/-
  ANSE.MasterMathRun2 -- the 24 locked master-math statements of run two.
  Generated by scripts/master_math/emit_lean.py from results/master_math_run2/.
  Fidelity is stated per theorem: `proxy` statements are arithmetic stand-ins
  and do NOT prove the named theorem; see the paper for the statement review.
-/

import Mathlib.GroupTheory.Index
import Mathlib.Algebra.Group.PUnit
import Mathlib.Data.Fintype.Card
import Mathlib.Analysis.InnerProductSpace.Basic
import Mathlib.Topology.MetricSpace.Contracting
import Mathlib.Data.Real.Basic
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic
import Mathlib.FieldTheory.Finite.Basic
import Mathlib.MeasureTheory.Integral.Bochner.Basic
import Mathlib.MeasureTheory.Constructions.BorelSpace.Real
import Mathlib.Topology.Order.IntermediateValue
import Mathlib.Topology.Instances.Real.Lemmas
import Mathlib.LinearAlgebra.Matrix.Charpoly.Basic
import Mathlib.Order.Zorn
import Mathlib.Topology.Baire.Lemmas
import Mathlib.Topology.Baire.CompleteMetrizable
import Mathlib.Logic.Function.Basic
import Mathlib.Data.Nat.Prime.Infinite
import Mathlib.Analysis.SpecialFunctions.Sqrt
import Mathlib.NumberTheory.Real.Irrational
import Mathlib.Analysis.Complex.Liouville
import Mathlib.Topology.MetricSpace.Pseudo.Defs
import Mathlib.Analysis.Complex.Polynomial.Basic
import Mathlib.Analysis.ODE.ExistUnique
import Mathlib.MeasureTheory.Integral.IntervalIntegral.FundThmCalculus
import Mathlib.Tactic.Ring
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.NormNum
import Mathlib.Tactic.Positivity
import Mathlib.Tactic.FieldSimp

namespace ANSE.MasterMathRun2

/-- Lagrange's theorem (index multiplicativity) [faithful]. Proof: reference control proof (no prover proof passed the kernel). -/
theorem mm01_lagrange {G : Type*} [Group G] [Finite G] (H : Subgroup G) :
    Nat.card H * H.index = Nat.card G := by exact Subgroup.card_mul_index H

/-- The false variant used as a negative control is refuted. -/
theorem mm01_lagrange_F_refuted : ¬ (∀ (G : Type) [Group G] [Finite G] (H : Subgroup G), Nat.card H + H.index = Nat.card G) := by
    intro h
    have := h PUnit ⊤
    simp at this

/-- Parallelogram law in real inner product spaces [faithful]. Proof: deepseek prover, round 0. -/
theorem mm02_parallelogram {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (x y : E) : ‖x + y‖ ^ 2 + ‖x - y‖ ^ 2 = 2 * (‖x‖ ^ 2 + ‖y‖ ^ 2) := by
    norm_num [norm_add_sq_real, norm_sub_sq_real, mul_add, mul_sub, mul_comm, mul_left_comm]
    <;> ring
    <;> simp [norm_add_sq_real, norm_sub_sq_real, mul_add, mul_sub, mul_comm, mul_left_comm]
    <;> ring
    <;> norm_num
    <;> linarith

/-- The false variant used as a negative control is refuted. -/
theorem mm02_parallelogram_F_refuted : ¬ (∀ x y : ℝ, ‖x + y‖ ^ 2 + ‖x - y‖ ^ 2 = ‖x‖ ^ 2 + ‖y‖ ^ 2) := by
    intro h
    have := h 1 0
    norm_num at this

/-- Banach contraction principle (unique fixed point) [faithful]. Proof: reference control proof (no prover proof passed the kernel). -/
theorem mm03_banach {X : Type*} [MetricSpace X] [CompleteSpace X] [Nonempty X]
    {c : NNReal} (hc : c < 1) {T : X → X} (hT : LipschitzWith c T) :
    ∃! x : X, T x = x := by
    have hK : ContractingWith c T := ⟨hc, hT⟩
    exact ⟨ContractingWith.fixedPoint T hK, hK.fixedPoint_isFixedPt,
      fun y hy => hK.fixedPoint_unique hy⟩

/-- The false variant used as a negative control is refuted. -/
theorem mm03_banach_F_refuted : ¬ (∀ T : ℝ → ℝ, LipschitzWith 1 T → ∃! x : ℝ, T x = x) := by
    intro h
    obtain ⟨x, -, hu⟩ := h id LipschitzWith.id
    have h1 := hu (x + 1) rfl
    linarith

/-- Cauchy-Riemann implies harmonic (second-derivative algebra only) [proxy]. Proof: deepseek prover, round 0. Derivatives are free real variables; no function or differentiability appears. -/
theorem mm04_cr_harmonic (u_xx u_yy v_xy v_yx : ℝ) (hCR1 : u_xx = v_yx)
    (hCR2 : u_yy = -v_xy) (hSym : v_yx = v_xy) : u_xx + u_yy = 0 := by
    have h1 : u_xx = v_yx := hCR1
    have h2 : u_yy = -v_xy := hCR2
    have h3 : v_yx = v_xy := hSym
    -- Simplify the expressions using the given equalities
    simp_all
    <;> linarith

/-- The false variant used as a negative control is refuted. -/
theorem mm04_cr_harmonic_F_refuted : ¬ (∀ u_xx u_yy v_xy v_yx : ℝ, u_xx = v_yx → u_yy = -v_xy → u_xx + u_yy = 0) := by
    intro h
    have := h 1 0 0 1 rfl (by norm_num)
    norm_num at this

/-- Gauss-Bonnet on the round sphere (K * Area = 2 pi chi, arithmetic only) [proxy]. Proof: deepseek prover, round 0. No surface or integral: K = 1/R^2 and Area = 4 pi R^2 are inserted by hand. Mathlib.Geometry.Manifold is not built locally. -/
theorem mm05_gauss_bonnet (R : ℝ) (hR : 0 < R) :
    (1 / R ^ 2) * (4 * Real.pi * R ^ 2) = 2 * Real.pi * 2 := by
    have h₁ : R ≠ 0 := by linarith
    field_simp [h₁]
    <;> ring
    <;> simp_all
    <;> field_simp [h₁]
    <;> ring
    <;> linarith

/-- The false variant used as a negative control is refuted. -/
theorem mm05_gauss_bonnet_F_refuted : ¬ (∀ R : ℝ, (1 / R ^ 2) * (4 * Real.pi * R ^ 2) = 4 * Real.pi) := by
    intro h
    have h0 := h 0
    have := Real.pi_pos
    norm_num at h0 <;> linarith

/-- Coboundary nilpotency d^2 = 0 on one oriented 2-simplex [proxy]. Proof: deepseek prover, round 0. A single telescoping sum, not a cochain complex. -/
theorem mm06_d_squared (f₀ f₁ f₂ : ℝ) : (f₁ - f₀) + (f₂ - f₁) + (f₀ - f₂) = 0 := by
    ring
    <;> simp_all only [add_assoc, add_left_comm, add_comm]
    <;> ring
    <;> omega

/-- The false variant used as a negative control is refuted. -/
theorem mm06_d_squared_F_refuted : ¬ (∀ f₀ f₁ f₂ : ℝ, (f₁ - f₀) + (f₂ - f₁) + (f₂ - f₀) = 0) := by
    intro h
    have := h 0 0 1
    norm_num at this

/-- Discrete Gronwall inequality [faithful]. Proof: deepseek prover, round 0. -/
theorem mm07_gronwall (E : ℕ → ℝ) (α : ℝ) (hα : 0 ≤ α) (hE : ∀ n, 0 ≤ E n)
    (h_step : ∀ n, E (n + 1) ≤ (1 + α) * E n) : ∀ n, E n ≤ (1 + α) ^ n * E 0 := by
    intro n
    induction n with
    | zero =>
      simp
    | succ n ih =>
      calc
        E (n + 1) ≤ (1 + α) * E n := h_step n
        _ ≤ (1 + α) * ((1 + α) ^ n * E 0) := by
          gcongr
          <;> simp_all [pow_succ]
          <;> nlinarith
        _ = (1 + α) ^ (n + 1) * E 0 := by
          simp [pow_succ, mul_assoc]
          <;> ring

/-- The false variant used as a negative control is refuted. -/
theorem mm07_gronwall_F_refuted : ¬ (∀ E : ℕ → ℝ, (∀ n, 0 ≤ E n) → (∀ n, E (n + 1) ≤ 2 * E n) → ∀ n, E n ≤ E 0) := by
    intro h
    have := h (fun n => 2 ^ n) (fun n => by positivity)
      (fun n => le_of_eq (by ring)) 1
    norm_num at this

/-- Fermat's little theorem in ZMod p [faithful]. Proof: deepseek prover, round 0. -/
theorem mm08_fermat (p : ℕ) [Fact p.Prime] (a : ZMod p) (ha : a ≠ 0) :
    a ^ (p - 1) = 1 := by
    have h := FiniteField.pow_card_sub_one_eq_one a ha
    simp_all

/-- The false variant used as a negative control is refuted. -/
theorem mm08_fermat_F_refuted : ¬ (∀ a : ZMod 5, a ^ (5 - 1) = 1) := by decide

/-- Markov's inequality (Bochner integral) [faithful]. Proof: deepseek prover, round 0. Upgraded from run one's pointwise proxy `(if x ≥ ε then ε else 0) ≤ x`. -/
theorem mm09_markov {α : Type*} [MeasurableSpace α] (μ : MeasureTheory.Measure α)
    {f : α → ℝ} (hf_nonneg : 0 ≤ᵐ[μ] f) (hf_int : MeasureTheory.Integrable f μ)
    (ε : ℝ) : ε * μ.real {x | ε ≤ f x} ≤ ∫ x, f x ∂μ := by
    have h₁ : ε * μ.real {x | ε ≤ f x} ≤ ∫ x, f x ∂μ := by
      have h₂ : ε * μ.real {x | ε ≤ f x} ≤ ∫ x, f x ∂μ := by
        have h₃ : ε * μ.real {x | ε ≤ f x} ≤ ∫ x, f x ∂μ := by
          -- Use the fact that the integral of f is greater than or equal to the integral of the indicator function times f
          exact?
        exact h₃
      exact h₂
    exact h₁

/-- The false variant used as a negative control is refuted. -/
theorem mm09_markov_F_refuted : ¬ (∀ (f : ℝ → ℝ) (ε : ℝ), ε * (MeasureTheory.Measure.dirac (0 : ℝ)).real {x | ε ≤ f x}
    ≤ (∫ x, f x ∂(MeasureTheory.Measure.dirac (0 : ℝ))) / 2) := by
    intro h
    have := h (fun _ => 1) 1
    simp at this
    norm_num at this

/-- Cauchy-Schwarz, signed form [faithful]. Proof: reference control proof (no prover proof passed the kernel). -/
theorem mm10a_cauchy_schwarz {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (x y : E) : @inner ℝ E _ x y ≤ ‖x‖ * ‖y‖ := by exact real_inner_le_norm x y

/-- The false variant used as a negative control is refuted. -/
theorem mm10a_cauchy_schwarz_F_refuted : ¬ (∀ x y : ℝ, @inner ℝ ℝ _ x y ≤ ‖x‖ * ‖y‖ - 1) := by
    intro h
    have := h 0 0
    simp at this
    norm_num at this

/-- Cauchy-Schwarz, absolute form [faithful]. Proof: deepseek prover, round 0. -/
theorem mm10b_cauchy_schwarz_abs {E : Type*} [NormedAddCommGroup E]
    [InnerProductSpace ℝ E] (x y : E) : |@inner ℝ E _ x y| ≤ ‖x‖ * ‖y‖ := by
    have h₁ : |@inner ℝ E _ x y| ≤ ‖x‖ * ‖y‖ := by
      rw [← Real.norm_eq_abs]
      -- Use the fact that the absolute value of the inner product is less than or equal to the product of the norms.
      exact?
    exact h₁

/-- The false variant used as a negative control is refuted. -/
theorem mm10b_cauchy_schwarz_abs_F_refuted : ¬ (∀ x y : ℝ, |@inner ℝ ℝ _ x y| < ‖x‖ * ‖y‖) := by
    intro h
    have := h 0 0
    simp at this

/-- Intermediate value theorem [faithful]. Proof: deepseek prover, round 0. One orientation only (f a <= y <= f b); the f b <= f a case is not stated. -/
theorem mm11_ivt (f : ℝ → ℝ) (a b y : ℝ) (hab : a ≤ b)
    (hf : ContinuousOn f (Set.Icc a b)) (hy : y ∈ Set.Icc (f a) (f b)) :
    ∃ x ∈ Set.Icc a b, f x = y := by
    obtain ⟨x, hx⟩ := intermediate_value_Icc hab hf hy
    exact ⟨x, hx⟩

/-- The false variant used as a negative control is refuted. -/
theorem mm11_ivt_F_refuted : ¬ (∀ (f : ℝ → ℝ) (a b y : ℝ), a ≤ b → y ∈ Set.Icc (f a) (f b) →
    ∃ x ∈ Set.Icc a b, f x = y) := by
    intro h
    obtain ⟨x, -, hx⟩ := h (fun x => if x < 1 then 0 else 2) 0 1 1 (by norm_num)
      (by norm_num)
    split_ifs at hx <;> norm_num at hx

/-- Cayley-Hamilton theorem [faithful]. Proof: reference control proof (no prover proof passed the kernel). -/
theorem mm12_cayley_hamilton {n R : Type*} [Fintype n] [DecidableEq n] [CommRing R]
    (M : Matrix n n R) : Polynomial.aeval M M.charpoly = 0 := by exact Matrix.aeval_self_charpoly M

/-- The false variant used as a negative control is refuted. -/
theorem mm12_cayley_hamilton_F_refuted : ¬ (∀ M : Matrix (Fin 1) (Fin 1) ℤ, Polynomial.aeval M (Polynomial.X : Polynomial ℤ) = 0) := by
    intro h
    have := h 1
    simp at this

/-- Zorn's lemma (maximal element form) [faithful]. Proof: reference control proof (no prover proof passed the kernel). -/
theorem mm13_zorn {α : Type*} [PartialOrder α]
    (h : ∀ c : Set α, IsChain (· ≤ ·) c → ∃ ub, ∀ a ∈ c, a ≤ ub) :
    ∃ m : α, ∀ a, m ≤ a → a = m := by
    obtain ⟨m, hm⟩ := zorn_le (fun c hc => h c hc)
    exact ⟨m, fun a ha => le_antisymm (hm ha) ha⟩

/-- The false variant used as a negative control is refuted. -/
theorem mm13_zorn_F_refuted : ¬ (∀ (α : Type) [PartialOrder α], ∃ m : α, ∀ a, m ≤ a → a = m) := by
    intro h
    obtain ⟨m, hm⟩ := h ℕ
    have := hm (m + 1) (by omega)
    omega

/-- Baire category theorem (complete metric spaces) [faithful]. Proof: reference control proof (no prover proof passed the kernel). -/
theorem mm14_baire {X : Type*} [MetricSpace X] [CompleteSpace X] (f : ℕ → Set X)
    (ho : ∀ n, IsOpen (f n)) (hd : ∀ n, Dense (f n)) : Dense (⋂ n, f n) := by exact dense_iInter_of_isOpen ho hd

/-- The false variant used as a negative control is refuted. -/
theorem mm14_baire_F_refuted : ¬ (∀ f : ℕ → Set ℝ, (∀ n, IsOpen (f n)) → (∀ n, Dense (f n)) → (⋂ n, f n) = Set.univ) := by
    intro h
    have hu := h (fun _ => ({0}ᶜ : Set ℝ)) (fun _ => isOpen_compl_singleton)
      (fun _ => dense_compl_singleton 0)
    have h0 : (0 : ℝ) ∈ ⋂ _n : ℕ, ({0}ᶜ : Set ℝ) := by rw [hu]; trivial
    simp at h0

/-- Cantor's theorem (no surjection onto the power set) [faithful]. Proof: goedel prover, round 0. -/
theorem mm15_cantor {α : Type*} (f : α → Set α) : ¬ Function.Surjective f := by
    have h_main : ¬ Function.Surjective f := by
      intro h_surj
      -- Define the set S = {x : α | x ∉ f x}
      let S : Set α := {x : α | x ∉ f x}
      -- Assume for contradiction that S is in the image of f
      have h₁ : ∃ (y : α), f y = S := by
        -- Since f is surjective, there exists y such that f y = S
        have h₂ : S ∈ Set.range f := by
          apply h_surj
        -- Obtain y such that f y = S
        rcases h₂ with ⟨y, hy⟩
        exact ⟨y, by simpa using hy⟩
      -- Obtain y such that f y = S
      rcases h₁ with ⟨y, hy⟩
      -- Consider whether y ∈ S or y ∉ S
      by_cases h : y ∈ S
      · -- Case: y ∈ S
        have h₂ : y ∉ f y := h
        have h₃ : f y = S := hy
        have h₄ : y ∉ S := by simpa [h₃] using h₂
        contradiction
      · -- Case: y ∉ S
        have h₂ : y ∈ f y := by
          have h₃ : y ∉ S := h
          have h₄ : y ∉ f y → False := by
            intro h₅
            have h₆ : y ∈ S := by
              have h₇ : y ∉ f y := h₅
              have h₈ : y ∈ S := by
                simpa [S, Set.mem_setOf_eq] using h₇
              exact h₈
            contradiction
          by_contra h₅
          exact h₄ h₅
        have h₃ : f y = S := hy
        have h₄ : y ∈ S := by simpa [h₃] using h₂
        contradiction
    exact h_main

/-- The false variant used as a negative control is refuted. -/
theorem mm15_cantor_F_refuted : ¬ (∀ (α : Type) (f : α → α), ¬ Function.Surjective f) := by
    intro h
    exact h Unit id Function.surjective_id

/-- Infinitude of primes [faithful]. Proof: deepseek prover, round 0. -/
theorem mm16_primes (n : ℕ) : ∃ p, n ≤ p ∧ Nat.Prime p := by
    have h₁ := Nat.exists_infinite_primes n
    obtain ⟨p, hp₁, hp₂⟩ := h₁
    exact ⟨p, by linarith, hp₂⟩

/-- The false variant used as a negative control is refuted. -/
theorem mm16_primes_F_refuted : ¬ (∃ N : ℕ, ∀ p, Nat.Prime p → p ≤ N) := by
    rintro ⟨N, hN⟩
    obtain ⟨p, hp, hpp⟩ := Nat.exists_infinite_primes (N + 1)
    have := hN p hpp
    omega

/-- AM-GM inequality, two variables [faithful]. Proof: deepseek prover, round 0. -/
theorem mm17_am_gm (x y : ℝ) (hx : 0 ≤ x) (hy : 0 ≤ y) :
    Real.sqrt (x * y) ≤ (x + y) / 2 := by
    have h₁ : 0 ≤ x * y := mul_nonneg hx hy
    have h₂ : 0 ≤ (x + y) / 2 := by linarith
    nlinarith [sq_nonneg (x - y), Real.sq_sqrt (show 0 ≤ x * y by positivity),
      Real.sqrt_nonneg (x * y), sq_nonneg (Real.sqrt (x * y) - (x + y) / 2)]

/-- The false variant used as a negative control is refuted. -/
theorem mm17_am_gm_F_refuted : ¬ (∀ x y : ℝ, Real.sqrt (x * y) ≤ (x + y) / 2) := by
    intro h
    have := h (-1) (-1)
    norm_num at this

/-- Irrationality of sqrt 2 [faithful]. Proof: reference control proof (no prover proof passed the kernel). -/
theorem mm18_sqrt2 : Irrational (Real.sqrt 2) := by exact irrational_sqrt_two

/-- The false variant used as a negative control is refuted. -/
theorem mm18_sqrt2_F_refuted : ¬ (Irrational (Real.sqrt 4)) := by
    intro h
    apply h
    refine ⟨2, ?_⟩
    rw [show (4 : ℝ) = 2 ^ 2 by norm_num, Real.sqrt_sq (by norm_num)]
    norm_num

/-- Liouville's theorem [faithful]. Proof: reference control proof (no prover proof passed the kernel). -/
theorem mm19_liouville (f : ℂ → ℂ) (hf : Differentiable ℂ f)
    (hb : Bornology.IsBounded (Set.range f)) (z w : ℂ) : f z = f w := by exact hf.apply_eq_apply_of_bounded hb z w

/-- The false variant used as a negative control is refuted. -/
theorem mm19_liouville_F_refuted : ¬ (∀ f : ℂ → ℂ, Differentiable ℂ f → ∀ z w : ℂ, f z = f w) := by
    intro h
    have := h id differentiable_id 0 1
    simp at this

/-- Triangle inequality in metric spaces [definitional]. Proof: deepseek prover, round 0. In Mathlib this is a field of the MetricSpace structure; a pass shows lookup, not proof. -/
theorem mm20_triangle {X : Type*} [MetricSpace X] (x y z : X) :
    dist x z ≤ dist x y + dist y z := by
    have h₁ := dist_triangle x y z
    have h₂ := dist_comm y z
    have h₃ := dist_comm x y
    have h₄ := dist_comm x z
    linarith

/-- The false variant used as a negative control is refuted. -/
theorem mm20_triangle_F_refuted : ¬ (∀ x y z : ℝ, dist x z ≤ dist x y) := by
    intro h
    have := h 0 0 1
    norm_num [Real.dist_eq] at this

/-- Fundamental theorem of algebra [faithful]. Proof: reference control proof (no prover proof passed the kernel). -/
theorem mm21_fta (p : Polynomial ℂ) (hp : 0 < p.degree) : ∃ z : ℂ, p.IsRoot z := by exact Complex.exists_root hp

/-- The false variant used as a negative control is refuted. -/
theorem mm21_fta_F_refuted : ¬ (∀ p : Polynomial ℝ, 0 < p.degree → ∃ z : ℝ, p.IsRoot z) := by
    intro h
    obtain ⟨z, hz⟩ := h (Polynomial.X ^ 2 + Polynomial.C 1)
      (by rw [Polynomial.degree_X_pow_add_C (by norm_num)]; norm_num)
    simp at hz
    nlinarith [sq_nonneg z]

/-- Picard-Lindelof uniqueness for Lipschitz ODEs [faithful]. Proof: reference control proof (no prover proof passed the kernel). -/
theorem mm22_picard_lindelof (v : ℝ → ℝ → ℝ) (K : NNReal)
    (hv : ∀ t, LipschitzWith K (v t)) (f g : ℝ → ℝ) (a b : ℝ)
    (hf : ∀ t, HasDerivAt f (v t (f t)) t) (hg : ∀ t, HasDerivAt g (v t (g t)) t)
    (ha : f a = g a) : Set.EqOn f g (Set.Icc a b) := by
    exact ODE_solution_unique hv (fun t _ => (hf t).continuousAt.continuousWithinAt)
      (fun t _ => (hf t).hasDerivWithinAt)
      (fun t _ => (hg t).continuousAt.continuousWithinAt)
      (fun t _ => (hg t).hasDerivWithinAt) ha

/-- The false variant used as a negative control is refuted. -/
theorem mm22_picard_lindelof_F_refuted : ¬ (∀ f g : ℝ → ℝ, (∀ t, HasDerivAt f 0 t) → (∀ t, HasDerivAt g 0 t) →
    Set.EqOn f g (Set.Icc 0 1)) := by
    intro h
    have := h (fun _ => 0) (fun _ => 1) (fun t => hasDerivAt_const t 0)
      (fun t => hasDerivAt_const t 1) (by norm_num : (0 : ℝ) ∈ Set.Icc 0 1)
    norm_num at this

/-- Stokes' theorem in dimension one (fundamental theorem of calculus) [special-case]. Proof: reference control proof (no prover proof passed the kernel). General Stokes on manifolds is not stateable here (Geometry.Manifold not built); this is the n = 1 instance, labelled as such. -/
theorem mm23_stokes_1d (f f' : ℝ → ℝ) (a b : ℝ)
    (hf : ∀ x ∈ Set.uIcc a b, HasDerivAt f (f' x) x)
    (hint : IntervalIntegrable f' MeasureTheory.volume a b) :
    ∫ x in a..b, f' x = f b - f a := by exact intervalIntegral.integral_eq_sub_of_hasDerivAt hf hint

/-- The false variant used as a negative control is refuted. -/
theorem mm23_stokes_1d_F_refuted : ¬ (∀ f f' : ℝ → ℝ, IntervalIntegrable f' MeasureTheory.volume 0 1 →
    ∫ x in (0 : ℝ)..1, f' x = f 1 - f 0) := by
    intro h
    have := h id (fun _ => 0) intervalIntegrable_const
    simp at this

end ANSE.MasterMathRun2

#print axioms ANSE.MasterMathRun2.mm01_lagrange
#print axioms ANSE.MasterMathRun2.mm01_lagrange_F_refuted
#print axioms ANSE.MasterMathRun2.mm02_parallelogram
#print axioms ANSE.MasterMathRun2.mm02_parallelogram_F_refuted
#print axioms ANSE.MasterMathRun2.mm03_banach
#print axioms ANSE.MasterMathRun2.mm03_banach_F_refuted
#print axioms ANSE.MasterMathRun2.mm04_cr_harmonic
#print axioms ANSE.MasterMathRun2.mm04_cr_harmonic_F_refuted
#print axioms ANSE.MasterMathRun2.mm05_gauss_bonnet
#print axioms ANSE.MasterMathRun2.mm05_gauss_bonnet_F_refuted
#print axioms ANSE.MasterMathRun2.mm06_d_squared
#print axioms ANSE.MasterMathRun2.mm06_d_squared_F_refuted
#print axioms ANSE.MasterMathRun2.mm07_gronwall
#print axioms ANSE.MasterMathRun2.mm07_gronwall_F_refuted
#print axioms ANSE.MasterMathRun2.mm08_fermat
#print axioms ANSE.MasterMathRun2.mm08_fermat_F_refuted
#print axioms ANSE.MasterMathRun2.mm09_markov
#print axioms ANSE.MasterMathRun2.mm09_markov_F_refuted
#print axioms ANSE.MasterMathRun2.mm10a_cauchy_schwarz
#print axioms ANSE.MasterMathRun2.mm10a_cauchy_schwarz_F_refuted
#print axioms ANSE.MasterMathRun2.mm10b_cauchy_schwarz_abs
#print axioms ANSE.MasterMathRun2.mm10b_cauchy_schwarz_abs_F_refuted
#print axioms ANSE.MasterMathRun2.mm11_ivt
#print axioms ANSE.MasterMathRun2.mm11_ivt_F_refuted
#print axioms ANSE.MasterMathRun2.mm12_cayley_hamilton
#print axioms ANSE.MasterMathRun2.mm12_cayley_hamilton_F_refuted
#print axioms ANSE.MasterMathRun2.mm13_zorn
#print axioms ANSE.MasterMathRun2.mm13_zorn_F_refuted
#print axioms ANSE.MasterMathRun2.mm14_baire
#print axioms ANSE.MasterMathRun2.mm14_baire_F_refuted
#print axioms ANSE.MasterMathRun2.mm15_cantor
#print axioms ANSE.MasterMathRun2.mm15_cantor_F_refuted
#print axioms ANSE.MasterMathRun2.mm16_primes
#print axioms ANSE.MasterMathRun2.mm16_primes_F_refuted
#print axioms ANSE.MasterMathRun2.mm17_am_gm
#print axioms ANSE.MasterMathRun2.mm17_am_gm_F_refuted
#print axioms ANSE.MasterMathRun2.mm18_sqrt2
#print axioms ANSE.MasterMathRun2.mm18_sqrt2_F_refuted
#print axioms ANSE.MasterMathRun2.mm19_liouville
#print axioms ANSE.MasterMathRun2.mm19_liouville_F_refuted
#print axioms ANSE.MasterMathRun2.mm20_triangle
#print axioms ANSE.MasterMathRun2.mm20_triangle_F_refuted
#print axioms ANSE.MasterMathRun2.mm21_fta
#print axioms ANSE.MasterMathRun2.mm21_fta_F_refuted
#print axioms ANSE.MasterMathRun2.mm22_picard_lindelof
#print axioms ANSE.MasterMathRun2.mm22_picard_lindelof_F_refuted
#print axioms ANSE.MasterMathRun2.mm23_stokes_1d
#print axioms ANSE.MasterMathRun2.mm23_stokes_1d_F_refuted
