import BAOCert.P2.Fit
import BAOCert.P2.Fit_Tamper
import BAOCert.P2.Slab_O000_O005
import BAOCert.P2.Slab_O005_O010
import BAOCert.P2.Slab_O010_O015
import BAOCert.P2.Slab_O015_O020
import BAOCert.P2.Slab_O020_O022
import BAOCert.P2.Slab_O022_O024
import BAOCert.P2.Slab_O024_O025
import BAOCert.P2.Slab_O025_O026
import BAOCert.P2.Slab_O034_O035
import BAOCert.P2.Slab_O035_O036
import BAOCert.P2.Slab_O036_O038
import BAOCert.P2.Slab_O038_O040
import BAOCert.P2.Slab_O040_O045
import BAOCert.P2.Slab_O045_O050
import BAOCert.P2.Slab_O050_O060
import BAOCert.P2.Slab_O060_O070
import BAOCert.P2.Slab_O070_O080
import BAOCert.P2.Slab_O080_O090
import BAOCert.P2.Slab_O090_O100
import BAOCert.P2.Slab_O029_O030
import BAOCert.P2.EdS
import BAOCert.P2.Ref_O000_R1_40
import BAOCert.P2.Ref_R1_40_O005
import BAOCert.P2.Ref_O005_O010
import BAOCert.P2.Ref_O010_R1_8
import BAOCert.P2.Ref_R1_8_O015
import BAOCert.P2.Ref_O015_R7_40
import BAOCert.P2.Ref_R7_40_O020
import BAOCert.P2.Ref_O020_O022
import BAOCert.P2.Ref_O022_R23_100
import BAOCert.P2.Ref_R23_100_O024
import BAOCert.P2.Ref_O024_R49_200
import BAOCert.P2.Ref_R49_200_O025
import BAOCert.P2.Ref_O025_R101_400
import BAOCert.P2.Ref_R101_400_R51_200
import BAOCert.P2.Ref_O035_R141_400
import BAOCert.P2.Ref_R141_400_R71_200
import BAOCert.P2.Ref_R71_200_O036
import BAOCert.P2.Ref_O036_R37_100
import BAOCert.P2.Ref_R37_100_O038
import BAOCert.P2.Ref_O038_O040
import BAOCert.P2.Ref_O040_R17_40
import BAOCert.P2.Ref_R17_40_O045
import BAOCert.P2.Ref_O045_O050
import BAOCert.P2.Ref_O050_R11_20
import BAOCert.P2.Ref_R11_20_O060
import BAOCert.P2.Ref_O060_O070
import BAOCert.P2.Ref_O070_O080
import BAOCert.P2.Ref_O080_O090
import BAOCert.P2.Ref_O090_O100
import BAOCert.P2.Data

/-! Generated by evaluate_p2.py: axiom audit of every P2 case theorem, the data check and the generic layer, plus planted controls. -/

#print axioms BAOCert.P2.Data.P_is_inverse
#print axioms BAOCert.Ex.ieval_sound
#print axioms BAOCert.chi2_lower_of_env
#print axioms BAOCert.chi2_mem_at_K0
#print axioms BAOCert.profile_lower
#print axioms BAOCert.wV_anti_Om
#print axioms BAOCert.chi_anti_Om
#print axioms BAOCert.P2.Fit.chi2_fit
#print axioms BAOCert.P2.Fit_Tamper.chi2_fit
#print axioms BAOCert.P2.Slab_O000_O005.chi2_slab
#print axioms BAOCert.P2.Slab_O005_O010.chi2_slab
#print axioms BAOCert.P2.Slab_O010_O015.chi2_slab
#print axioms BAOCert.P2.Slab_O015_O020.chi2_slab
#print axioms BAOCert.P2.Slab_O020_O022.chi2_slab
#print axioms BAOCert.P2.Slab_O022_O024.chi2_slab
#print axioms BAOCert.P2.Slab_O024_O025.chi2_slab
#print axioms BAOCert.P2.Slab_O025_O026.chi2_slab
#print axioms BAOCert.P2.Slab_O034_O035.chi2_slab
#print axioms BAOCert.P2.Slab_O035_O036.chi2_slab
#print axioms BAOCert.P2.Slab_O036_O038.chi2_slab
#print axioms BAOCert.P2.Slab_O038_O040.chi2_slab
#print axioms BAOCert.P2.Slab_O040_O045.chi2_slab
#print axioms BAOCert.P2.Slab_O045_O050.chi2_slab
#print axioms BAOCert.P2.Slab_O050_O060.chi2_slab
#print axioms BAOCert.P2.Slab_O060_O070.chi2_slab
#print axioms BAOCert.P2.Slab_O070_O080.chi2_slab
#print axioms BAOCert.P2.Slab_O080_O090.chi2_slab
#print axioms BAOCert.P2.Slab_O090_O100.chi2_slab
#print axioms BAOCert.P2.Slab_O029_O030.chi2_slab
#print axioms BAOCert.P2.EdS.chi2_slab
#print axioms BAOCert.P2.Ref_O000_R1_40.chi2_slab
#print axioms BAOCert.P2.Ref_R1_40_O005.chi2_slab
#print axioms BAOCert.P2.Ref_O005_O010.chi2_slab
#print axioms BAOCert.P2.Ref_O010_R1_8.chi2_slab
#print axioms BAOCert.P2.Ref_R1_8_O015.chi2_slab
#print axioms BAOCert.P2.Ref_O015_R7_40.chi2_slab
#print axioms BAOCert.P2.Ref_R7_40_O020.chi2_slab
#print axioms BAOCert.P2.Ref_O020_O022.chi2_slab
#print axioms BAOCert.P2.Ref_O022_R23_100.chi2_slab
#print axioms BAOCert.P2.Ref_R23_100_O024.chi2_slab
#print axioms BAOCert.P2.Ref_O024_R49_200.chi2_slab
#print axioms BAOCert.P2.Ref_R49_200_O025.chi2_slab
#print axioms BAOCert.P2.Ref_O025_R101_400.chi2_slab
#print axioms BAOCert.P2.Ref_R101_400_R51_200.chi2_slab
#print axioms BAOCert.P2.Ref_O035_R141_400.chi2_slab
#print axioms BAOCert.P2.Ref_R141_400_R71_200.chi2_slab
#print axioms BAOCert.P2.Ref_R71_200_O036.chi2_slab
#print axioms BAOCert.P2.Ref_O036_R37_100.chi2_slab
#print axioms BAOCert.P2.Ref_R37_100_O038.chi2_slab
#print axioms BAOCert.P2.Ref_O038_O040.chi2_slab
#print axioms BAOCert.P2.Ref_O040_R17_40.chi2_slab
#print axioms BAOCert.P2.Ref_R17_40_O045.chi2_slab
#print axioms BAOCert.P2.Ref_O045_O050.chi2_slab
#print axioms BAOCert.P2.Ref_O050_R11_20.chi2_slab
#print axioms BAOCert.P2.Ref_R11_20_O060.chi2_slab
#print axioms BAOCert.P2.Ref_O060_O070.chi2_slab
#print axioms BAOCert.P2.Ref_O070_O080.chi2_slab
#print axioms BAOCert.P2.Ref_O080_O090.chi2_slab
#print axioms BAOCert.P2.Ref_O090_O100.chi2_slab

theorem ctl_sorry : BAOCert.P2.Data.chi2DESI 1 1 = 0 := by sorry
axiom ctl_cheat : False
theorem ctl_axiom : BAOCert.P2.Data.chi2DESI 1 1 = 0 := ctl_cheat.elim
#print axioms ctl_sorry
#print axioms ctl_axiom
