#!/usr/bin/env python3
"""Untrusted emitter for the P1 certified BAO pilot.

For Om = p/q and the grid x_i = i/S it computes integers lo_i, hi_i with
    lo_i^2 a_i <= D^2 b <= hi_i^2 a_i,   A(x_i) = a_i / b exactly,
so that lo_i/D <= 1/E(x_i) <= hi_i/D. Lean re-checks every inequality with `decide +kernel`; nothing here is trusted.
It writes a Lean module with the table and one theorem per DESI DR2 redshift, and a JSON file with the exact
rational bounds (for the paper and the controls).

Usage:
    python3 scripts/certified_numerics/emit_bao_tables.py --name Fit --p 29743 --q 100000
    python3 scripts/certified_numerics/emit_bao_tables.py --name EdS --p 1 --q 1
    python3 scripts/certified_numerics/emit_bao_tables.py --name FitOm101 --p 3004043 --q 10000000
    python3 scripts/certified_numerics/emit_bao_tables.py --name Tampered --p 29743 --q 100000 --tamper 1234
"""

from __future__ import annotations

import argparse
import json
from fractions import Fraction
from math import isqrt
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
S = 2000
D = 10**12
CHUNK = 128
# DESI DR2 effective redshifts (desi_bao_dr2/desi_gaussian_bao_ALL_GCcomb_mean.txt), all multiples of 1/S
Z_NODES = {"z0295": 590, "z0510": 1020, "z0706": 1412, "z0934": 1868, "z1321": 2642, "z1484": 2968, "z2330": 4660}
N_MAX = max(Z_NODES.values())
C_OVER_100_HRD = Fraction(299792458, 10154300)  # c [km/s] / (100 * h r_d [Mpc]) at h r_d = 101.543


def a_num(p: int, q: int, i: int) -> int:
    return p * (S + i) ** 3 + (q - p) * S**3


def b_den(q: int) -> int:
    return q * S**3


def node(p: int, q: int, i: int) -> tuple[int, int]:
    a, b = a_num(p, q, i), b_den(q)
    lo = isqrt(D * D * b // a)  # floor(D sqrt(b/a)) = floor(D / sqrt(A))
    hi = lo + 1
    assert lo * lo * a <= D * D * b <= hi * hi * a
    return lo, hi


def lower_sum(tbl: list[tuple[int, int]]) -> int:
    return sum(lo for lo, _ in tbl[1:])


def upper_sum(tbl: list[tuple[int, int]]) -> int:
    return sum(hi for _, hi in tbl[:-1])


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--name", required=True)
    ap.add_argument("--p", type=int, required=True)
    ap.add_argument("--q", type=int, required=True)
    ap.add_argument("--tamper", type=int, help="node whose hi is decreased by 10^6 (negative control C2)")
    args = ap.parse_args()
    p, q = args.p, args.q
    tbl = [node(p, q, i) for i in range(N_MAX + 1)]
    if args.tamper is not None:
        lo, hi = tbl[args.tamper]
        tbl[args.tamper] = (lo, hi - 10**6)
    ns = f"BAOCert.{args.name}"
    P, Q, Sn, Dn = f"({p} : ℕ)", f"({q} : ℕ)", f"({S} : ℕ)", f"({D} : ℕ)"
    out: list[str] = [
        "import BAOCert.Core",
        "",
        f"/-! Generated by scripts/certified_numerics/emit_bao_tables.py (untrusted): Om = {p}/{q}, S = {S}, D = 10^12.",
        "Every number below is re-checked by the kernel. -/",
        "",
        f"namespace {ns}",
        "open BAOCert",
        "",
    ]
    chunks = [tbl[k:k + CHUNK] for k in range(0, len(tbl), CHUNK)]
    for j, ch in enumerate(chunks):
        out.append(f"def c{j} : List (ℕ × ℕ) := [" + ", ".join(f"({lo}, {hi})" for lo, hi in ch) + "]")
    out += [
        "",
        "/-- `(lo_i, hi_i)` for nodes `i = 0 .. " + str(N_MAX) + "` (chunks of " + str(CHUNK) + " keep elaboration shallow). -/",
        "def tbl : List (ℕ × ℕ) := " + " ++ ".join(f"c{j}" for j in range(len(chunks))),
        "",
        f"theorem tbl_check : checkFrom {p} {q} {S} {D} 0 tbl = true := by decide +kernel",
        "",
    ]
    report: dict[str, object] = {"name": args.name, "Om": f"{p}/{q}", "S": S, "D": D, "tampered_node": args.tamper, "redshifts": {}}
    if args.tamper is None:
        for label, n in Z_NODES.items():
            sub = tbl[: n + 1]
            L, U = lower_sum(sub), upper_sum(sub)
            lo_n, hi_n = tbl[n]
            out += [
                f"/-- χ(z) at z = {n}/{S} is enclosed in [{L}/(D·S), {U}/(D·S)]. -/",
                f"theorem chi_{label} :",
                f"    ((({L} : ℕ) : ℝ) / ((({D} : ℕ) : ℝ) * (({S} : ℕ) : ℝ))) ≤ chi ((({p} : ℕ) : ℝ) / (({q} : ℕ) : ℝ)) ((({n} : ℕ) : ℝ) / (({S} : ℕ) : ℝ)) ∧",
                f"      chi ((({p} : ℕ) : ℝ) / (({q} : ℕ) : ℝ)) ((({n} : ℕ) : ℝ) / (({S} : ℕ) : ℝ)) ≤ ((({U} : ℕ) : ℝ) / ((({D} : ℕ) : ℝ) * (({S} : ℕ) : ℝ))) := by",
                f"  have h := chi_bounds (p := {p}) (q := {q}) (S := {S}) (D := {D}) (n := {n}) (by norm_num) (by norm_num) (by norm_num) (by norm_num)",
                f"    (tbl.take {n + 1}) (by decide +kernel) (by decide +kernel)",
                f"  have hl : lowerSum (tbl.take {n + 1}) = {L} := by decide +kernel",
                f"  have hu : upperSum (tbl.take {n + 1}) = {U} := by decide +kernel",
                "  rw [hl, hu] at h",
                "  exact h",
                "",
                f"/-- 1/E(z) at z = {n}/{S} (gives D_H/r_d) is enclosed in [{lo_n}/D, {hi_n}/D]. -/",
                f"theorem invE_{label} :",
                f"    ((({lo_n} : ℕ) : ℝ) / (({D} : ℕ) : ℝ)) ≤ invE ((({p} : ℕ) : ℝ) / (({q} : ℕ) : ℝ)) ((({n} : ℕ) : ℝ) / (({S} : ℕ) : ℝ)) ∧",
                f"      invE ((({p} : ℕ) : ℝ) / (({q} : ℕ) : ℝ)) ((({n} : ℕ) : ℝ) / (({S} : ℕ) : ℝ)) ≤ ((({hi_n} : ℕ) : ℝ) / (({D} : ℕ) : ℝ)) :=",
                f"  node_bounds (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by decide +kernel : nodeOK {p} {q} {S} {D} {n} {lo_n} {hi_n} = true)",
                "",
            ]
            chi_lo, chi_hi = Fraction(L, D * S), Fraction(U, D * S)
            ie_lo, ie_hi = Fraction(lo_n, D), Fraction(hi_n, D)
            report["redshifts"][label] = {
                "n": n, "z": str(Fraction(n, S)), "chi_lo": f"{L}/{D * S}", "chi_hi": f"{U}/{D * S}",
                "chi_lo_float": float(chi_lo), "chi_hi_float": float(chi_hi),
                "chi_rel_width": float((chi_hi - chi_lo) / chi_lo),
                "invE_lo": f"{lo_n}/{D}", "invE_hi": f"{hi_n}/{D}", "invE_lo_float": float(ie_lo), "invE_hi_float": float(ie_hi),
                "DM_over_rd_lo": float(C_OVER_100_HRD * chi_lo), "DM_over_rd_hi": float(C_OVER_100_HRD * chi_hi),
                "DH_over_rd_lo": float(C_OVER_100_HRD * ie_lo), "DH_over_rd_hi": float(C_OVER_100_HRD * ie_hi),
            }
    out.append(f"end {ns}")
    lean_path = REPO / "formal_cert" / "BAOCert" / f"{args.name}.lean"
    lean_path.write_text("\n".join(out) + "\n", encoding="utf-8")
    res_dir = REPO / "results" / "certified_numerics" / "P1_bao"
    res_dir.mkdir(parents=True, exist_ok=True)
    (res_dir / f"bounds_{args.name}.json").write_text(json.dumps(report, indent=1) + "\n")
    worst = max((v["chi_rel_width"] for v in report["redshifts"].values()), default=None)
    print(json.dumps({"lean": str(lean_path.relative_to(REPO)), "bytes": lean_path.stat().st_size, "worst_chi_rel_width": worst}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
