#!/usr/bin/env python3
"""Untrusted emitter for pilot P2 (certified DESI DR2 BAO likelihood).

Subcommands:
  table --name N --p P --q Q --S S [--only-check]   Lean module BAOCert.P2.T_<N>: integer table, its kernel check, and
                                                    Iv-form enclosures of chi, 1/E (and w for the D_V row) at the
                                                    DESI DR2 redshifts; JSON with the rational bounds.
  data                                              BAOCert.P2.Data: DESI DR2 data vector, covariance, exact inverse
                                                    (kernel-checked), the base-quantity list xsOf and chi2DESI.
  case ...                                          see emit_case()
Nothing here is trusted; every number is re-checked by Lean's kernel.
"""

from __future__ import annotations

import argparse
import json
from fractions import Fraction
from math import isqrt
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
LEAN_DIR = REPO / "formal_cert" / "BAOCert" / "P2"
RES = REPO / "results" / "certified_numerics" / "P2_likelihood"
DR2 = Path("/mnt/disks/disk-socrateai-local-1/dualscale-data-r3/desi_sdss_bao/desi_bao_dr2")
D = 10**12
CHUNK = 128
GROUP = 32
Z2000 = [590, 1020, 1412, 1868, 2642, 2968, 4660]  # DESI DR2 z_eff * 2000
WD = 10**15  # denominator of the cube-root bounds


def a_num(p: int, q: int, S: int, i: int) -> int:
    return p * (S + i) ** 3 + (q - p) * S**3


def node(p: int, q: int, S: int, i: int) -> tuple[int, int]:
    a, b = a_num(p, q, S, i), q * S**3
    lo = isqrt(D * D * b // a)
    hi = lo + 1
    assert lo * lo * a <= D * D * b <= hi * hi * a
    return lo, hi


def zlabel(n2000: int) -> str:
    return f"z{n2000 * 1000 // 2000:04d}"


def lean_table(name: str, p: int, q: int, S: int, only_check: bool) -> dict[str, object]:
    assert S % 2000 == 0
    f = S // 2000
    nmax = Z2000[-1] * f
    tbl = [node(p, q, S, i) for i in range(nmax + 1)]
    out = ["import BAOCert.Likelihood", "",
           f"/-! Generated by scripts/certified_numerics/emit_p2.py (untrusted): Om = {p}/{q}, S = {S}, D = 10^12. -/", "",
           f"namespace BAOCert.P2.T_{name}", "open BAOCert", ""]
    chunks = [tbl[k:k + CHUNK] for k in range(0, len(tbl), CHUNK)]
    for j, ch in enumerate(chunks):
        out.append(f"def c{j} : List (ℕ × ℕ) := [" + ", ".join(f"({lo}, {hi})" for lo, hi in ch) + "]")
    groups = [list(range(k, min(k + GROUP, len(chunks)))) for k in range(0, len(chunks), GROUP)]
    for g, idx in enumerate(groups):
        out.append(f"def g{g} : List (ℕ × ℕ) := " + " ++ ".join(f"c{j}" for j in idx))
    out += ["", "def tbl : List (ℕ × ℕ) := " + " ++ ".join(f"g{g}" for g in range(len(groups))), "",
            f"theorem tbl_check : checkFrom {p} {q} {S} {D} 0 tbl = true := by decide +kernel", ""]
    rep: dict[str, object] = {"name": name, "p": p, "q": q, "S": S, "nodes": len(tbl), "z": {}}
    if not only_check:
        DS = D * S
        Om = f"((({p} : ℕ) : ℝ) / (({q} : ℕ) : ℝ))"
        for n2 in Z2000:
            n = n2 * f
            lab = zlabel(n2)
            sub = tbl[: n + 1]
            L = sum(lo for lo, _ in sub[1:])
            U = sum(hi for _, hi in sub[:-1])
            lo_n, hi_n = tbl[n]
            zc = f"((({n2} : ℕ) : ℝ) / ((2000 : ℕ) : ℝ))"
            zs = f"((({n} : ℕ) : ℝ) / (({S} : ℕ) : ℝ))"
            rw = [] if f == 1 else [f"  have hz : {zs} = {zc} := by norm_num", "  rw [hz] at h"]
            out += [
                f"theorem chi_{lab} : (⟨({L} : ℚ) / ({DS} : ℚ), ({U} : ℚ) / ({DS} : ℚ)⟩ : Iv).mem (chi {Om} {zc}) := by",
                f"  have h := chi_bounds (p := {p}) (q := {q}) (S := {S}) (D := {D}) (n := {n}) (by norm_num) (by norm_num) (by norm_num) (by norm_num)",
                f"    (tbl.take {n + 1}) (by decide +kernel) (checkFrom_take {p} {q} {S} {D} tbl 0 {n + 1} tbl_check)",
                f"  have hl : lowerSum (tbl.take {n + 1}) = {L} := by decide +kernel",
                f"  have hu : upperSum (tbl.take {n + 1}) = {U} := by decide +kernel",
                "  rw [hl, hu] at h", *rw,
                f"  have e1 : ((({L} : ℚ) / ({DS} : ℚ) : ℚ) : ℝ) = ((({L} : ℕ) : ℝ) / ((({D} : ℕ) : ℝ) * (({S} : ℕ) : ℝ))) := by norm_num",
                f"  have e2 : ((({U} : ℚ) / ({DS} : ℚ) : ℚ) : ℝ) = ((({U} : ℕ) : ℝ) / ((({D} : ℕ) : ℝ) * (({S} : ℕ) : ℝ))) := by norm_num",
                "  exact ⟨by rw [e1]; exact h.1, by rw [e2]; exact h.2⟩", "",
                f"theorem invE_{lab} : (⟨({lo_n} : ℚ) / ({D} : ℚ), ({hi_n} : ℚ) / ({D} : ℚ)⟩ : Iv).mem (invE {Om} {zc}) := by",
                f"  have h := node_bounds (p := {p}) (q := {q}) (S := {S}) (D := {D}) (i := {n}) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by decide +kernel : nodeOK {p} {q} {S} {D} {n} {lo_n} {hi_n} = true)",
                *rw,
                f"  have e1 : ((({lo_n} : ℚ) / ({D} : ℚ) : ℚ) : ℝ) = ((({lo_n} : ℕ) : ℝ) / (({D} : ℕ) : ℝ)) := by norm_num",
                f"  have e2 : ((({hi_n} : ℚ) / ({D} : ℚ) : ℚ) : ℝ) = ((({hi_n} : ℕ) : ℝ) / (({D} : ℕ) : ℝ)) := by norm_num",
                "  exact ⟨by rw [e1]; exact h.1, by rw [e2]; exact h.2⟩", ""]
            rep["z"][lab] = {"n2000": n2, "chi": [f"{L}/{DS}", f"{U}/{DS}"], "invE": [f"{lo_n}/{D}", f"{hi_n}/{D}"]}
        # D_V row (z = 0.295): w = cbrt(z chi^2 invE)
        lab = zlabel(Z2000[0])
        cl, ch = (Fraction(s.split("/")[0]) / Fraction(s.split("/")[1]) for s in rep["z"][lab]["chi"])
        il, ih = (Fraction(s.split("/")[0]) / Fraction(s.split("/")[1]) for s in rep["z"][lab]["invE"])
        z = Fraction(Z2000[0], 2000)
        Xlo, Xhi = z * cl * cl * il, z * ch * ch * ih
        wl = icbrt_floor(Xlo, WD)
        wh = icbrt_ceil(Xhi, WD)
        assert Fraction(wl, WD) ** 3 <= Xlo and Fraction(wh, WD) ** 3 >= Xhi
        Om = f"((({p} : ℕ) : ℝ) / (({q} : ℕ) : ℝ))"
        zc = f"((({Z2000[0]} : ℕ) : ℝ) / ((2000 : ℕ) : ℝ))"
        c_lo, c_hi = rep["z"][lab]["chi"]
        i_lo, i_hi = rep["z"][lab]["invE"]
        out += [
            f"theorem wV_{lab} : (⟨({wl} : ℚ) / ({WD} : ℚ), ({wh} : ℚ) / ({WD} : ℚ)⟩ : Iv).mem (wV {Om} {zc}) := by",
            f"  have hc := chi_{lab}",
            f"  have hi := invE_{lab}",
            "  unfold Iv.mem at hc hi ⊢",
            f"  have hlo : ((({wl} : ℚ) / ({WD} : ℚ) : ℚ) : ℝ) ^ 3 ≤ {zc} * ((({c_lo.split('/')[0]} : ℚ) / ({c_lo.split('/')[1]} : ℚ) : ℚ) : ℝ) ^ 2 * ((({i_lo.split('/')[0]} : ℚ) / ({i_lo.split('/')[1]} : ℚ) : ℚ) : ℝ) := by",
            f"    have hq : (({wl} : ℚ) / ({WD} : ℚ)) ^ 3 ≤ (({Z2000[0]} : ℚ) / 2000) * (({c_lo.split('/')[0]} : ℚ) / ({c_lo.split('/')[1]} : ℚ)) ^ 2 * (({i_lo.split('/')[0]} : ℚ) / ({i_lo.split('/')[1]} : ℚ)) := by decide +kernel",
            "    have h2 := (Rat.cast_le (K := ℝ)).2 hq",
            "    simp only [Rat.cast_mul, Rat.cast_pow] at h2",
            f"    have hz : ((((({Z2000[0]} : ℚ) / 2000) : ℚ)) : ℝ) = {zc} := by norm_num",
            "    rw [hz] at h2",
            "    exact h2",
            f"  have hhi : {zc} * ((({c_hi.split('/')[0]} : ℚ) / ({c_hi.split('/')[1]} : ℚ) : ℚ) : ℝ) ^ 2 * ((({i_hi.split('/')[0]} : ℚ) / ({i_hi.split('/')[1]} : ℚ) : ℚ) : ℝ) ≤ ((({wh} : ℚ) / ({WD} : ℚ) : ℚ) : ℝ) ^ 3 := by",
            f"    have hq : (({Z2000[0]} : ℚ) / 2000) * (({c_hi.split('/')[0]} : ℚ) / ({c_hi.split('/')[1]} : ℚ)) ^ 2 * (({i_hi.split('/')[0]} : ℚ) / ({i_hi.split('/')[1]} : ℚ)) ≤ (({wh} : ℚ) / ({WD} : ℚ)) ^ 3 := by decide +kernel",
            "    have h2 := (Rat.cast_le (K := ℝ)).2 hq",
            "    simp only [Rat.cast_mul, Rat.cast_pow] at h2",
            f"    have hz : ((((({Z2000[0]} : ℚ) / 2000) : ℚ)) : ℝ) = {zc} := by norm_num",
            "    rw [hz] at h2",
            "    exact h2",
            "  exact wV_bounds (by positivity) (by rw [div_le_one (by positivity)]; norm_num) (by positivity) (by positivity) (by positivity)",
            "    (by positivity) (by positivity) hc hi hlo hhi", ""]
        rep["wV"] = [f"{wl}/{WD}", f"{wh}/{WD}"]
    out.append(f"end BAOCert.P2.T_{name}")
    LEAN_DIR.mkdir(parents=True, exist_ok=True)
    (LEAN_DIR / f"T_{name}.lean").write_text("\n".join(out) + "\n", encoding="utf-8")
    RES.mkdir(parents=True, exist_ok=True)
    if not only_check:
        (RES / f"table_{name}.json").write_text(json.dumps(rep, indent=1) + "\n")
    return rep


def icbrt_floor(X: Fraction, den: int) -> int:
    """largest w with (w/den)^3 <= X."""
    lo, hi = 0, den * 10
    while lo < hi:
        mid = (lo + hi + 1) // 2
        if Fraction(mid, den) ** 3 <= X:
            lo = mid
        else:
            hi = mid - 1
    return lo


def icbrt_ceil(X: Fraction, den: int) -> int:
    w = icbrt_floor(X, den)
    return w if Fraction(w, den) ** 3 >= X else w + 1


def main() -> int:
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)
    t = sub.add_parser("table")
    t.add_argument("--name", required=True)
    t.add_argument("--p", type=int, required=True)
    t.add_argument("--q", type=int, required=True)
    t.add_argument("--S", type=int, default=2000)
    t.add_argument("--only-check", action="store_true")
    args = ap.parse_args()
    if args.cmd == "table":
        rep = lean_table(args.name, args.p, args.q, args.S, args.only_check)
        print(json.dumps({"name": rep["name"], "nodes": rep["nodes"], "file": f"formal_cert/BAOCert/P2/T_{args.name}.lean",
                          "bytes": (LEAN_DIR / f"T_{args.name}.lean").stat().st_size}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
