#!/usr/bin/env python3
"""Untrusted emitter for P3 (certified Hubble tension, DESI DR2 BAO + BBN, flat LCDM, radiation off).

  point      BAOCert.P3.Point: kernel-checked upper bound U_tot of chi2_total at (Om*, h*, omega_b*) = (0.29743, h*, mu)
  boxes      BAOCert.P3.Box_<i>: for all Om in [a,b], omega_b in [c,d], h >= 0.73: chi2_total >= L_i + priorMin
  assemble   BAOCert.P3.Main: the full exclusion statement from the box, slab and outside-omega_b theorems
"""

from __future__ import annotations

import json
import math
import sys
from fractions import Fraction
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import emit_p2_cases as E  # noqa: E402

REPO = Path(__file__).resolve().parents[2]
LEAN = REPO / "formal_cert" / "BAOCert" / "P3"
RES = REPO / "results" / "certified_numerics" / "P3_h0"
NU = 0.0107 * 0.06
MU = Fraction(2218, 100000)
KFIT = Fraction(299792458, 10154300)
OMSTAR = (29743, 100000)


def rd_float(wcb: float, wb: float) -> float:
    return 55.154 * math.exp(-72.3 * (NU + 0.0006) ** 2) / (wcb**0.25351 * wb**0.12807)


def K_float(h: float, om: float, wb: float) -> float:
    return 299792.458 / (100 * h * rd_float(om * h * h - NU, wb))


def kexp(x: Fraction) -> int:
    """smallest k >= 0 with x 2^k in [1/2, 1]."""
    k = 0
    while x * 2**k < Fraction(1, 2):
        k += 1
    assert x * 2**k <= 1
    return k


def q(x: Fraction) -> str:
    return f"({x.numerator} / {x.denominator} : ℚ)" if x.denominator != 1 else f"({x.numerator} : ℚ)"


def write_point() -> dict:
    om = OMSTAR[0] / OMSTAR[1]
    lo, hi = 0.5, 0.9
    for _ in range(200):
        mid = (lo + hi) / 2
        if K_float(mid, om, float(MU)) > float(KFIT):
            lo = mid
        else:
            hi = mid
    hq = Fraction(round((lo + hi) / 2 * 10**10), 10**10)
    wcb = Fraction(*OMSTAR) * hq**2 - Fraction(107, 10000) * Fraction(6, 100)
    k1, k2 = kexp(wcb), kexp(MU)
    tm = Fraction(1, 10**7)
    d, P = E.load_PD("Data")
    T = E.tables()["FitFine"]
    env = [E.iv_from(T, kind, n) for kind, n in E.ROWS]
    C = E.c_iv(P, d, KFIT, env)
    B = E.b_iv(P, d, KFIT, env)
    A = E.a_iv(P, env)
    Bm = max(abs(B[0]), abs(B[1]))
    U = E.round_up(C[1] + tm * Bm + tm * tm * A[1], 4)
    Om = f"((({OMSTAR[0]} : ℕ) : ℝ) / (({OMSTAR[1]} : ℕ) : ℝ))"
    rdI = f"(rdIv {q(wcb)} {q(MU)} {k1} {k2} 60 25)"
    lines = ["import BAOCert.H0.Lemmas", "import BAOCert.P2.T_FitFine", "import BAOCert.P2.Data", "",
             "/-! Generated by scripts/certified_numerics/emit_p3.py (untrusted). H9: kernel-checked upper bound of the",
             "BAO+BBN chi^2 at a point, hence of its global minimum. -/", "",
             "namespace BAOCert.P3.Point", "open BAOCert BAOCert.H0 BAOCert.P2 ANSE.BAOBBNH0", "",
             "def envs : List Iv := [" + ", ".join(E.iv_lean(I) for I in env) + "]", "",
             f"/-- χ²_total(Om = 0.29743, h = {float(hq)}, ω_b = 0.02218) ≤ {float(U)}. -/",
             f"theorem chi2tot_point : chi2tot {Om} (({q(hq)}) : ℝ) (({q(MU)}) : ℝ) ≤ ({q(U)} : ℝ) := by",
             *E.mem_lines_point("FitFine"),
             f"  have henv := env_ok envs (Data.xsOf ({Om})) {E.forall2(13)}",
             f"  have hcb : omegaCb (({q(hq)}) : ℝ) {Om} = (({q(wcb)}) : ℝ) := by unfold omegaCb omegaNu; push_cast; norm_num",
             f"  have hrd := rdIv_mem {q(wcb)} {q(MU)} {k1} {k2} 60 25 (by decide +kernel)",
             "  rw [← hcb] at hrd",
             f"  have hc : (299792.458 : ℝ) = ((299792458 / 1000 : ℚ) : ℝ) := by norm_num",
             f"  have hlo : (({q(KFIT)}) : ℝ) - (({q(tm)}) : ℝ) ≤ 299792.458 / (100 * ((({q(hq)}) : ℝ) * (({rdI}.hi : ℚ) : ℝ))) := by",
             f"    have hq0 : {q(KFIT)} - {q(tm)} ≤ (299792458 / 1000 : ℚ) / (100 * ({q(hq)} * {rdI}.hi)) := by decide +kernel",
             "    have := (Rat.cast_le (K := ℝ)).2 hq0",
             "    rw [hc]; push_cast at this ⊢; exact this",
             f"  have hhi : 299792.458 / (100 * ((({q(hq)}) : ℝ) * (({rdI}.lo : ℚ) : ℝ))) ≤ (({q(KFIT)}) : ℝ) + (({q(tm)}) : ℝ) := by",
             f"    have hq0 : (299792458 / 1000 : ℚ) / (100 * ({q(hq)} * {rdI}.lo)) ≤ {q(KFIT)} + {q(tm)} := by decide +kernel",
             "    have := (Rat.cast_le (K := ℝ)).2 hq0",
             "    rw [hc]; push_cast at this ⊢; exact this",
             f"  have hrlo : (0 : ℝ) < (({rdI}.lo : ℚ) : ℝ) := by",
             f"    have : (0 : ℚ) < {rdI}.lo := by decide +kernel",
             "    exact_mod_cast this",
             f"  have hK := Kof_near {rdI}.lo {rdI}.hi {q(KFIT)} {q(tm)} (by norm_num) hrd hrlo hlo hhi",
             f"  have hchi := chi2_upper_Kin Data.Pent Data.dR {q(KFIT)} _ _ henv {q(U)} {q(tm)} (by norm_num) (by decide +kernel) (by decide +kernel) _ hK",
             "  unfold chi2tot",
             f"  have hp : (((({q(MU)}) : ℝ) - 0.02218) / 0.00055) ^ 2 = 0 := by norm_num",
             "  rw [hp, add_zero]",
             "  exact hchi", "",
             "end BAOCert.P3.Point"]
    LEAN.mkdir(parents=True, exist_ok=True)
    (LEAN / "Point.lean").write_text("\n".join(lines) + "\n", encoding="utf-8")
    rep = {"Om": "29743/100000", "h": str(hq), "h_float": float(hq), "omega_b": str(MU), "U_tot": str(U), "U_tot_float": float(U),
           "K_float_at_point": K_float(float(hq), om, float(MU)), "K0": str(KFIT), "tm": str(tm), "k1": k1, "k2": k2}
    RES.mkdir(parents=True, exist_ok=True)
    (RES / "point.json").write_text(json.dumps(rep, indent=1) + "\n")
    print(json.dumps(rep))
    return rep


def write_boxes() -> list[dict]:
    plan = json.loads((RES / "plan.json").read_text())
    elist = json.loads((REPO / "scripts/certified_numerics/p2_edges.json").read_text())["edges"]
    edges = {Fraction(p, q_): n for n, p, q_ in elist}
    raw = {n: (p, q_) for n, p, q_ in elist}
    for f in E.RES.glob("table_R*.json"):
        t = json.loads(f.read_text())
        edges.setdefault(Fraction(t["p"], t["q"]), t["name"])
        raw.setdefault(t["name"], (t["p"], t["q"]))
    d, P = E.load_PD("Data")
    T = E.tables()
    nu = Fraction(107, 10000) * Fraction(6, 100)
    out = []
    for i, leaf in enumerate(plan["leaves"]):
        assert leaf["pass"], leaf
        a, b = Fraction(leaf["Om"][0]), Fraction(leaf["Om"][1])
        c, dd = Fraction(leaf["wb"][0]), Fraction(leaf["wb"][1])
        K0 = Fraction(leaf["K0"])
        ta, tb = edges[a], edges[b]
        env = [(E.iv_from(T[tb], kind, n)[0], E.iv_from(T[ta], kind, n)[1]) for kind, n in E.ROWS]
        Cc = E.c_iv(P, d, K0, env)
        L = E.round_down(Cc[0], 2)
        wcb = Fraction(*raw[tb]) * Fraction(73, 100) ** 2 - nu
        k1, k2 = kexp(wcb), kexp(dd)
        ar = f"((({raw[ta][0]} : ℕ) : ℝ) / (({raw[ta][1]} : ℕ) : ℝ))"
        br = f"((({raw[tb][0]} : ℕ) : ℝ) / (({raw[tb][1]} : ℕ) : ℝ))"
        rdI = f"(rdIv {q(wcb)} {q(dd)} {k1} {k2} 60 25)"
        name = f"Box_{i:03d}"
        lines = [f"import BAOCert.P2.T_{ta}", f"import BAOCert.P2.T_{tb}", "import BAOCert.H0.Lemmas", "import BAOCert.P2.Data", "",
                 f"/-! Generated by scripts/certified_numerics/emit_p3.py (untrusted): Om in [{a}, {b}], ω_b in [{c}, {dd}], h ≥ 0.73. -/", "",
                 f"namespace BAOCert.P3.{name}", "open BAOCert BAOCert.H0 BAOCert.P2 ANSE.BAOBBNH0", "",
                 "def envs : List Iv := [" + ", ".join(E.iv_lean(I) for I in env) + "]", "",
                 f"theorem box : ∀ Om : ℝ, {ar} ≤ Om → Om ≤ {br} → ∀ wb : ℝ, (({q(c)}) : ℝ) ≤ wb → wb ≤ (({q(dd)}) : ℝ) →",
                 f"    ∀ h : ℝ, 73 / 100 ≤ h → (({q(L)}) : ℝ) + ((priorMin {q(c)} {q(dd)} : ℚ) : ℝ) ≤ chi2tot Om h wb := by",
                 "  intro Om hOa hOb wb hwc hwd h hh",
                 f"  have ha0 : (0 : ℝ) < {ar} := by norm_num",
                 f"  have hb1 : {br} ≤ 1 := by norm_num",
                 "  have hO0 : 0 ≤ Om := ha0.le.trans hOa",
                 "  have hO1 : Om ≤ 1 := hOb.trans hb1"]
        for j, (kind, n) in enumerate(E.ROWS):
            th = {"w": f"wV_{E.ZLAB[n]}", "chi": f"chi_{E.ZLAB[n]}", "invE": f"invE_{E.ZLAB[n]}"}[kind]
            anti = {"w": "wV_anti_Om", "chi": "chi_anti_Om", "invE": "invE_anti_Om"}[kind]
            z = f"((({n} : ℕ) : ℝ) / ((2000 : ℕ) : ℝ))"
            lines += [f"  have hz{j} : (0 : ℝ) ≤ {z} := by positivity",
                      f"  have h{j} : ({E.iv_lean(env[j])} : Iv).mem _ :=",
                      f"    ⟨(BAOCert.P2.T_{tb}.{th}).1.trans ({anti} hO0 hOb hb1 hz{j}),",
                      f"     ({anti} ha0.le hOa hO1 hz{j}).trans (BAOCert.P2.T_{ta}.{th}).2⟩"]
        lines += [f"  have henv := env_ok envs (Data.xsOf Om) {E.forall2(13)}",
                  f"  have hcb : omegaCb (73 / 100) {br} = (({q(wcb)}) : ℝ) := by unfold omegaCb omegaNu; push_cast; norm_num",
                  f"  have hrd := (rdIv_mem {q(wcb)} {q(dd)} {k1} {k2} 60 25 (by decide +kernel)).1",
                  "  rw [← hcb] at hrd",
                  f"  have hrlo : (0 : ℝ) < (({rdI}.lo : ℚ) : ℝ) := by",
                  f"    have : (0 : ℚ) < {rdI}.lo := by decide +kernel",
                  "    exact_mod_cast this",
                  "  have hc : (299792.458 : ℝ) = ((299792458 / 1000 : ℚ) : ℝ) := by norm_num",
                  f"  have hKq : (299792.458 : ℝ) / (100 * ((73 / 100) * (({rdI}.lo : ℚ) : ℝ))) ≤ (({q(K0)}) : ℝ) := by",
                  f"    have hq0 : (299792458 / 1000 : ℚ) / (100 * ((73 / 100) * {rdI}.lo)) ≤ {q(K0)} := by decide +kernel",
                  "    have := (Rat.cast_le (K := ℝ)).2 hq0",
                  "    rw [hc]; push_cast at this ⊢; exact this",
                  f"  have hdom : omegaNu ≤ (1 - 2 * 0.25351) * ({ar} * (73 / 100) ^ 2) := by unfold omegaNu; norm_num",
                  f"  have hK := K_le {rdI}.lo {q(K0)} ha0 (by norm_num) hOa hOb hwc hwd hh hdom hrd hrlo hKq",
                  f"  have hchi := chi2_lower_Kle Data.Pent Data.dR {q(K0)} _ _ henv {q(L)} (by decide +kernel) (by decide +kernel) (by decide +kernel) _ hK",
                  f"  have hpr := prior_ge (c := {q(c)}) (d := {q(dd)}) hwc hwd",
                  "  unfold chi2tot",
                  "  exact add_le_add hchi hpr", "",
                  f"end BAOCert.P3.{name}"]
        (LEAN / f"{name}.lean").write_text("\n".join(lines) + "\n", encoding="utf-8")
        out.append({"name": name, "Om": [str(a), str(b)], "Om_raw": [list(raw[ta]), list(raw[tb])], "tables": [ta, tb],
                    "wb": [str(c), str(dd)], "K0": str(K0), "L": str(L), "prior_min": leaf["prior_min"]})
    (RES / "boxes.json").write_text(json.dumps(out, indent=1) + "\n")
    print(len(out), "box files")
    return out


def write_assemble() -> None:
    U = Fraction(json.loads((RES / "point.json").read_text())["U_tot"])
    T = U + 25
    boxes = json.loads((RES / "boxes.json").read_text())
    leafmap = {(Fraction(b["Om"][0]), Fraction(b["Om"][1]), Fraction(b["wb"][0]), Fraction(b["wb"][1])): b for b in boxes}
    rawname = {}
    for b in boxes:
        for x, r in zip(b["Om"], b["Om_raw"]):
            rawname[Fraction(x)] = tuple(r)
    ref = json.loads((E.RES / "refine_plan.json").read_text())["leaves"]
    exc = sorted([l for l in ref if l["excluded"]], key=lambda l: Fraction(l["a"]))
    for l in exc:
        assert Fraction(l["L"]) > T, (l["name"], l["L"], T)
    lower = [l for l in exc if Fraction(l["b"]) <= Fraction(51, 200)]
    upper = [l for l in exc if Fraction(l["a"]) >= Fraction(35, 100)]
    assert Fraction(lower[0]["a"]) == 0 and Fraction(lower[-1]["b"]) == Fraction(51, 200)
    assert Fraction(upper[0]["a"]) == Fraction(35, 100) and Fraction(upper[-1]["b"]) == 1
    for chain in (lower, upper):
        for x, y in zip(chain, chain[1:]):
            assert Fraction(x["b"]) == Fraction(y["a"]), (x["name"], y["name"])
    SIG = Fraction(55, 100000)

    def omr(s: str) -> str:
        n, d = s.split("/") if "/" in s else (s, "1")
        return f"((({n} : ℕ) : ℝ) / (({d} : ℕ) : ℝ))"

    lines: list[str] = []

    def emit(s: str, ind: int) -> None:
        lines.append("  " * ind + s)

    def band(a, b, c, d, hOa, hOb, hwc, hwd, ind):
        key = (a, b, c, d)
        if key in leafmap:
            bx = leafmap[key]
            emit(f"exact gt_of_box (BAOCert.P3.{bx['name']}.box Om {hOa} {hOb} wb {hwc} {hwd} h hh) (by decide +kernel)", ind)
            return
        om_rel, wb_rel = (b - a) / Fraction(1, 100), (d - c) / SIG
        if om_rel >= wb_rel and b - a > Fraction(1, 800):
            m = (a + b) / 2
            mr = rawname[m]
            emit(f"rcases le_or_gt Om ((({mr[0]} : ℕ) : ℝ) / (({mr[1]} : ℕ) : ℝ)) with hO{ind} | hO{ind}", ind)
            emit("·", ind)
            band(a, m, c, d, hOa, f"hO{ind}", hwc, hwd, ind + 1)
            emit("·", ind)
            band(m, b, c, d, f"hO{ind}.le", hOb, hwc, hwd, ind + 1)
        else:
            m = (c + d) / 2
            emit(f"rcases le_or_gt wb (({q(m)}) : ℝ) with hW{ind} | hW{ind}", ind)
            emit("·", ind)
            band(a, b, c, m, hOa, hOb, hwc, f"hW{ind}", ind + 1)
            emit("·", ind)
            band(a, b, m, d, hOa, hOb, f"hW{ind}.le", hwd, ind + 1)

    def chain(slabs, hlo, ind):
        # hlo : a_0 ≤ Om ; walk slabs left to right
        cur = hlo
        for i, s in enumerate(slabs):
            last = i == len(slabs) - 1
            if last:
                emit(f"exact gt_of_slab (BAOCert.P2.{s['name']}.chi2_slab Om {cur} hOb1 _) (by decide +kernel)", ind)
            else:
                emit(f"rcases le_or_gt Om {omr(s['b'])} with hS{i} | hS{i}", ind)
                emit(f"· exact gt_of_slab (BAOCert.P2.{s['name']}.chi2_slab Om {cur} hS{i} _) (by decide +kernel)", ind)
                cur = f"hS{i}.le"

    imports = sorted({f"import BAOCert.P3.{b['name']}" for b in boxes} | {f"import BAOCert.P2.{l['name']}" for l in lower + upper})
    head = [*imports, "import BAOCert.P3.Glue", "import BAOCert.P3.Point", "",
            "/-! Generated by scripts/certified_numerics/emit_p3.py (untrusted): assembly of the certified H0 ≥ 73 exclusion. -/", "",
            "namespace BAOCert.P3", "open BAOCert BAOCert.H0", "",
            "/-- **Certified Hubble tension (DESI DR2 BAO + BBN, flat ΛCDM, radiation off, Aubourg r_d).**",
            f"For every `Om ∈ [0, 1]`, every `ω_b` and every `h ≥ 0.73`, `χ²_total > {float(U)} + 25`. -/",
            f"theorem H0_ge_73_excluded : ∀ Om h wb : ℝ, 0 ≤ Om → Om ≤ 1 → 73 / 100 ≤ h → ((({q(T)}) : ℚ) : ℝ) < chi2tot Om h wb := by",
            "  intro Om h wb hO0 hO1 hh",
            "  rcases lt_or_ge wb (1833 / 100000) with hw1 | hw1",
            "  · exact gt_of_prior (Or.inl hw1) (by norm_num)",
            "  rcases lt_or_ge (2603 / 100000) wb with hw2 | hw2",
            "  · exact gt_of_prior (Or.inr hw2) (by norm_num)",
            f"  have hwc : (({q(Fraction(1833, 100000))}) : ℝ) ≤ wb := by push_cast; linarith",
            f"  have hwd : wb ≤ (({q(Fraction(2603, 100000))}) : ℝ) := by push_cast; linarith",
            f"  have hOa0 : {omr(lower[0]['a'])} ≤ Om := by norm_num; exact hO0",
            f"  have hOb1 : Om ≤ {omr(upper[-1]['b'])} := by norm_num; exact hO1",
            f"  rcases le_or_gt Om {omr(lower[-1]['b'])} with hL | hL"]
    lines.extend(head)
    emit("·", 1)
    # lower chain ending at 51/200 uses hL as the last upper bound
    lowc = lower
    cur = "hOa0"
    for i, s in enumerate(lowc):
        last = i == len(lowc) - 1
        if last:
            emit(f"exact gt_of_slab (BAOCert.P2.{s['name']}.chi2_slab Om {cur} hL _) (by decide +kernel)", 2)
        else:
            emit(f"rcases le_or_gt Om {omr(s['b'])} with hS{i} | hS{i}", 2)
            emit(f"· exact gt_of_slab (BAOCert.P2.{s['name']}.chi2_slab Om {cur} hS{i} _) (by decide +kernel)", 2)
            cur = f"hS{i}.le"
    emit("·", 1)
    emit(f"rcases le_or_gt Om {omr(upper[0]['a'])} with hU | hU", 2)
    emit("·", 2)
    band(Fraction(51, 200), Fraction(35, 100), Fraction(1833, 100000), Fraction(2603, 100000), "hL.le", "hU", "hwc", "hwd", 3)
    emit("·", 2)
    chain(upper, "hU.le", 3)
    lines.append("")
    lines += [f"/-- Corollary: every H0 ≥ 73 point is more than Δχ² = 25 above an allowed point (h = {float(Fraction(json.loads((RES / 'point.json').read_text())['h'])):.6f}). -/",
              "theorem H0_ge_73_delta_chi2 : ∀ Om h wb : ℝ, 0 ≤ Om → Om ≤ 1 → 73 / 100 ≤ h →",
              "    chi2tot ((29743 : ℕ) / (100000 : ℕ) : ℝ) ((" + q(Fraction(json.loads((RES / 'point.json').read_text())['h'])) + ") : ℝ) (((1109 / 50000 : ℚ)) : ℝ) + 25 < chi2tot Om h wb := by",
              "  intro Om h wb hO0 hO1 hh",
              "  have hp := BAOCert.P3.Point.chi2tot_point",
              "  have hx := H0_ge_73_excluded Om h wb hO0 hO1 hh",
              "  push_cast at hp hx ⊢",
              "  linarith", "", "end BAOCert.P3"]
    (LEAN / "Main.lean").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("Main.lean", len(lines), "lines;", len(boxes), "boxes;", len(lower), "+", len(upper), "slabs; threshold", float(T))


def main() -> int:
    cmd = sys.argv[1]
    if cmd == "assemble":
        write_assemble()
    if cmd == "point":
        write_point()
    elif cmd == "boxes":
        write_boxes()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
