#!/usr/bin/env python3
"""Evaluate pilot P2 against its preregistration (results/certified_numerics/P2_likelihood/preregistration.json, A1, A2).

Only statements whose Lean module compiled with rc 0 and whose theorem appears in the axiom audit with whitelisted
axioms count as certified. Untrusted references: rusty-SUNDIALS (README value and MCP server) and the MCP profile.
Also writes formal_cert/BAOCert/P2/Axioms.lean (audit of every P2 theorem + planted controls) when called with --axioms-file.
"""

from __future__ import annotations

import json
import sys
from fractions import Fraction
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
RES = REPO / "results" / "certified_numerics" / "P2_likelihood"
LEAN = REPO / "formal_cert" / "BAOCert" / "P2"
ALLOWED = {"propext", "Classical.choice", "Quot.sound"}


def compiled(mod: str) -> bool:
    f = RES / f"compile_{mod}.json"
    return f.exists() and json.loads(f.read_text())["rc"] == 0


def case_modules() -> list[str]:
    slabs = [s["name"] for s in json.loads((RES / "slabs_plan.json").read_text()) if s["A_lo_positive"]]
    ref = [s["name"] for s in json.loads((RES / "refine_plan.json").read_text())["leaves"] if s["excluded"]]
    return list(dict.fromkeys(["Fit", "Fit_Tamper", *slabs, *ref]))


def write_axioms_file() -> None:
    mods = [m for m in case_modules() if compiled(m)]
    lines = [f"import BAOCert.P2.{m}" for m in mods] + ["import BAOCert.P2.Data", "", "/-! Generated by evaluate_p2.py: axiom audit of every P2 case theorem, the data check and the generic layer, plus planted controls. -/", ""]
    lines += ["#print axioms BAOCert.P2.Data.P_is_inverse", "#print axioms BAOCert.Ex.ieval_sound", "#print axioms BAOCert.chi2_lower_of_env",
              "#print axioms BAOCert.chi2_mem_at_K0", "#print axioms BAOCert.profile_lower", "#print axioms BAOCert.wV_anti_Om", "#print axioms BAOCert.chi_anti_Om"]
    for m in mods:
        th = "chi2_fit" if m.startswith("Fit") else "chi2_slab"
        lines.append(f"#print axioms BAOCert.P2.{m}.{th}")
    lines += ["", "theorem ctl_sorry : BAOCert.P2.Data.chi2DESI 1 1 = 0 := by sorry", "axiom ctl_cheat : False",
              "theorem ctl_axiom : BAOCert.P2.Data.chi2DESI 1 1 = 0 := ctl_cheat.elim", "#print axioms ctl_sorry", "#print axioms ctl_axiom", ""]
    (LEAN / "Axioms.lean").write_text("\n".join(lines))
    print(f"Axioms.lean: {len(mods)} case modules")


def axioms() -> dict[str, list[str]]:
    f = RES / "compile_Axioms.json"
    if not f.exists():
        return {}
    out = json.loads(f.read_text())["output"]
    return {l.split("'")[1]: [a.strip() for a in l.split("[")[1].rstrip("]").split(",")] for l in out.splitlines() if "depends on axioms" in l}


def main() -> int:
    if "--axioms-file" in sys.argv:
        write_axioms_file()
        return 0
    ax = axioms()
    ok_ax = lambda name: name in ax and set(ax[name]) <= ALLOWED
    out: dict[str, object] = {"pilot": "P2"}
    fit = json.loads((RES / "case_Fit.json").read_text())
    lo, hi = Fraction(fit["stated"][0]), Fraction(fit["stated"][1])
    mcp = json.loads((RES / "mcp_profile.json").read_text())
    h6_cert = compiled("Fit") and ok_ax("BAOCert.P2.Fit.chi2_fit")
    out["H6"] = {"certified": h6_cert, "interval": [float(lo), float(hi)], "width": float(hi - lo),
                 "contains_rust_readme_10.2710": lo <= Fraction("10.2710") <= hi,
                 "contains_mcp_fit_value": lo <= Fraction(mcp["chi2_fit_point"]) <= hi, "mcp_fit_value": mcp["chi2_fit_point"]}
    out["H6"]["pass"] = bool(h6_cert and out["H6"]["contains_rust_readme_10.2710"])
    eds = next(s for s in json.loads((RES / "slabs_plan.json").read_text()) if s["name"] == "EdS")
    h7_cert = compiled("EdS") and ok_ax("BAOCert.P2.EdS.chi2_slab")
    out["H7"] = {"certified": h7_cert, "bound": eds["L_float"], "pass": bool(h7_cert and Fraction(eds["L"]) >= 1000)}
    T = hi + 25
    pre = []
    for s in json.loads((RES / "slabs_plan.json").read_text()):
        if s["name"] == "EdS":
            continue
        cert = s["A_lo_positive"] and compiled(s["name"]) and ok_ax(f"BAOCert.P2.{s['name']}.chi2_slab")
        pre.append({"slab": [s["a"], s["b"]], "L": s["L_float"], "certified": bool(cert), "excluded": bool(cert and Fraction(s["L"]) > T)})
    control = next(p for p in pre if [Fraction(x) for x in p["slab"]] == [Fraction(29, 100), Fraction(3, 10)])
    prereg_slabs = [p for p in pre if p is not control]
    pred = [p for p in prereg_slabs if Fraction(p["slab"][1]) <= Fraction("0.24") or Fraction(p["slab"][0]) >= Fraction("0.36")]
    out["H8_preregistered_layout"] = {"threshold": float(T), "slabs": prereg_slabs,
                                      "n_excluded": sum(p["excluded"] for p in prereg_slabs),
                                      "prediction_cover_[0,0.24]_and_[0.36,1]": all(p["excluded"] for p in pred), "pass": all(p["excluded"] for p in pred)}
    ref = json.loads((RES / "refine_plan.json").read_text())
    leaves = []
    for s in ref["leaves"]:
        cert = s["excluded"] and compiled(s["name"]) and ok_ax(f"BAOCert.P2.{s['name']}.chi2_slab")
        leaves.append({"slab": [s["a"], s["b"]], "L": s["L_float"], "excluded_certified": bool(cert), "planned_excluded": s["excluded"]})
    exc = [l for l in leaves if l["excluded_certified"]]
    out["A2_refined"] = {"leaves": leaves, "n_excluded_certified": len(exc),
                         "not_excluded": [l["slab"] for l in leaves if not l["excluded_certified"]]}
    out["C5_control_slab_not_excluded"] = {"slab": control["slab"], "L": control["L"], "pass": not control["excluded"]}
    tam = json.loads((RES / "case_Fit_Tamper.json").read_text())
    tl, th = Fraction(tam["stated"][0]), Fraction(tam["stated"][1])
    out["C6_tampered_data"] = {"certified": compiled("Fit_Tamper") and ok_ax("BAOCert.P2.Fit_Tamper.chi2_fit"), "interval": [float(tl), float(th)],
                               "excludes_10.2710": not (tl <= Fraction("10.2710") <= th)}
    out["C6_tampered_data"]["pass"] = bool(out["C6_tampered_data"]["certified"] and out["C6_tampered_data"]["excludes_10.2710"])
    viol = []
    allslabs = [(Fraction(p["slab"][0]), Fraction(p["slab"][1]), p["L"], p["certified"]) for p in pre] + \
               [(Fraction(l["slab"][0]), Fraction(l["slab"][1]), l["L"], l["excluded_certified"]) for l in leaves]
    for om, v in mcp["profile"].items():
        x = Fraction(om)
        for a, b, L, cert in allslabs:
            if cert and a <= x <= b and not v["at_range_edge"] and v["chi2_min"] < L:
                viol.append({"Om": om, "mcp_chi2_min": v["chi2_min"], "slab": [str(a), str(b)], "L": L})
    out["C4_mcp_profile_consistent"] = {"violations": viol, "pass": not viol and out["H6"]["contains_mcp_fit_value"],
                                        "note": "MCP profile minimises over h r_d in [50, 200] only (the tool's range); points at the range edge are skipped"}
    ctl = {k: v for k, v in ax.items() if k.startswith("ctl_")}
    out["C7_axiom_audit"] = {"n_audited": len([k for k in ax if not k.startswith("ctl_")]),
                             "all_whitelisted": all(set(v) <= ALLOWED for k, v in ax.items() if not k.startswith("ctl_")),
                             "sorry_flagged": "sorryAx" in ctl.get("ctl_sorry", []), "axiom_flagged": "ctl_cheat" in ctl.get("ctl_axiom", [])}
    out["C7_axiom_audit"]["pass"] = all(out["C7_axiom_audit"][k] for k in ("all_whitelisted", "sorry_flagged", "axiom_flagged"))
    controls_ok = all(out[k]["pass"] for k in ("C4_mcp_profile_consistent", "C5_control_slab_not_excluded", "C6_tampered_data", "C7_axiom_audit"))
    out["scope"] = ["flat LCDM, radiation off, Om in [0, 1]", "DESI DR2 BAO ALL_GCcomb Gaussian likelihood (data vector and covariance as inputs)",
                    "profiled over every real K = c/(100 h r_d), i.e. every h r_d", "Delta chi2 = 25 with 2 free parameters is about 4.6 sigma (not 5 sigma)",
                    "the preregistered slab layout (H8) failed 8/19; the A2 refinement is post hoc (disclosed in the preregistration amendments)"]
    out["verdict"] = "VOID" if not controls_ok else ("P2_OK" if all(out[k]["pass"] for k in ("H6", "H7", "H8_preregistered_layout")) else "P2_PARTIAL")
    (RES / "result.json").write_text(json.dumps(out, indent=1) + "\n")
    print(json.dumps({k: (v["pass"] if isinstance(v, dict) and "pass" in v else v) for k, v in out.items() if k != "A2_refined"}, indent=1))
    print("A2 excluded certified:", len(exc), "not excluded:", out["A2_refined"]["not_excluded"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
