#!/usr/bin/env python3
"""Write formal_cert/BAOCert/Axioms.lean: #print axioms for EVERY theorem/lemma of Core, Fit, FitOm101 and EdS,
plus the two planted negative controls (C3)."""

from __future__ import annotations

import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
D = REPO / "formal_cert" / "BAOCert"
names: list[str] = []
for mod in ("Core", "Fit", "FitOm101", "EdS"):
    text = (D / f"{mod}.lean").read_text()
    ns = "BAOCert" if mod == "Core" else f"BAOCert.{mod}"
    for m in re.finditer(r"^(?:theorem|lemma)\s+([A-Za-z0-9_'.]+)", text, re.M):
        names.append(f"{ns}.{m.group(1)}")
lines = ["import BAOCert.Fit", "import BAOCert.FitOm101", "import BAOCert.EdS", "",
         "/-! Generated by scripts/certified_numerics/make_axioms_file.py: axiom audit of every theorem of the pilot,",
         "and two planted negative controls (C3) that must show non-whitelisted axioms. -/", ""]
lines += [f"#print axioms {n}" for n in names]
lines += ["", "-- C3 negative controls", "theorem ctl_sorry : BAOCert.chi 1 1 = 0 := by sorry", "axiom ctl_cheat : False",
          "theorem ctl_axiom : BAOCert.chi 1 1 = 0 := ctl_cheat.elim", "#print axioms ctl_sorry", "#print axioms ctl_axiom", ""]
(D / "Axioms.lean").write_text("\n".join(lines))
print(len(names), "theorems")
