#!/usr/bin/env python3
"""Generate gen_numbers.tex for the dyadic triangular Hilbert paper from result files only.

Every macro is read from a JSON written by a script in the repository; nothing is typed in.
Run:  python3 papers/dyadic_triangular_hilbert/gen_numbers.py
"""

from __future__ import annotations

import hashlib
import json
import subprocess
from fractions import Fraction
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
RES = REPO / "results" / "openai_math" / "hypotheses"
TENSOR = RES / "tensor"
NIGHT = RES / "night_2026-10-07" / "H5"
OUT = Path(__file__).resolve().parent / "gen_numbers.tex"


def frac_tex(s: str) -> str:
    f = Fraction(s)
    return str(f.numerator) if f.denominator == 1 else rf"\tfrac{{{f.numerator}}}{{{f.denominator}}}"


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> int:
    rigor = json.loads((TENSOR / "rigor.json").read_text())
    powers = json.loads((TENSOR / "tensor_powers_to_r5.json").read_text())
    night = json.loads((NIGHT / "result.json").read_text())
    verify = json.loads((NIGHT / "verify_tensor.json").read_text())
    searches = {p.stem: json.loads(p.read_text()) for p in sorted(TENSOR.glob("search_*.json")) if "smoke" not in p.stem}
    seed = rigor["seeds"]["g2_lane_witness"]
    commit = subprocess.run(["git", "rev-parse", "--short=12", "HEAD"], capture_output=True, text=True, cwd=REPO).stdout.strip()

    lines = [
        "% generated by gen_numbers.py -- do not edit",
        rf"\newcommand{{\gitcommit}}{{{commit}}}",
        rf"\newcommand{{\seedR}}{{{frac_tex(seed['R'])}}}",
        rf"\newcommand{{\seedH}}{{{frac_tex(seed['H'])}}}",
        rf"\newcommand{{\seedT}}{{{frac_tex(seed['T'])}}}",
        rf"\newcommand{{\seedPhi}}{{{frac_tex(seed['phi'])}}}",
        rf"\newcommand{{\nOneCount}}{{{rigor['exhaustive_N1']['count']}}}",
        rf"\newcommand{{\nOneMaxR}}{{{frac_tex(rigor['exhaustive_N1']['max_R'])}}}",
        rf"\newcommand{{\nOneMaxPhi}}{{{frac_tex(rigor['exhaustive_N1']['max_phi'])}}}",
        rf"\newcommand{{\prodRulePairs}}{{{rigor['product_rule_pm1']['n_pairs']}}}",
        rf"\newcommand{{\prodRuleGeneralPairs}}{{{rigor['product_rule_general']['n_pairs']}}}",
        rf"\newcommand{{\prodRuleAllPass}}{{{'yes' if rigor['product_rule_pm1']['all_pass'] and rigor['product_rule_general']['all_pass'] else 'NO'}}}",
        rf"\newcommand{{\rMaxPowers}}{{{powers[-1]['r']}}}",
        rf"\newcommand{{\nMaxPowers}}{{{powers[-1]['N']}}}",
        rf"\newcommand{{\lastPowerR}}{{{frac_tex(powers[-1]['R'])}}}",
        rf"\newcommand{{\nightRatioNeight}}{{{frac_tex(night['refuting_witness']['ratio'])}}}",
        rf"\newcommand{{\nightIndependent}}{{{frac_tex(night['refuting_witness']['independent_direct_implementation'])}}}",
    ]
    # Seed matrices.
    for v, m in enumerate(seed["matrices"]):
        rows = r" \\ ".join(" & ".join(str(x) for x in row) for row in m)
        lines.append(rf"\newcommand{{\seedMat{'ABC'[v]}}}{{\begin{{pmatrix}} {rows} \end{{pmatrix}}}}")
    # Powers table rows.
    rows = []
    for p in powers:
        ok = "yes" if Fraction(p["R"]) == Fraction(p["closed_form"]) else "NO"
        rows.append(f"{p['r']} & {p['N']} & ${frac_tex(p['R'])}$ & ${frac_tex(p['H'])}$ & ${frac_tex(p['T'])}$ & ${frac_tex(p['closed_form'])}$ & {ok} \\\\")
    lines.append(r"\newcommand{\powersTableRows}{" + " ".join(rows) + "}")
    # Searches table rows.
    srows = []
    for name, s in searches.items():
        obj = r"$\Phi$" if s["mode"] == "phi" else "$R$"
        origin = "tensor + random" if any(r["origin"] == "tensor_perturbed" for r in s["runs"]) else "random"
        best_f = float(Fraction(s["best"]))
        srows.append(f"{obj} & {s['n_res']} & {s['restarts_done']} & {origin} & ${frac_tex(s['best'])}$ & {best_f:.4f} \\\\")
    lines.append(r"\newcommand{\searchTableRows}{" + " ".join(srows) + "}")
    best_phi = max((Fraction(s["best"]) for s in searches.values() if s["mode"] == "phi"), default=Fraction(0))
    best_R = max((Fraction(s["best"]) for s in searches.values() if s["mode"] == "R"), default=Fraction(0))
    lines.append(rf"\newcommand{{\searchBestPhi}}{{{frac_tex(str(best_phi))}}}")
    lines.append(rf"\newcommand{{\searchBestR}}{{{frac_tex(str(best_R))}}}")
    lines.append(rf"\newcommand{{\searchAnyAboveThree}}{{{'yes' if best_phi > 3 else 'none'}}}")
    lines.append(rf"\newcommand{{\rigorSha}}{{{sha(REPO / 'scripts' / 'openai_math' / 'hypotheses' / 'tensor' / 'h5_tensor_rigor.py')[:16]}}}")
    lines.append(rf"\newcommand{{\searchSha}}{{{sha(REPO / 'scripts' / 'openai_math' / 'hypotheses' / 'tensor' / 'phi_search.py')[:16]}}}")
    doi_file = Path(__file__).resolve().parent / "zenodo_doi.txt"
    lines.append(rf"\newcommand{{\zenodoDOI}}{{{doi_file.read_text().strip() if doi_file.exists() else 'pending'}}}")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(lines)} macros); best phi {best_phi}, best R {best_R}, powers to r={powers[-1]['r']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
