

# This file was *autogenerated* from the file scripts/hardness/sage_curve_facts.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2)# Emit elliptic-curve facts from Cremona's database as JSON, with Sage as the
# source of truth. True facts come straight from Sage; false variants are
# perturbed and RE-CHECKED false by Sage before being emitted.
import json, sys

LABELS = ["11a1", "14a1", "15a1", "17a1", "19a1", "20a1", "21a1", "24a1",
          "26a1", "27a1", "37a1", "43a1", "53a1", "57a1", "58a1", "61a1",
          "65a1", "77a1", "79a1", "83a1", "389a1", "433a1", "446d1", "563a1"]

out = []
for lbl in LABELS:
    E = EllipticCurve(lbl)
    a1, a2, a3, a4, a6 = [QQ(x) for x in E.a_invariants()]
    rec = {"label": lbl, "a": [str(a1), str(a2), str(a3), str(a4), str(a6)],
           "disc": str(E.discriminant()), "rank": int(E.rank())}
    # A rational point: a generator if rank > 0, else a nonzero torsion point.
    pts = [P for P in (E.gens() if E.rank() > _sage_const_0  else E.torsion_points()) if not P.is_zero()]
    if pts:
        P = pts[_sage_const_0 ]
        rec["point"] = [str(P[_sage_const_0 ]), str(P[_sage_const_1 ])]
        # False point: step y until Sage confirms it is NOT on E (a +1 bump
        # can land exactly on the conjugate point -y - a1 x - a3).
        d = _sage_const_1 
        while E.is_on_curve(P[_sage_const_0 ], P[_sage_const_1 ] + d):
            d += _sage_const_1 
        rec["false_point"] = [str(P[_sage_const_0 ]), str(P[_sage_const_1 ] + d)]
        # Group law: P + P (doubling) when 2P is affine.
        Q = _sage_const_2  * P
        if not Q.is_zero():
            rec["double"] = [str(Q[_sage_const_0 ]), str(Q[_sage_const_1 ])]
            # 2P has exactly one y-coordinate, so y+1 is a false claim.
            rec["false_double"] = [str(Q[_sage_const_0 ]), str(Q[_sage_const_1 ] + _sage_const_1 )]
    # False discriminant: off by one, trivially re-checked.
    rec["false_disc"] = str(E.discriminant() + _sage_const_1 )
    out.append(rec)

print(json.dumps(out))

