#!/usr/bin/env python3
"""Generate the numbers and tables of the certified DESI DR2 / H0 paper from the committed P2 and P3 result files."""

from __future__ import annotations

import json
from fractions import Fraction
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
R2 = REPO / "results" / "certified_numerics" / "P2_likelihood"
R3 = REPO / "results" / "certified_numerics" / "P3_h0"


def wrap(spec: str, header: str, rows: list[str]) -> str:
    return "\\begin{tabular}{" + spec + "}\\toprule\n" + header + " \\\\\n\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n"


def main() -> None:
    p2 = json.loads((R2 / "result.json").read_text())
    p3 = json.loads((R3 / "result.json").read_text())
    ref = json.loads((R2 / "refine_plan.json").read_text())
    boxes = json.loads((R3 / "boxes.json").read_text())
    point = json.loads((R3 / "point.json").read_text())
    m: dict[str, str] = {}
    m["FitLo"], m["FitHi"] = (f"{x:.4f}" for x in p2["H6"]["interval"])
    m["FitWidth"] = f"{p2['H6']['width']:.4f}"
    m["MCPFit"] = f"{p2['H6']['mcp_fit_value']:.5f}"
    m["EdSBound"] = f"{p2['H7']['bound']:.2f}"
    m["Thr"] = f"{p2['H8_preregistered_layout']['threshold']:.4f}"
    m["PreExcl"] = str(p2["H8_preregistered_layout"]["n_excluded"])
    m["PreN"] = str(len(p2["H8_preregistered_layout"]["slabs"]))
    exc = [l for l in ref["leaves"] if l["excluded"]]
    m["RefN"] = str(len(exc))
    m["RefMin"] = f"{min(l['L_float'] for l in exc):.2f}"
    m["NAudP2"] = str(p2["C7_axiom_audit"]["n_audited"])
    m["TamperLo"], m["TamperHi"] = (f"{x:.2f}" for x in p2["C6_tampered_data"]["interval"])
    m["UTot"] = f"{point['U_tot_float']:.4f}"
    m["HStar"] = f"{point['h_float']:.6f}"
    m["NBoxes"] = str(len(boxes))
    m["BoxMin"] = f"{min(float(Fraction(b['L'])) + b['prior_min'] for b in boxes):.2f}"
    c8 = p3["C8_rd_vs_python"]
    m["RdLo"], m["RdHi"], m["RdPy"] = f"{c8['certified_lo']:.8f}", f"{c8['certified_hi']:.8f}", f"{c8['common_rd_aubourg16']:.10f}"
    m["NAudP3"] = str(p3["C11_axiom_audit"]["n"])
    rows = [
        f"P2 / H6 & $\\chi^2_{{\\rm BAO}}(0.29743,\\,K_{{\\rm fit}})\\in[{m['FitLo']},\\,{m['FitHi']}]$ & \\texttt{{P2.Fit.chi2\\_fit}} & yes \\\\",
        f"P2 / H7 & $\\forall K:\\ \\chi^2_{{\\rm BAO}}(\\Omega_m{{=}}1,K)\\ge {m['EdSBound']}$ & \\texttt{{P2.EdS.chi2\\_slab}} & yes \\\\",
        f"P2 / H8 & preregistered slabs excluded at $\\Delta\\chi^2>25$ & 19 slab files & \\textbf{{failed}} ({m['PreExcl']}/{m['PreN']}) \\\\",
        f"P2 / A2 & $\\forall\\Omega_m\\in[0,0.255]\\cup[0.35,1],\\forall K:\\ \\chi^2_{{\\rm BAO}}>{m['Thr']}$ & {m['RefN']} slab theorems & yes (post hoc) \\\\",
        f"P3 / H9 & $\\chi^2_{{\\rm tot}}(0.29743,{m['HStar']},0.02218)\\le {m['UTot']}$ & \\texttt{{P3.Point.chi2tot\\_point}} & yes \\\\",
        f"P3 / H10 & $\\forall\\Omega_m\\in[0,1],\\forall\\omega_b,\\forall h\\ge0.73:\\ \\chi^2_{{\\rm tot}}>{m['UTot']}+25$ & \\texttt{{P3.H0\\_ge\\_73\\_excluded}} & yes \\\\",
        "P3 / H11 & the same for $h\\le0.64$ & -- & not attempted \\\\",
    ]
    (HERE / "table_results.tex").write_text(wrap("@{}l p{6.2cm} p{3.6cm} l@{}", "id & statement (kernel-checked unless noted) & Lean & verdict", rows))
    (HERE / "gen_numbers.tex").write_text("% generated by gen_numbers.py; do not edit\n" + "\n".join(f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in m.items()) + "\n")
    print(json.dumps(m, indent=1))


if __name__ == "__main__":
    main()
