import BAOCert.Fit
import BAOCert.FitOm101
import BAOCert.EdS

/-! Generated by scripts/certified_numerics/make_axioms_file.py: axiom audit of every theorem of the pilot,
and two planted negative controls (C3) that must show non-whitelisted axioms. -/

#print axioms BAOCert.arg_pos
#print axioms BAOCert.invE_antitoneOn
#print axioms BAOCert.le_invE_of
#print axioms BAOCert.invE_le_of
#print axioms BAOCert.A_eq
#print axioms BAOCert.node_bounds
#print axioms BAOCert.cell_bounds
#print axioms BAOCert.intervalIntegrable_grid
#print axioms BAOCert.seg_bounds
#print axioms BAOCert.chi_bounds
#print axioms BAOCert.Fit.tbl_check
#print axioms BAOCert.Fit.chi_z0295
#print axioms BAOCert.Fit.invE_z0295
#print axioms BAOCert.Fit.chi_z0510
#print axioms BAOCert.Fit.invE_z0510
#print axioms BAOCert.Fit.chi_z0706
#print axioms BAOCert.Fit.invE_z0706
#print axioms BAOCert.Fit.chi_z0934
#print axioms BAOCert.Fit.invE_z0934
#print axioms BAOCert.Fit.chi_z1321
#print axioms BAOCert.Fit.invE_z1321
#print axioms BAOCert.Fit.chi_z1484
#print axioms BAOCert.Fit.invE_z1484
#print axioms BAOCert.Fit.chi_z2330
#print axioms BAOCert.Fit.invE_z2330
#print axioms BAOCert.FitOm101.tbl_check
#print axioms BAOCert.FitOm101.chi_z0295
#print axioms BAOCert.FitOm101.invE_z0295
#print axioms BAOCert.FitOm101.chi_z0510
#print axioms BAOCert.FitOm101.invE_z0510
#print axioms BAOCert.FitOm101.chi_z0706
#print axioms BAOCert.FitOm101.invE_z0706
#print axioms BAOCert.FitOm101.chi_z0934
#print axioms BAOCert.FitOm101.invE_z0934
#print axioms BAOCert.FitOm101.chi_z1321
#print axioms BAOCert.FitOm101.invE_z1321
#print axioms BAOCert.FitOm101.chi_z1484
#print axioms BAOCert.FitOm101.invE_z1484
#print axioms BAOCert.FitOm101.chi_z2330
#print axioms BAOCert.FitOm101.invE_z2330
#print axioms BAOCert.EdS.tbl_check
#print axioms BAOCert.EdS.chi_z0295
#print axioms BAOCert.EdS.invE_z0295
#print axioms BAOCert.EdS.chi_z0510
#print axioms BAOCert.EdS.invE_z0510
#print axioms BAOCert.EdS.chi_z0706
#print axioms BAOCert.EdS.invE_z0706
#print axioms BAOCert.EdS.chi_z0934
#print axioms BAOCert.EdS.invE_z0934
#print axioms BAOCert.EdS.chi_z1321
#print axioms BAOCert.EdS.invE_z1321
#print axioms BAOCert.EdS.chi_z1484
#print axioms BAOCert.EdS.invE_z1484
#print axioms BAOCert.EdS.chi_z2330
#print axioms BAOCert.EdS.invE_z2330

-- C3 negative controls
theorem ctl_sorry : BAOCert.chi 1 1 = 0 := by sorry
axiom ctl_cheat : False
theorem ctl_axiom : BAOCert.chi 1 1 = 0 := ctl_cheat.elim
#print axioms ctl_sorry
#print axioms ctl_axiom
