#!/usr/bin/env python3
"""Emit formal/ANSE/MasterMathRun2.lean from the run's kernel verdicts.

For each locked statement: the first kernel-clean *prover* proof if one
exists, else the reference (control) proof -- the docstring says which. Each
false variant's refutation is included too. The file carries its own
`#print axioms` lines (LL.md §11b: a footprint check that is not in the
committed source is not reproducible).
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
sys.path.insert(0, str(REPO))  # repo root: `scripts.*` packages

from scripts.master_math.problems import PROBLEMS, TACTICS  # noqa: E402

RUN_DIR = REPO / "results" / "master_math_run2"
OUT = REPO / "formal" / "ANSE" / "MasterMathRun2.lean"


def indent(proof: str) -> str:
    return proof.replace("\n", "\n  ")


def main() -> int:
    runs = json.loads((RUN_DIR / "runs.json").read_text())["runs"]
    modules: list[str] = []
    for p in PROBLEMS:
        for line in p["header"].splitlines():
            m = line.removeprefix("import ").strip()
            if m not in modules and m not in TACTICS:
                modules.append(m)
    parts = ["/-\n  ANSE.MasterMathRun2 -- the 24 locked master-math statements of run two.\n",
             "  Generated by scripts/master_math/emit_lean.py from results/master_math_run2/.\n",
             "  Fidelity is stated per theorem: `proxy` statements are arithmetic stand-ins\n",
             "  and do NOT prove the named theorem; see the paper for the statement review.\n-/\n\n"]
    parts += [f"import {m}\n" for m in modules + TACTICS]
    parts.append("\nnamespace ANSE.MasterMathRun2\n\n")
    names: list[str] = []
    for p in PROBLEMS:
        clean = [r for r in runs if r["id"] == p["id"] and r.get("clean") and r.get("proof")]
        clean.sort(key=lambda r: (r["round"], r["model"]))
        if clean:
            proof, who = clean[0]["proof"], f"{clean[0]['model']} prover, round {clean[0]['round']}"
        else:
            proof, who = p["reference"], "reference control proof (no prover proof passed the kernel)"
        note = f" {p['note']}" if p.get("note") else ""
        parts.append(f"/-- {p['title']} [{p['fidelity']}]. Proof: {who}.{note} -/\n")
        parts.append(f"{p['statement']} := {indent(proof)}\n\n")
        rid = p["id"] + "_F_refuted"
        parts.append("/-- The false variant used as a negative control is refuted. -/\n")
        parts.append(f"theorem {rid} : ¬ ({p['false_prop']}) := {indent(p['refutation'])}\n\n")
        names += [p["id"], rid]
    parts.append("end ANSE.MasterMathRun2\n\n")
    parts += [f"#print axioms ANSE.MasterMathRun2.{n}\n" for n in names]
    OUT.write_text("".join(parts), encoding="utf-8")
    print(f"wrote {OUT} ({len(names)} theorems)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
