"""
anse/gwaya/verifier.py
======================
GWAYA Parallel Verifier for Gemini 3.1 Pro & Gemini 3.8 Flash in Antigravity.

Designed to be executed in parallel or as a pre-flight hook before code edits
are applied to the workspace. Enforces the zero-trust anti-hallucination protocol:
- Blocks stubs, incomplete mocks, and syntax placeholders.
- Blocks security risks (CWE-78 command injection, CWE-94 code injection).
- Scores code against physical energy conservation laws.
"""
from __future__ import annotations

import logging
from typing import Optional

from anse.gwaya.advisor import GwayaAdvisor, GwayaVerificationResult, VerificationVerdict

logger = logging.getLogger("GwayaVerifier")

# Shared global advisor singleton for Antigravity agent sessions
_GLOBAL_ADVISOR: Optional[GwayaAdvisor] = None


def get_gwaya_advisor(mock: bool = False) -> GwayaAdvisor:
    global _GLOBAL_ADVISOR
    if _GLOBAL_ADVISOR is None:
        _GLOBAL_ADVISOR = GwayaAdvisor(mock=mock)
    return _GLOBAL_ADVISOR


def verify_gemini_output(code: str, prompt: str = "", mock: bool = False) -> GwayaVerificationResult:
    """
    Direct function hook for Antigravity agents:
    Evaluates candidate code generated by Gemini 3.1 Pro or Gemini 3.8 Flash.
    Returns GwayaVerificationResult in <50 ms.
    """
    advisor = get_gwaya_advisor(mock=mock)
    result = advisor.verify_generation(candidate_code=code, prompt=prompt)

    if result.should_reject:
        logger.warning(
            f"🚨 [GWAYA VERIFIER ALERT] Gemini output flagged: {result.verdict.value} (E={result.physical_energy:.0f})"
        )
    else:
        logger.info(
            f"✅ [GWAYA VERIFIER PASS] Gemini output verified clean (E={result.physical_energy:.2f}, {result.latency_ms:.1f}ms)"
        )

    return result


def assert_zero_hallucination(code: str, mock: bool = False) -> None:
    """
    Assertion guard for tests and pre-commit checks:
    Raises AssertionError if code contains any stubs or security risks.
    """
    result = verify_gemini_output(code, mock=mock)
    if result.should_reject:
        raise AssertionError(
            f"Zero-Hallucination Invariant Violated! "
            f"Verdict: {result.verdict.value} | Energy: {result.physical_energy} | "
            f"Details: {result.recommendation}"
        )
