"""
QA Agent: Adversarial test generator.
Synthesizes boundary conditions, complexity traps (O(2^N) regex backtracking),
and extreme type mutations to expose hidden flaws in candidate implementations.
"""

from __future__ import annotations

import ast
from dataclasses import dataclass, field


@dataclass
class AdversarialTestReport:
    """Report generated by adversarial test suite generation."""

    target_name: str
    num_tests_generated: int
    test_code: str
    edge_cases_covered: list[str] = field(default_factory=list)


class QAAgent:
    """
    Generates targeted adversarial test suites for Python functions.
    Injects extreme inputs (None, boundary numbers, large collections, malicious payloads).
    """

    def __init__(self) -> None:
        pass

    def inspect_function_signature(self, func_code: str) -> list[tuple[str, list[str]]]:
        """Extracts function names and argument names via AST."""
        functions = []
        try:
            tree = ast.parse(func_code)
            for node in ast.walk(tree):
                if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    args = [a.arg for a in node.args.args if a.arg != "self"]
                    functions.append((node.name, args))
        except Exception:
            pass
        return functions

    def generate_adversarial_suite(
        self,
        module_import: str,
        function_code: str,
    ) -> AdversarialTestReport:
        """
        Generates a pytest test file targeting the function with adversarial inputs.
        """
        funcs = self.inspect_function_signature(function_code)
        if not funcs:
            return AdversarialTestReport(
                target_name="unknown",
                num_tests_generated=0,
                test_code="# No callable function found in input",
                edge_cases_covered=[],
            )

        target_name, args = funcs[0]
        test_lines = [
            f"# Adversarial test suite for {target_name}",
            "from __future__ import annotations",
            "import pytest",
            "import sys",
            "import math",
            f"from {module_import} import {target_name}",
            "",
        ]

        edge_cases: list[str] = []

        # 1. Null / None tests
        if args:
            edge_cases.append("Null / None parameter handling")
            none_args = ", ".join(["None"] * len(args))
            test_lines.extend(
                [
                    f"def test_{target_name}_handles_none():",
                    "    try:",
                    f"        {target_name}({none_args})",
                    "    except (TypeError, ValueError, AttributeError):",
                    "        pass  # Graceful failure or validation error expected",
                    "",
                ]
            )

        # 2. Empty collections / boundary types
        if args:
            edge_cases.append("Empty collections / zero boundaries")
            empty_args = ", ".join(["[]" if i == 0 else "0" for i in range(len(args))])
            test_lines.extend(
                [
                    f"def test_{target_name}_handles_empty_or_zero():",
                    "    try:",
                    f"        {target_name}({empty_args})",
                    "    except (TypeError, ValueError, IndexError, ZeroDivisionError):",
                    "        pass",
                    "",
                ]
            )

        # 3. Numeric boundaries (maxsize, negative, inf, nan)
        if args:
            edge_cases.append("Numeric overflow / NaN / Inf boundaries")
            test_lines.extend(
                [
                    f"def test_{target_name}_numeric_boundaries():",
                    "    for val in [0, -1, sys.maxsize, -sys.maxsize, float('inf'), float('nan')]:",
                    "        try:",
                    f"            {target_name}(val)",
                    "        except (TypeError, ValueError, OverflowError):",
                    "            pass",
                    "",
                ]
            )

        # 4. Exponential complexity / catastrophic input probe
        edge_cases.append("Quadratic / catastrophic string length trap")
        test_lines.extend(
            [
                f"def test_{target_name}_stress_scale():",
                "    large_input = 'a' * 5000",
                "    try:",
                f"        {target_name}(large_input)",
                "    except (TypeError, ValueError):",
                "        pass",
                "",
            ]
        )

        test_code_str = "\n".join(test_lines)
        return AdversarialTestReport(
            target_name=target_name,
            num_tests_generated=len(edge_cases),
            test_code=test_code_str,
            edge_cases_covered=edge_cases,
        )
