import BAOCert.P2.T_R93_320
import BAOCert.P2.T_R949_3200
import BAOCert.H0.Lemmas
import BAOCert.P2.Data

/-! Generated by scripts/certified_numerics/emit_p3.py (untrusted): Om in [93/320, 949/3200], ω_b in [19669/800000, 10027/400000], h ≥ 0.73. -/

namespace BAOCert.P3.Box_050
open BAOCert BAOCert.H0 BAOCert.P2 ANSE.BAOBBNH0

def envs : List Iv := [⟨(267703304273116 : ℚ) / (1000000000000000 : ℚ), (268207509766453 : ℚ) / (1000000000000000 : ℚ)⟩, ⟨(898177695469122 : ℚ) / (2000000000000000 : ℚ), (900310229830916 : ℚ) / (2000000000000000 : ℚ)⟩, ⟨(761500082995 : ℚ) / (1000000000000 : ℚ), (764722995922 : ℚ) / (1000000000000 : ℚ)⟩, ⟨(1179975591254014 : ℚ) / (2000000000000000 : ℚ), (1183559398590994 : ℚ) / (2000000000000000 : ℚ)⟩, ⟨(677918466918 : ℚ) / (1000000000000 : ℚ), (681616011411 : ℚ) / (1000000000000 : ℚ)⟩, ⟨(1469086101666735 : ℚ) / (2000000000000000 : ℚ), (1474496295440611 : ℚ) / (2000000000000000 : ℚ)⟩, ⟨(592481348845 : ℚ) / (1000000000000 : ℚ), (596368320944 : ℚ) / (1000000000000 : ℚ)⟩, ⟨(1880387001111977 : ℚ) / (2000000000000000 : ℚ), (1888886449908396 : ℚ) / (2000000000000000 : ℚ)⟩, ⟨(476111995522 : ℚ) / (1000000000000 : ℚ), (479841090492 : ℚ) / (1000000000000 : ℚ)⟩, ⟨(2028985914770358 : ℚ) / (2000000000000000 : ℚ), (2038717227253036 : ℚ) / (2000000000000000 : ℚ)⟩, ⟨(436484586426 : ℚ) / (1000000000000 : ℚ), (440065151334 : ℚ) / (1000000000000 : ℚ)⟩, ⟨(292925120584 : ℚ) / (1000000000000 : ℚ), (295643218624 : ℚ) / (1000000000000 : ℚ)⟩, ⟨(2633667332536479 : ℚ) / (2000000000000000 : ℚ), (2648861436197349 : ℚ) / (2000000000000000 : ℚ)⟩]

theorem box : ∀ Om : ℝ, (((93 : ℕ) : ℝ) / ((320 : ℕ) : ℝ)) ≤ Om → Om ≤ (((949 : ℕ) : ℝ) / ((3200 : ℕ) : ℝ)) → ∀ wb : ℝ, (((19669 / 800000 : ℚ)) : ℝ) ≤ wb → wb ≤ (((10027 / 400000 : ℚ)) : ℝ) →
    ∀ h : ℝ, 73 / 100 ≤ h → (((1143 / 50 : ℚ)) : ℝ) + ((priorMin (19669 / 800000 : ℚ) (10027 / 400000 : ℚ) : ℚ) : ℝ) ≤ chi2tot Om h wb := by
  intro Om hOa hOb wb hwc hwd h hh
  have ha0 : (0 : ℝ) < (((93 : ℕ) : ℝ) / ((320 : ℕ) : ℝ)) := by norm_num
  have hb1 : (((949 : ℕ) : ℝ) / ((3200 : ℕ) : ℝ)) ≤ 1 := by norm_num
  have hO0 : 0 ≤ Om := ha0.le.trans hOa
  have hO1 : Om ≤ 1 := hOb.trans hb1
  have hz0 : (0 : ℝ) ≤ (((590 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h0 : (⟨(267703304273116 : ℚ) / (1000000000000000 : ℚ), (268207509766453 : ℚ) / (1000000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R949_3200.wV_z0295).1.trans (wV_anti_Om hO0 hOb hb1 hz0),
     (wV_anti_Om ha0.le hOa hO1 hz0).trans (BAOCert.P2.T_R93_320.wV_z0295).2⟩
  have hz1 : (0 : ℝ) ≤ (((1020 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h1 : (⟨(898177695469122 : ℚ) / (2000000000000000 : ℚ), (900310229830916 : ℚ) / (2000000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R949_3200.chi_z0510).1.trans (chi_anti_Om hO0 hOb hb1 hz1),
     (chi_anti_Om ha0.le hOa hO1 hz1).trans (BAOCert.P2.T_R93_320.chi_z0510).2⟩
  have hz2 : (0 : ℝ) ≤ (((1020 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h2 : (⟨(761500082995 : ℚ) / (1000000000000 : ℚ), (764722995922 : ℚ) / (1000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R949_3200.invE_z0510).1.trans (invE_anti_Om hO0 hOb hb1 hz2),
     (invE_anti_Om ha0.le hOa hO1 hz2).trans (BAOCert.P2.T_R93_320.invE_z0510).2⟩
  have hz3 : (0 : ℝ) ≤ (((1412 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h3 : (⟨(1179975591254014 : ℚ) / (2000000000000000 : ℚ), (1183559398590994 : ℚ) / (2000000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R949_3200.chi_z0706).1.trans (chi_anti_Om hO0 hOb hb1 hz3),
     (chi_anti_Om ha0.le hOa hO1 hz3).trans (BAOCert.P2.T_R93_320.chi_z0706).2⟩
  have hz4 : (0 : ℝ) ≤ (((1412 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h4 : (⟨(677918466918 : ℚ) / (1000000000000 : ℚ), (681616011411 : ℚ) / (1000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R949_3200.invE_z0706).1.trans (invE_anti_Om hO0 hOb hb1 hz4),
     (invE_anti_Om ha0.le hOa hO1 hz4).trans (BAOCert.P2.T_R93_320.invE_z0706).2⟩
  have hz5 : (0 : ℝ) ≤ (((1868 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h5 : (⟨(1469086101666735 : ℚ) / (2000000000000000 : ℚ), (1474496295440611 : ℚ) / (2000000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R949_3200.chi_z0934).1.trans (chi_anti_Om hO0 hOb hb1 hz5),
     (chi_anti_Om ha0.le hOa hO1 hz5).trans (BAOCert.P2.T_R93_320.chi_z0934).2⟩
  have hz6 : (0 : ℝ) ≤ (((1868 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h6 : (⟨(592481348845 : ℚ) / (1000000000000 : ℚ), (596368320944 : ℚ) / (1000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R949_3200.invE_z0934).1.trans (invE_anti_Om hO0 hOb hb1 hz6),
     (invE_anti_Om ha0.le hOa hO1 hz6).trans (BAOCert.P2.T_R93_320.invE_z0934).2⟩
  have hz7 : (0 : ℝ) ≤ (((2642 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h7 : (⟨(1880387001111977 : ℚ) / (2000000000000000 : ℚ), (1888886449908396 : ℚ) / (2000000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R949_3200.chi_z1321).1.trans (chi_anti_Om hO0 hOb hb1 hz7),
     (chi_anti_Om ha0.le hOa hO1 hz7).trans (BAOCert.P2.T_R93_320.chi_z1321).2⟩
  have hz8 : (0 : ℝ) ≤ (((2642 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h8 : (⟨(476111995522 : ℚ) / (1000000000000 : ℚ), (479841090492 : ℚ) / (1000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R949_3200.invE_z1321).1.trans (invE_anti_Om hO0 hOb hb1 hz8),
     (invE_anti_Om ha0.le hOa hO1 hz8).trans (BAOCert.P2.T_R93_320.invE_z1321).2⟩
  have hz9 : (0 : ℝ) ≤ (((2968 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h9 : (⟨(2028985914770358 : ℚ) / (2000000000000000 : ℚ), (2038717227253036 : ℚ) / (2000000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R949_3200.chi_z1484).1.trans (chi_anti_Om hO0 hOb hb1 hz9),
     (chi_anti_Om ha0.le hOa hO1 hz9).trans (BAOCert.P2.T_R93_320.chi_z1484).2⟩
  have hz10 : (0 : ℝ) ≤ (((2968 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h10 : (⟨(436484586426 : ℚ) / (1000000000000 : ℚ), (440065151334 : ℚ) / (1000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R949_3200.invE_z1484).1.trans (invE_anti_Om hO0 hOb hb1 hz10),
     (invE_anti_Om ha0.le hOa hO1 hz10).trans (BAOCert.P2.T_R93_320.invE_z1484).2⟩
  have hz11 : (0 : ℝ) ≤ (((4660 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h11 : (⟨(292925120584 : ℚ) / (1000000000000 : ℚ), (295643218624 : ℚ) / (1000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R949_3200.invE_z2330).1.trans (invE_anti_Om hO0 hOb hb1 hz11),
     (invE_anti_Om ha0.le hOa hO1 hz11).trans (BAOCert.P2.T_R93_320.invE_z2330).2⟩
  have hz12 : (0 : ℝ) ≤ (((4660 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h12 : (⟨(2633667332536479 : ℚ) / (2000000000000000 : ℚ), (2648861436197349 : ℚ) / (2000000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R949_3200.chi_z2330).1.trans (chi_anti_Om hO0 hOb hb1 hz12),
     (chi_anti_Om ha0.le hOa hO1 hz12).trans (BAOCert.P2.T_R93_320.chi_z2330).2⟩
  have henv := env_ok envs (Data.xsOf Om) (List.Forall₂.cons h0 (List.Forall₂.cons h1 (List.Forall₂.cons h2 (List.Forall₂.cons h3 (List.Forall₂.cons h4 (List.Forall₂.cons h5 (List.Forall₂.cons h6 (List.Forall₂.cons h7 (List.Forall₂.cons h8 (List.Forall₂.cons h9 (List.Forall₂.cons h10 (List.Forall₂.cons h11 (List.Forall₂.cons h12 List.Forall₂.nil)))))))))))))
  have hcb : omegaCb (73 / 100) (((949 : ℕ) : ℝ) / ((3200 : ℕ) : ℝ)) = (((5036677 / 32000000 : ℚ)) : ℝ) := by unfold omegaCb omegaNu; push_cast; norm_num
  have hrd := (rdIv_mem (5036677 / 32000000 : ℚ) (10027 / 400000 : ℚ) 2 5 60 25 (by decide +kernel)).1
  rw [← hcb] at hrd
  have hrlo : (0 : ℝ) < (((rdIv (5036677 / 32000000 : ℚ) (10027 / 400000 : ℚ) 2 5 60 25).lo : ℚ) : ℝ) := by
    have : (0 : ℚ) < (rdIv (5036677 / 32000000 : ℚ) (10027 / 400000 : ℚ) 2 5 60 25).lo := by decide +kernel
    exact_mod_cast this
  have hc : (299792.458 : ℝ) = ((299792458 / 1000 : ℚ) : ℝ) := by norm_num
  have hKq : (299792.458 : ℝ) / (100 * ((73 / 100) * (((rdIv (5036677 / 32000000 : ℚ) (10027 / 400000 : ℚ) 2 5 60 25).lo : ℚ) : ℝ))) ≤ (((1816575323 / 62500000 : ℚ)) : ℝ) := by
    have hq0 : (299792458 / 1000 : ℚ) / (100 * ((73 / 100) * (rdIv (5036677 / 32000000 : ℚ) (10027 / 400000 : ℚ) 2 5 60 25).lo)) ≤ (1816575323 / 62500000 : ℚ) := by decide +kernel
    have := (Rat.cast_le (K := ℝ)).2 hq0
    rw [hc]; push_cast at this ⊢; exact this
  have hdom : omegaNu ≤ (1 - 2 * 0.25351) * ((((93 : ℕ) : ℝ) / ((320 : ℕ) : ℝ)) * (73 / 100) ^ 2) := by unfold omegaNu; norm_num
  have hK := K_le (rdIv (5036677 / 32000000 : ℚ) (10027 / 400000 : ℚ) 2 5 60 25).lo (1816575323 / 62500000 : ℚ) ha0 (by norm_num) hOa hOb hwc hwd hh hdom hrd hrlo hKq
  have hchi := chi2_lower_Kle Data.Pent Data.dR (1816575323 / 62500000 : ℚ) _ _ henv (1143 / 50 : ℚ) (by decide +kernel) (by decide +kernel) (by decide +kernel) _ hK
  have hpr := prior_ge (c := (19669 / 800000 : ℚ)) (d := (10027 / 400000 : ℚ)) hwc hwd
  unfold chi2tot
  exact add_le_add hchi hpr

end BAOCert.P3.Box_050
