import BAOCert.P2.T_R223_800
import BAOCert.P2.T_R911_3200
import BAOCert.H0.Lemmas
import BAOCert.P2.Data

/-! Generated by scripts/certified_numerics/emit_p3.py (untrusted): Om in [223/800, 911/3200], ω_b in [19669/800000, 10027/400000], h ≥ 0.73. -/

namespace BAOCert.P3.Box_054
open BAOCert BAOCert.H0 BAOCert.P2 ANSE.BAOBBNH0

def envs : List Iv := [⟨(268626032981763 : ℚ) / (1000000000000000 : ℚ), (269134619975088 : ℚ) / (1000000000000000 : ℚ)⟩, ⟨(901988432389743 : ℚ) / (2000000000000000 : ℚ), (904147102858689 : ℚ) / (2000000000000000 : ℚ)⟩, ⟨(767987179521 : ℚ) / (1000000000000 : ℚ), (771293522194 : ℚ) / (1000000000000 : ℚ)⟩, ⟨(1186542891921288 : ℚ) / (2000000000000000 : ℚ), (1190192795432238 : ℚ) / (2000000000000000 : ℚ)⟩, ⟨(685374725601 : ℚ) / (1000000000000 : ℚ), (689196314894 : ℚ) / (1000000000000 : ℚ)⟩, ⟨(1479167612807556 : ℚ) / (2000000000000000 : ℚ), (1484708330983945 : ℚ) / (2000000000000000 : ℚ)⟩, ⟨(600332812139 : ℚ) / (1000000000000 : ℚ), (604377433817 : ℚ) / (1000000000000 : ℚ)⟩, ⟨(1896479544995475 : ℚ) / (2000000000000000 : ℚ), (1905243406415786 : ℚ) / (2000000000000000 : ℚ)⟩, ⟨(483659204024 : ℚ) / (1000000000000 : ℚ), (487569935090 : ℚ) / (1000000000000 : ℚ)⟩, ⟨(2047491797078751 : ℚ) / (2000000000000000 : ℚ), (2057547352217513 : ℚ) / (2000000000000000 : ℚ)⟩, ⟨(443735303194 : ℚ) / (1000000000000 : ℚ), (447498841254 : ℚ) / (1000000000000 : ℚ)⟩, ⟨(298438413548 : ℚ) / (1000000000000 : ℚ), (301314420329 : ℚ) / (1000000000000 : ℚ)⟩, ⟨(2662952982627880 : ℚ) / (2000000000000000 : ℚ), (2678765686708193 : ℚ) / (2000000000000000 : ℚ)⟩]

theorem box : ∀ Om : ℝ, (((223 : ℕ) : ℝ) / ((800 : ℕ) : ℝ)) ≤ Om → Om ≤ (((911 : ℕ) : ℝ) / ((3200 : ℕ) : ℝ)) → ∀ wb : ℝ, (((19669 / 800000 : ℚ)) : ℝ) ≤ wb → wb ≤ (((10027 / 400000 : ℚ)) : ℝ) →
    ∀ h : ℝ, 73 / 100 ≤ h → (((581 / 20 : ℚ)) : ℝ) + ((priorMin (19669 / 800000 : ℚ) (10027 / 400000 : ℚ) : ℚ) : ℝ) ≤ chi2tot Om h wb := by
  intro Om hOa hOb wb hwc hwd h hh
  have ha0 : (0 : ℝ) < (((223 : ℕ) : ℝ) / ((800 : ℕ) : ℝ)) := by norm_num
  have hb1 : (((911 : ℕ) : ℝ) / ((3200 : ℕ) : ℝ)) ≤ 1 := by norm_num
  have hO0 : 0 ≤ Om := ha0.le.trans hOa
  have hO1 : Om ≤ 1 := hOb.trans hb1
  have hz0 : (0 : ℝ) ≤ (((590 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h0 : (⟨(268626032981763 : ℚ) / (1000000000000000 : ℚ), (269134619975088 : ℚ) / (1000000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R911_3200.wV_z0295).1.trans (wV_anti_Om hO0 hOb hb1 hz0),
     (wV_anti_Om ha0.le hOa hO1 hz0).trans (BAOCert.P2.T_R223_800.wV_z0295).2⟩
  have hz1 : (0 : ℝ) ≤ (((1020 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h1 : (⟨(901988432389743 : ℚ) / (2000000000000000 : ℚ), (904147102858689 : ℚ) / (2000000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R911_3200.chi_z0510).1.trans (chi_anti_Om hO0 hOb hb1 hz1),
     (chi_anti_Om ha0.le hOa hO1 hz1).trans (BAOCert.P2.T_R223_800.chi_z0510).2⟩
  have hz2 : (0 : ℝ) ≤ (((1020 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h2 : (⟨(767987179521 : ℚ) / (1000000000000 : ℚ), (771293522194 : ℚ) / (1000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R911_3200.invE_z0510).1.trans (invE_anti_Om hO0 hOb hb1 hz2),
     (invE_anti_Om ha0.le hOa hO1 hz2).trans (BAOCert.P2.T_R223_800.invE_z0510).2⟩
  have hz3 : (0 : ℝ) ≤ (((1412 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h3 : (⟨(1186542891921288 : ℚ) / (2000000000000000 : ℚ), (1190192795432238 : ℚ) / (2000000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R911_3200.chi_z0706).1.trans (chi_anti_Om hO0 hOb hb1 hz3),
     (chi_anti_Om ha0.le hOa hO1 hz3).trans (BAOCert.P2.T_R223_800.chi_z0706).2⟩
  have hz4 : (0 : ℝ) ≤ (((1412 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h4 : (⟨(685374725601 : ℚ) / (1000000000000 : ℚ), (689196314894 : ℚ) / (1000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R911_3200.invE_z0706).1.trans (invE_anti_Om hO0 hOb hb1 hz4),
     (invE_anti_Om ha0.le hOa hO1 hz4).trans (BAOCert.P2.T_R223_800.invE_z0706).2⟩
  have hz5 : (0 : ℝ) ≤ (((1868 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h5 : (⟨(1479167612807556 : ℚ) / (2000000000000000 : ℚ), (1484708330983945 : ℚ) / (2000000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R911_3200.chi_z0934).1.trans (chi_anti_Om hO0 hOb hb1 hz5),
     (chi_anti_Om ha0.le hOa hO1 hz5).trans (BAOCert.P2.T_R223_800.chi_z0934).2⟩
  have hz6 : (0 : ℝ) ≤ (((1868 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h6 : (⟨(600332812139 : ℚ) / (1000000000000 : ℚ), (604377433817 : ℚ) / (1000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R911_3200.invE_z0934).1.trans (invE_anti_Om hO0 hOb hb1 hz6),
     (invE_anti_Om ha0.le hOa hO1 hz6).trans (BAOCert.P2.T_R223_800.invE_z0934).2⟩
  have hz7 : (0 : ℝ) ≤ (((2642 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h7 : (⟨(1896479544995475 : ℚ) / (2000000000000000 : ℚ), (1905243406415786 : ℚ) / (2000000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R911_3200.chi_z1321).1.trans (chi_anti_Om hO0 hOb hb1 hz7),
     (chi_anti_Om ha0.le hOa hO1 hz7).trans (BAOCert.P2.T_R223_800.chi_z1321).2⟩
  have hz8 : (0 : ℝ) ≤ (((2642 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h8 : (⟨(483659204024 : ℚ) / (1000000000000 : ℚ), (487569935090 : ℚ) / (1000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R911_3200.invE_z1321).1.trans (invE_anti_Om hO0 hOb hb1 hz8),
     (invE_anti_Om ha0.le hOa hO1 hz8).trans (BAOCert.P2.T_R223_800.invE_z1321).2⟩
  have hz9 : (0 : ℝ) ≤ (((2968 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h9 : (⟨(2047491797078751 : ℚ) / (2000000000000000 : ℚ), (2057547352217513 : ℚ) / (2000000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R911_3200.chi_z1484).1.trans (chi_anti_Om hO0 hOb hb1 hz9),
     (chi_anti_Om ha0.le hOa hO1 hz9).trans (BAOCert.P2.T_R223_800.chi_z1484).2⟩
  have hz10 : (0 : ℝ) ≤ (((2968 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h10 : (⟨(443735303194 : ℚ) / (1000000000000 : ℚ), (447498841254 : ℚ) / (1000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R911_3200.invE_z1484).1.trans (invE_anti_Om hO0 hOb hb1 hz10),
     (invE_anti_Om ha0.le hOa hO1 hz10).trans (BAOCert.P2.T_R223_800.invE_z1484).2⟩
  have hz11 : (0 : ℝ) ≤ (((4660 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h11 : (⟨(298438413548 : ℚ) / (1000000000000 : ℚ), (301314420329 : ℚ) / (1000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R911_3200.invE_z2330).1.trans (invE_anti_Om hO0 hOb hb1 hz11),
     (invE_anti_Om ha0.le hOa hO1 hz11).trans (BAOCert.P2.T_R223_800.invE_z2330).2⟩
  have hz12 : (0 : ℝ) ≤ (((4660 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h12 : (⟨(2662952982627880 : ℚ) / (2000000000000000 : ℚ), (2678765686708193 : ℚ) / (2000000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R911_3200.chi_z2330).1.trans (chi_anti_Om hO0 hOb hb1 hz12),
     (chi_anti_Om ha0.le hOa hO1 hz12).trans (BAOCert.P2.T_R223_800.chi_z2330).2⟩
  have henv := env_ok envs (Data.xsOf Om) (List.Forall₂.cons h0 (List.Forall₂.cons h1 (List.Forall₂.cons h2 (List.Forall₂.cons h3 (List.Forall₂.cons h4 (List.Forall₂.cons h5 (List.Forall₂.cons h6 (List.Forall₂.cons h7 (List.Forall₂.cons h8 (List.Forall₂.cons h9 (List.Forall₂.cons h10 (List.Forall₂.cons h11 (List.Forall₂.cons h12 List.Forall₂.nil)))))))))))))
  have hcb : omegaCb (73 / 100) (((911 : ℕ) : ℝ) / ((3200 : ℕ) : ℝ)) = (((193367 / 1280000 : ℚ)) : ℝ) := by unfold omegaCb omegaNu; push_cast; norm_num
  have hrd := (rdIv_mem (193367 / 1280000 : ℚ) (10027 / 400000 : ℚ) 2 5 60 25 (by decide +kernel)).1
  rw [← hcb] at hrd
  have hrlo : (0 : ℝ) < (((rdIv (193367 / 1280000 : ℚ) (10027 / 400000 : ℚ) 2 5 60 25).lo : ℚ) : ℝ) := by
    have : (0 : ℚ) < (rdIv (193367 / 1280000 : ℚ) (10027 / 400000 : ℚ) 2 5 60 25).lo := by decide +kernel
    exact_mod_cast this
  have hc : (299792.458 : ℝ) = ((299792458 / 1000 : ℚ) : ℝ) := by norm_num
  have hKq : (299792.458 : ℝ) / (100 * ((73 / 100) * (((rdIv (193367 / 1280000 : ℚ) (10027 / 400000 : ℚ) 2 5 60 25).lo : ℚ) : ℝ))) ≤ (((287644057 / 10000000 : ℚ)) : ℝ) := by
    have hq0 : (299792458 / 1000 : ℚ) / (100 * ((73 / 100) * (rdIv (193367 / 1280000 : ℚ) (10027 / 400000 : ℚ) 2 5 60 25).lo)) ≤ (287644057 / 10000000 : ℚ) := by decide +kernel
    have := (Rat.cast_le (K := ℝ)).2 hq0
    rw [hc]; push_cast at this ⊢; exact this
  have hdom : omegaNu ≤ (1 - 2 * 0.25351) * ((((223 : ℕ) : ℝ) / ((800 : ℕ) : ℝ)) * (73 / 100) ^ 2) := by unfold omegaNu; norm_num
  have hK := K_le (rdIv (193367 / 1280000 : ℚ) (10027 / 400000 : ℚ) 2 5 60 25).lo (287644057 / 10000000 : ℚ) ha0 (by norm_num) hOa hOb hwc hwd hh hdom hrd hrlo hKq
  have hchi := chi2_lower_Kle Data.Pent Data.dR (287644057 / 10000000 : ℚ) _ _ henv (581 / 20 : ℚ) (by decide +kernel) (by decide +kernel) (by decide +kernel) _ hK
  have hpr := prior_ge (c := (19669 / 800000 : ℚ)) (d := (10027 / 400000 : ℚ)) hwc hwd
  unfold chi2tot
  exact add_le_add hchi hpr

end BAOCert.P3.Box_054
