import BAOCert.P2.T_R41_128
import BAOCert.P2.T_R261_800
import BAOCert.H0.Lemmas
import BAOCert.P2.Data

/-! Generated by scripts/certified_numerics/emit_p3.py (untrusted): Om in [41/128, 261/800], ω_b in [9257/400000, 18899/800000], h ≥ 0.73. -/

namespace BAOCert.P3.Box_036
open BAOCert BAOCert.H0 BAOCert.P2 ANSE.BAOBBNH0

def envs : List Iv := [⟨(265445940761148 : ℚ) / (1000000000000000 : ℚ), (265939639453756 : ℚ) / (1000000000000000 : ℚ)⟩, ⟨(888925985971056 : ℚ) / (2000000000000000 : ℚ), (890996851698480 : ℚ) / (2000000000000000 : ℚ)⟩, ⟨(745975250730 : ℚ) / (1000000000000 : ℚ), (749004259647 : ℚ) / (1000000000000 : ℚ)⟩, ⟨(1164169972102354 : ℚ) / (2000000000000000 : ℚ), (1167600158485949 : ℚ) / (2000000000000000 : ℚ)⟩, ⟨(660292918844 : ℚ) / (1000000000000 : ℚ), (663708057117 : ℚ) / (1000000000000 : ℚ)⟩, ⟨(1445021873063479 : ℚ) / (2000000000000000 : ℚ), (1450133072920554 : ℚ) / (2000000000000000 : ℚ)⟩, ⟨(574125745301 : ℚ) / (1000000000000 : ℚ), (577660402137 : ℚ) / (1000000000000 : ℚ)⟩, ⟨(1842365065088485 : ℚ) / (2000000000000000 : ℚ), (1850269526210710 : ℚ) / (2000000000000000 : ℚ)⟩, ⟨(458688627545 : ℚ) / (1000000000000 : ℚ), (462020302433 : ℚ) / (1000000000000 : ℚ)⟩, ⟨(1985403064292422 : ℚ) / (2000000000000000 : ℚ), (1994408796428674 : ℚ) / (2000000000000000 : ℚ)⟩, ⟨(419806687061 : ℚ) / (1000000000000 : ℚ), (422989355727 : ℚ) / (1000000000000 : ℚ)⟩, ⟨(280376493588 : ℚ) / (1000000000000 : ℚ), (282757234011 : ℚ) / (1000000000000 : ℚ)⟩, ⟨(2565435234897958 : ℚ) / (2000000000000000 : ℚ), (2579269691890938 : ℚ) / (2000000000000000 : ℚ)⟩]

theorem box : ∀ Om : ℝ, (((41 : ℕ) : ℝ) / ((128 : ℕ) : ℝ)) ≤ Om → Om ≤ (((261 : ℕ) : ℝ) / ((800 : ℕ) : ℝ)) → ∀ wb : ℝ, (((9257 / 400000 : ℚ)) : ℝ) ≤ wb → wb ≤ (((18899 / 800000 : ℚ)) : ℝ) →
    ∀ h : ℝ, 73 / 100 ≤ h → (((99 / 2 : ℚ)) : ℝ) + ((priorMin (9257 / 400000 : ℚ) (18899 / 800000 : ℚ) : ℚ) : ℝ) ≤ chi2tot Om h wb := by
  intro Om hOa hOb wb hwc hwd h hh
  have ha0 : (0 : ℝ) < (((41 : ℕ) : ℝ) / ((128 : ℕ) : ℝ)) := by norm_num
  have hb1 : (((261 : ℕ) : ℝ) / ((800 : ℕ) : ℝ)) ≤ 1 := by norm_num
  have hO0 : 0 ≤ Om := ha0.le.trans hOa
  have hO1 : Om ≤ 1 := hOb.trans hb1
  have hz0 : (0 : ℝ) ≤ (((590 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h0 : (⟨(265445940761148 : ℚ) / (1000000000000000 : ℚ), (265939639453756 : ℚ) / (1000000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R261_800.wV_z0295).1.trans (wV_anti_Om hO0 hOb hb1 hz0),
     (wV_anti_Om ha0.le hOa hO1 hz0).trans (BAOCert.P2.T_R41_128.wV_z0295).2⟩
  have hz1 : (0 : ℝ) ≤ (((1020 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h1 : (⟨(888925985971056 : ℚ) / (2000000000000000 : ℚ), (890996851698480 : ℚ) / (2000000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R261_800.chi_z0510).1.trans (chi_anti_Om hO0 hOb hb1 hz1),
     (chi_anti_Om ha0.le hOa hO1 hz1).trans (BAOCert.P2.T_R41_128.chi_z0510).2⟩
  have hz2 : (0 : ℝ) ≤ (((1020 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h2 : (⟨(745975250730 : ℚ) / (1000000000000 : ℚ), (749004259647 : ℚ) / (1000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R261_800.invE_z0510).1.trans (invE_anti_Om hO0 hOb hb1 hz2),
     (invE_anti_Om ha0.le hOa hO1 hz2).trans (BAOCert.P2.T_R41_128.invE_z0510).2⟩
  have hz3 : (0 : ℝ) ≤ (((1412 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h3 : (⟨(1164169972102354 : ℚ) / (2000000000000000 : ℚ), (1167600158485949 : ℚ) / (2000000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R261_800.chi_z0706).1.trans (chi_anti_Om hO0 hOb hb1 hz3),
     (chi_anti_Om ha0.le hOa hO1 hz3).trans (BAOCert.P2.T_R41_128.chi_z0706).2⟩
  have hz4 : (0 : ℝ) ≤ (((1412 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h4 : (⟨(660292918844 : ℚ) / (1000000000000 : ℚ), (663708057117 : ℚ) / (1000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R261_800.invE_z0706).1.trans (invE_anti_Om hO0 hOb hb1 hz4),
     (invE_anti_Om ha0.le hOa hO1 hz4).trans (BAOCert.P2.T_R41_128.invE_z0706).2⟩
  have hz5 : (0 : ℝ) ≤ (((1868 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h5 : (⟨(1445021873063479 : ℚ) / (2000000000000000 : ℚ), (1450133072920554 : ℚ) / (2000000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R261_800.chi_z0934).1.trans (chi_anti_Om hO0 hOb hb1 hz5),
     (chi_anti_Om ha0.le hOa hO1 hz5).trans (BAOCert.P2.T_R41_128.chi_z0934).2⟩
  have hz6 : (0 : ℝ) ≤ (((1868 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h6 : (⟨(574125745301 : ℚ) / (1000000000000 : ℚ), (577660402137 : ℚ) / (1000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R261_800.invE_z0934).1.trans (invE_anti_Om hO0 hOb hb1 hz6),
     (invE_anti_Om ha0.le hOa hO1 hz6).trans (BAOCert.P2.T_R41_128.invE_z0934).2⟩
  have hz7 : (0 : ℝ) ≤ (((2642 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h7 : (⟨(1842365065088485 : ℚ) / (2000000000000000 : ℚ), (1850269526210710 : ℚ) / (2000000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R261_800.chi_z1321).1.trans (chi_anti_Om hO0 hOb hb1 hz7),
     (chi_anti_Om ha0.le hOa hO1 hz7).trans (BAOCert.P2.T_R41_128.chi_z1321).2⟩
  have hz8 : (0 : ℝ) ≤ (((2642 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h8 : (⟨(458688627545 : ℚ) / (1000000000000 : ℚ), (462020302433 : ℚ) / (1000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R261_800.invE_z1321).1.trans (invE_anti_Om hO0 hOb hb1 hz8),
     (invE_anti_Om ha0.le hOa hO1 hz8).trans (BAOCert.P2.T_R41_128.invE_z1321).2⟩
  have hz9 : (0 : ℝ) ≤ (((2968 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h9 : (⟨(1985403064292422 : ℚ) / (2000000000000000 : ℚ), (1994408796428674 : ℚ) / (2000000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R261_800.chi_z1484).1.trans (chi_anti_Om hO0 hOb hb1 hz9),
     (chi_anti_Om ha0.le hOa hO1 hz9).trans (BAOCert.P2.T_R41_128.chi_z1484).2⟩
  have hz10 : (0 : ℝ) ≤ (((2968 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h10 : (⟨(419806687061 : ℚ) / (1000000000000 : ℚ), (422989355727 : ℚ) / (1000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R261_800.invE_z1484).1.trans (invE_anti_Om hO0 hOb hb1 hz10),
     (invE_anti_Om ha0.le hOa hO1 hz10).trans (BAOCert.P2.T_R41_128.invE_z1484).2⟩
  have hz11 : (0 : ℝ) ≤ (((4660 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h11 : (⟨(280376493588 : ℚ) / (1000000000000 : ℚ), (282757234011 : ℚ) / (1000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R261_800.invE_z2330).1.trans (invE_anti_Om hO0 hOb hb1 hz11),
     (invE_anti_Om ha0.le hOa hO1 hz11).trans (BAOCert.P2.T_R41_128.invE_z2330).2⟩
  have hz12 : (0 : ℝ) ≤ (((4660 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h12 : (⟨(2565435234897958 : ℚ) / (2000000000000000 : ℚ), (2579269691890938 : ℚ) / (2000000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R261_800.chi_z2330).1.trans (chi_anti_Om hO0 hOb hb1 hz12),
     (chi_anti_Om ha0.le hOa hO1 hz12).trans (BAOCert.P2.T_R41_128.chi_z2330).2⟩
  have henv := env_ok envs (Data.xsOf Om) (List.Forall₂.cons h0 (List.Forall₂.cons h1 (List.Forall₂.cons h2 (List.Forall₂.cons h3 (List.Forall₂.cons h4 (List.Forall₂.cons h5 (List.Forall₂.cons h6 (List.Forall₂.cons h7 (List.Forall₂.cons h8 (List.Forall₂.cons h9 (List.Forall₂.cons h10 (List.Forall₂.cons h11 (List.Forall₂.cons h12 List.Forall₂.nil)))))))))))))
  have hcb : omegaCb (73 / 100) (((261 : ℕ) : ℝ) / ((800 : ℕ) : ℝ)) = (((1385733 / 8000000 : ℚ)) : ℝ) := by unfold omegaCb omegaNu; push_cast; norm_num
  have hrd := (rdIv_mem (1385733 / 8000000 : ℚ) (18899 / 800000 : ℚ) 2 5 60 25 (by decide +kernel)).1
  rw [← hcb] at hrd
  have hrlo : (0 : ℝ) < (((rdIv (1385733 / 8000000 : ℚ) (18899 / 800000 : ℚ) 2 5 60 25).lo : ℚ) : ℝ) := by
    have : (0 : ℚ) < (rdIv (1385733 / 8000000 : ℚ) (18899 / 800000 : ℚ) 2 5 60 25).lo := by decide +kernel
    exact_mod_cast this
  have hc : (299792.458 : ℝ) = ((299792458 / 1000 : ℚ) : ℝ) := by norm_num
  have hKq : (299792.458 : ℝ) / (100 * ((73 / 100) * (((rdIv (1385733 / 8000000 : ℚ) (18899 / 800000 : ℚ) 2 5 60 25).lo : ℚ) : ℝ))) ≤ (((1182167141 / 40000000 : ℚ)) : ℝ) := by
    have hq0 : (299792458 / 1000 : ℚ) / (100 * ((73 / 100) * (rdIv (1385733 / 8000000 : ℚ) (18899 / 800000 : ℚ) 2 5 60 25).lo)) ≤ (1182167141 / 40000000 : ℚ) := by decide +kernel
    have := (Rat.cast_le (K := ℝ)).2 hq0
    rw [hc]; push_cast at this ⊢; exact this
  have hdom : omegaNu ≤ (1 - 2 * 0.25351) * ((((41 : ℕ) : ℝ) / ((128 : ℕ) : ℝ)) * (73 / 100) ^ 2) := by unfold omegaNu; norm_num
  have hK := K_le (rdIv (1385733 / 8000000 : ℚ) (18899 / 800000 : ℚ) 2 5 60 25).lo (1182167141 / 40000000 : ℚ) ha0 (by norm_num) hOa hOb hwc hwd hh hdom hrd hrlo hKq
  have hchi := chi2_lower_Kle Data.Pent Data.dR (1182167141 / 40000000 : ℚ) _ _ henv (99 / 2 : ℚ) (by decide +kernel) (by decide +kernel) (by decide +kernel) _ hK
  have hpr := prior_ge (c := (9257 / 400000 : ℚ)) (d := (18899 / 800000 : ℚ)) hwc hwd
  unfold chi2tot
  exact add_le_add hchi hpr

end BAOCert.P3.Box_036
