import BAOCert.P2.T_R51_200
import BAOCert.P2.T_R427_1600
import BAOCert.H0.Lemmas
import BAOCert.P2.Data

/-! Generated by scripts/certified_numerics/emit_p3.py (untrusted): Om in [51/200, 427/1600], ω_b in [9257/400000, 4821/200000], h ≥ 0.73. -/

namespace BAOCert.P3.Box_072
open BAOCert BAOCert.H0 BAOCert.P2 ANSE.BAOBBNH0

def envs : List Iv := [⟨(270032126150930 : ℚ) / (1000000000000000 : ℚ), (271024501038135 : ℚ) / (1000000000000000 : ℚ)⟩, ⟨(907828858619406 : ℚ) / (2000000000000000 : ℚ), (912023609492420 : ℚ) / (2000000000000000 : ℚ)⟩, ⟨(778036374447 : ℚ) / (1000000000000 : ℚ), (784959219527 : ℚ) / (1000000000000 : ℚ)⟩, ⟨(1196675056045130 : ℚ) / (2000000000000000 : ℚ), (1203921714900556 : ℚ) / (2000000000000000 : ℚ)⟩, ⟨(697035280423 : ℚ) / (1000000000000 : ℚ), (705147961280 : ℚ) / (1000000000000 : ℚ)⟩, ⟨(1494820721936230 : ℚ) / (2000000000000000 : ℚ), (1506010795594597 : ℚ) / (2000000000000000 : ℚ)⟩, ⟨(612718146142 : ℚ) / (1000000000000 : ℚ), (621413990116 : ℚ) / (1000000000000 : ℚ)⟩, ⟨(1921666231597021 : ℚ) / (2000000000000000 : ℚ), (1939705759308836 : ℚ) / (2000000000000000 : ℚ)⟩, ⟨(495684696553 : ℚ) / (1000000000000 : ℚ), (504218598436 : ℚ) / (1000000000000 : ℚ)⟩, ⟨(2076529665809086 : ℚ) / (2000000000000000 : ℚ), (2097347289030668 : ℚ) / (2000000000000000 : ℚ)⟩, ⟨(455322438392 : ℚ) / (1000000000000 : ℚ), (463571265027 : ℚ) / (1000000000000 : ℚ)⟩, ⟨(307325030075 : ℚ) / (1000000000000 : ℚ), (313710311896 : ℚ) / (1000000000000 : ℚ)⟩, ⟨(2709300759138740 : ℚ) / (2000000000000000 : ℚ), (2742655277648003 : ℚ) / (2000000000000000 : ℚ)⟩]

theorem box : ∀ Om : ℝ, (((51 : ℕ) : ℝ) / ((200 : ℕ) : ℝ)) ≤ Om → Om ≤ (((427 : ℕ) : ℝ) / ((1600 : ℕ) : ℝ)) → ∀ wb : ℝ, (((9257 / 400000 : ℚ)) : ℝ) ≤ wb → wb ≤ (((4821 / 200000 : ℚ)) : ℝ) →
    ∀ h : ℝ, 73 / 100 ≤ h → (((4913 / 100 : ℚ)) : ℝ) + ((priorMin (9257 / 400000 : ℚ) (4821 / 200000 : ℚ) : ℚ) : ℝ) ≤ chi2tot Om h wb := by
  intro Om hOa hOb wb hwc hwd h hh
  have ha0 : (0 : ℝ) < (((51 : ℕ) : ℝ) / ((200 : ℕ) : ℝ)) := by norm_num
  have hb1 : (((427 : ℕ) : ℝ) / ((1600 : ℕ) : ℝ)) ≤ 1 := by norm_num
  have hO0 : 0 ≤ Om := ha0.le.trans hOa
  have hO1 : Om ≤ 1 := hOb.trans hb1
  have hz0 : (0 : ℝ) ≤ (((590 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h0 : (⟨(270032126150930 : ℚ) / (1000000000000000 : ℚ), (271024501038135 : ℚ) / (1000000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R427_1600.wV_z0295).1.trans (wV_anti_Om hO0 hOb hb1 hz0),
     (wV_anti_Om ha0.le hOa hO1 hz0).trans (BAOCert.P2.T_R51_200.wV_z0295).2⟩
  have hz1 : (0 : ℝ) ≤ (((1020 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h1 : (⟨(907828858619406 : ℚ) / (2000000000000000 : ℚ), (912023609492420 : ℚ) / (2000000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R427_1600.chi_z0510).1.trans (chi_anti_Om hO0 hOb hb1 hz1),
     (chi_anti_Om ha0.le hOa hO1 hz1).trans (BAOCert.P2.T_R51_200.chi_z0510).2⟩
  have hz2 : (0 : ℝ) ≤ (((1020 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h2 : (⟨(778036374447 : ℚ) / (1000000000000 : ℚ), (784959219527 : ℚ) / (1000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R427_1600.invE_z0510).1.trans (invE_anti_Om hO0 hOb hb1 hz2),
     (invE_anti_Om ha0.le hOa hO1 hz2).trans (BAOCert.P2.T_R51_200.invE_z0510).2⟩
  have hz3 : (0 : ℝ) ≤ (((1412 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h3 : (⟨(1196675056045130 : ℚ) / (2000000000000000 : ℚ), (1203921714900556 : ℚ) / (2000000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R427_1600.chi_z0706).1.trans (chi_anti_Om hO0 hOb hb1 hz3),
     (chi_anti_Om ha0.le hOa hO1 hz3).trans (BAOCert.P2.T_R51_200.chi_z0706).2⟩
  have hz4 : (0 : ℝ) ≤ (((1412 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h4 : (⟨(697035280423 : ℚ) / (1000000000000 : ℚ), (705147961280 : ℚ) / (1000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R427_1600.invE_z0706).1.trans (invE_anti_Om hO0 hOb hb1 hz4),
     (invE_anti_Om ha0.le hOa hO1 hz4).trans (BAOCert.P2.T_R51_200.invE_z0706).2⟩
  have hz5 : (0 : ℝ) ≤ (((1868 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h5 : (⟨(1494820721936230 : ℚ) / (2000000000000000 : ℚ), (1506010795594597 : ℚ) / (2000000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R427_1600.chi_z0934).1.trans (chi_anti_Om hO0 hOb hb1 hz5),
     (chi_anti_Om ha0.le hOa hO1 hz5).trans (BAOCert.P2.T_R51_200.chi_z0934).2⟩
  have hz6 : (0 : ℝ) ≤ (((1868 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h6 : (⟨(612718146142 : ℚ) / (1000000000000 : ℚ), (621413990116 : ℚ) / (1000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R427_1600.invE_z0934).1.trans (invE_anti_Om hO0 hOb hb1 hz6),
     (invE_anti_Om ha0.le hOa hO1 hz6).trans (BAOCert.P2.T_R51_200.invE_z0934).2⟩
  have hz7 : (0 : ℝ) ≤ (((2642 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h7 : (⟨(1921666231597021 : ℚ) / (2000000000000000 : ℚ), (1939705759308836 : ℚ) / (2000000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R427_1600.chi_z1321).1.trans (chi_anti_Om hO0 hOb hb1 hz7),
     (chi_anti_Om ha0.le hOa hO1 hz7).trans (BAOCert.P2.T_R51_200.chi_z1321).2⟩
  have hz8 : (0 : ℝ) ≤ (((2642 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h8 : (⟨(495684696553 : ℚ) / (1000000000000 : ℚ), (504218598436 : ℚ) / (1000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R427_1600.invE_z1321).1.trans (invE_anti_Om hO0 hOb hb1 hz8),
     (invE_anti_Om ha0.le hOa hO1 hz8).trans (BAOCert.P2.T_R51_200.invE_z1321).2⟩
  have hz9 : (0 : ℝ) ≤ (((2968 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h9 : (⟨(2076529665809086 : ℚ) / (2000000000000000 : ℚ), (2097347289030668 : ℚ) / (2000000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R427_1600.chi_z1484).1.trans (chi_anti_Om hO0 hOb hb1 hz9),
     (chi_anti_Om ha0.le hOa hO1 hz9).trans (BAOCert.P2.T_R51_200.chi_z1484).2⟩
  have hz10 : (0 : ℝ) ≤ (((2968 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h10 : (⟨(455322438392 : ℚ) / (1000000000000 : ℚ), (463571265027 : ℚ) / (1000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R427_1600.invE_z1484).1.trans (invE_anti_Om hO0 hOb hb1 hz10),
     (invE_anti_Om ha0.le hOa hO1 hz10).trans (BAOCert.P2.T_R51_200.invE_z1484).2⟩
  have hz11 : (0 : ℝ) ≤ (((4660 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h11 : (⟨(307325030075 : ℚ) / (1000000000000 : ℚ), (313710311896 : ℚ) / (1000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R427_1600.invE_z2330).1.trans (invE_anti_Om hO0 hOb hb1 hz11),
     (invE_anti_Om ha0.le hOa hO1 hz11).trans (BAOCert.P2.T_R51_200.invE_z2330).2⟩
  have hz12 : (0 : ℝ) ≤ (((4660 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h12 : (⟨(2709300759138740 : ℚ) / (2000000000000000 : ℚ), (2742655277648003 : ℚ) / (2000000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R427_1600.chi_z2330).1.trans (chi_anti_Om hO0 hOb hb1 hz12),
     (chi_anti_Om ha0.le hOa hO1 hz12).trans (BAOCert.P2.T_R51_200.chi_z2330).2⟩
  have henv := env_ok envs (Data.xsOf Om) (List.Forall₂.cons h0 (List.Forall₂.cons h1 (List.Forall₂.cons h2 (List.Forall₂.cons h3 (List.Forall₂.cons h4 (List.Forall₂.cons h5 (List.Forall₂.cons h6 (List.Forall₂.cons h7 (List.Forall₂.cons h8 (List.Forall₂.cons h9 (List.Forall₂.cons h10 (List.Forall₂.cons h11 (List.Forall₂.cons h12 List.Forall₂.nil)))))))))))))
  have hcb : omegaCb (73 / 100) (((427 : ℕ) : ℝ) / ((1600 : ℕ) : ℝ)) = (((2265211 / 16000000 : ℚ)) : ℝ) := by unfold omegaCb omegaNu; push_cast; norm_num
  have hrd := (rdIv_mem (2265211 / 16000000 : ℚ) (4821 / 200000 : ℚ) 2 5 60 25 (by decide +kernel)).1
  rw [← hcb] at hrd
  have hrlo : (0 : ℝ) < (((rdIv (2265211 / 16000000 : ℚ) (4821 / 200000 : ℚ) 2 5 60 25).lo : ℚ) : ℝ) := by
    have : (0 : ℚ) < (rdIv (2265211 / 16000000 : ℚ) (4821 / 200000 : ℚ) 2 5 60 25).lo := by decide +kernel
    exact_mod_cast this
  have hc : (299792.458 : ℝ) = ((299792458 / 1000 : ℚ) : ℝ) := by norm_num
  have hKq : (299792.458 : ℝ) / (100 * ((73 / 100) * (((rdIv (2265211 / 16000000 : ℚ) (4821 / 200000 : ℚ) 2 5 60 25).lo : ℚ) : ℝ))) ≤ (((3519191323 / 125000000 : ℚ)) : ℝ) := by
    have hq0 : (299792458 / 1000 : ℚ) / (100 * ((73 / 100) * (rdIv (2265211 / 16000000 : ℚ) (4821 / 200000 : ℚ) 2 5 60 25).lo)) ≤ (3519191323 / 125000000 : ℚ) := by decide +kernel
    have := (Rat.cast_le (K := ℝ)).2 hq0
    rw [hc]; push_cast at this ⊢; exact this
  have hdom : omegaNu ≤ (1 - 2 * 0.25351) * ((((51 : ℕ) : ℝ) / ((200 : ℕ) : ℝ)) * (73 / 100) ^ 2) := by unfold omegaNu; norm_num
  have hK := K_le (rdIv (2265211 / 16000000 : ℚ) (4821 / 200000 : ℚ) 2 5 60 25).lo (3519191323 / 125000000 : ℚ) ha0 (by norm_num) hOa hOb hwc hwd hh hdom hrd hrlo hKq
  have hchi := chi2_lower_Kle Data.Pent Data.dR (3519191323 / 125000000 : ℚ) _ _ henv (4913 / 100 : ℚ) (by decide +kernel) (by decide +kernel) (by decide +kernel) _ hK
  have hpr := prior_ge (c := (9257 / 400000 : ℚ)) (d := (4821 / 200000 : ℚ)) hwc hwd
  unfold chi2tot
  exact add_le_add hchi hpr

end BAOCert.P3.Box_072
