import BAOCert.P2.T_R121_400
import BAOCert.P2.T_R503_1600
import BAOCert.H0.Lemmas
import BAOCert.P2.Data

/-! Generated by scripts/certified_numerics/emit_p3.py (untrusted): Om in [121/400, 503/1600], ω_b in [8487/400000, 1109/50000], h ≥ 0.73. -/

namespace BAOCert.P3.Box_079
open BAOCert BAOCert.H0 BAOCert.P2 ANSE.BAOBBNH0

def envs : List Iv := [⟨(266340563203229 : ℚ) / (1000000000000000 : ℚ), (267291933136914 : ℚ) / (1000000000000000 : ℚ)⟩, ⟨(892580725969946 : ℚ) / (2000000000000000 : ℚ), (896538086701353 : ℚ) / (2000000000000000 : ℚ)⟩, ⟨(752070468346 : ℚ) / (1000000000000 : ℚ), (758317578334 : ℚ) / (1000000000000 : ℚ)⟩, ⟨(1170390705148132 : ℚ) / (2000000000000000 : ℚ), (1177071596301063 : ℚ) / (2000000000000000 : ℚ)⟩, ⟨(667176740404 : ℚ) / (1000000000000 : ℚ), (674280450791 : ℚ) / (1000000000000 : ℚ)⟩, ⟨(1454460094086419 : ℚ) / (2000000000000000 : ℚ), (1464557562302759 : ℚ) / (2000000000000000 : ℚ)⟩, ⟨(581261157577 : ℚ) / (1000000000000 : ℚ), (588669402072 : ℚ) / (1000000000000 : ℚ)⟩, ⟨(1857213527177802 : ℚ) / (2000000000000000 : ℚ), (1873065180797749 : ℚ) / (2000000000000000 : ℚ)⟩, ⟨(465425646815 : ℚ) / (1000000000000 : ℚ), (472468512941 : ℚ) / (1000000000000 : ℚ)⟩, ⟨(2002400032783205 : ℚ) / (2000000000000000 : ℚ), (2020539505450969 : ℚ) / (2000000000000000 : ℚ)⟩, ⟨(426245525602 : ℚ) / (1000000000000 : ℚ), (432990022160 : ℚ) / (1000000000000 : ℚ)⟩, ⟨(285199669135 : ℚ) / (1000000000000 : ℚ), (290280639242 : ℚ) / (1000000000000 : ℚ)⟩, ⟨(2591924877724946 : ℚ) / (2000000000000000 : ℚ), (2620182149509967 : ℚ) / (2000000000000000 : ℚ)⟩]

theorem box : ∀ Om : ℝ, (((121 : ℕ) : ℝ) / ((400 : ℕ) : ℝ)) ≤ Om → Om ≤ (((503 : ℕ) : ℝ) / ((1600 : ℕ) : ℝ)) → ∀ wb : ℝ, (((8487 / 400000 : ℚ)) : ℝ) ≤ wb → wb ≤ (((1109 / 50000 : ℚ)) : ℝ) →
    ∀ h : ℝ, 73 / 100 ≤ h → (((6251 / 100 : ℚ)) : ℝ) + ((priorMin (8487 / 400000 : ℚ) (1109 / 50000 : ℚ) : ℚ) : ℝ) ≤ chi2tot Om h wb := by
  intro Om hOa hOb wb hwc hwd h hh
  have ha0 : (0 : ℝ) < (((121 : ℕ) : ℝ) / ((400 : ℕ) : ℝ)) := by norm_num
  have hb1 : (((503 : ℕ) : ℝ) / ((1600 : ℕ) : ℝ)) ≤ 1 := by norm_num
  have hO0 : 0 ≤ Om := ha0.le.trans hOa
  have hO1 : Om ≤ 1 := hOb.trans hb1
  have hz0 : (0 : ℝ) ≤ (((590 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h0 : (⟨(266340563203229 : ℚ) / (1000000000000000 : ℚ), (267291933136914 : ℚ) / (1000000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R503_1600.wV_z0295).1.trans (wV_anti_Om hO0 hOb hb1 hz0),
     (wV_anti_Om ha0.le hOa hO1 hz0).trans (BAOCert.P2.T_R121_400.wV_z0295).2⟩
  have hz1 : (0 : ℝ) ≤ (((1020 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h1 : (⟨(892580725969946 : ℚ) / (2000000000000000 : ℚ), (896538086701353 : ℚ) / (2000000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R503_1600.chi_z0510).1.trans (chi_anti_Om hO0 hOb hb1 hz1),
     (chi_anti_Om ha0.le hOa hO1 hz1).trans (BAOCert.P2.T_R121_400.chi_z0510).2⟩
  have hz2 : (0 : ℝ) ≤ (((1020 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h2 : (⟨(752070468346 : ℚ) / (1000000000000 : ℚ), (758317578334 : ℚ) / (1000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R503_1600.invE_z0510).1.trans (invE_anti_Om hO0 hOb hb1 hz2),
     (invE_anti_Om ha0.le hOa hO1 hz2).trans (BAOCert.P2.T_R121_400.invE_z0510).2⟩
  have hz3 : (0 : ℝ) ≤ (((1412 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h3 : (⟨(1170390705148132 : ℚ) / (2000000000000000 : ℚ), (1177071596301063 : ℚ) / (2000000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R503_1600.chi_z0706).1.trans (chi_anti_Om hO0 hOb hb1 hz3),
     (chi_anti_Om ha0.le hOa hO1 hz3).trans (BAOCert.P2.T_R121_400.chi_z0706).2⟩
  have hz4 : (0 : ℝ) ≤ (((1412 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h4 : (⟨(667176740404 : ℚ) / (1000000000000 : ℚ), (674280450791 : ℚ) / (1000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R503_1600.invE_z0706).1.trans (invE_anti_Om hO0 hOb hb1 hz4),
     (invE_anti_Om ha0.le hOa hO1 hz4).trans (BAOCert.P2.T_R121_400.invE_z0706).2⟩
  have hz5 : (0 : ℝ) ≤ (((1868 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h5 : (⟨(1454460094086419 : ℚ) / (2000000000000000 : ℚ), (1464557562302759 : ℚ) / (2000000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R503_1600.chi_z0934).1.trans (chi_anti_Om hO0 hOb hb1 hz5),
     (chi_anti_Om ha0.le hOa hO1 hz5).trans (BAOCert.P2.T_R121_400.chi_z0934).2⟩
  have hz6 : (0 : ℝ) ≤ (((1868 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h6 : (⟨(581261157577 : ℚ) / (1000000000000 : ℚ), (588669402072 : ℚ) / (1000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R503_1600.invE_z0934).1.trans (invE_anti_Om hO0 hOb hb1 hz6),
     (invE_anti_Om ha0.le hOa hO1 hz6).trans (BAOCert.P2.T_R121_400.invE_z0934).2⟩
  have hz7 : (0 : ℝ) ≤ (((2642 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h7 : (⟨(1857213527177802 : ℚ) / (2000000000000000 : ℚ), (1873065180797749 : ℚ) / (2000000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R503_1600.chi_z1321).1.trans (chi_anti_Om hO0 hOb hb1 hz7),
     (chi_anti_Om ha0.le hOa hO1 hz7).trans (BAOCert.P2.T_R121_400.chi_z1321).2⟩
  have hz8 : (0 : ℝ) ≤ (((2642 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h8 : (⟨(465425646815 : ℚ) / (1000000000000 : ℚ), (472468512941 : ℚ) / (1000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R503_1600.invE_z1321).1.trans (invE_anti_Om hO0 hOb hb1 hz8),
     (invE_anti_Om ha0.le hOa hO1 hz8).trans (BAOCert.P2.T_R121_400.invE_z1321).2⟩
  have hz9 : (0 : ℝ) ≤ (((2968 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h9 : (⟨(2002400032783205 : ℚ) / (2000000000000000 : ℚ), (2020539505450969 : ℚ) / (2000000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R503_1600.chi_z1484).1.trans (chi_anti_Om hO0 hOb hb1 hz9),
     (chi_anti_Om ha0.le hOa hO1 hz9).trans (BAOCert.P2.T_R121_400.chi_z1484).2⟩
  have hz10 : (0 : ℝ) ≤ (((2968 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h10 : (⟨(426245525602 : ℚ) / (1000000000000 : ℚ), (432990022160 : ℚ) / (1000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R503_1600.invE_z1484).1.trans (invE_anti_Om hO0 hOb hb1 hz10),
     (invE_anti_Om ha0.le hOa hO1 hz10).trans (BAOCert.P2.T_R121_400.invE_z1484).2⟩
  have hz11 : (0 : ℝ) ≤ (((4660 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h11 : (⟨(285199669135 : ℚ) / (1000000000000 : ℚ), (290280639242 : ℚ) / (1000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R503_1600.invE_z2330).1.trans (invE_anti_Om hO0 hOb hb1 hz11),
     (invE_anti_Om ha0.le hOa hO1 hz11).trans (BAOCert.P2.T_R121_400.invE_z2330).2⟩
  have hz12 : (0 : ℝ) ≤ (((4660 : ℕ) : ℝ) / ((2000 : ℕ) : ℝ)) := by positivity
  have h12 : (⟨(2591924877724946 : ℚ) / (2000000000000000 : ℚ), (2620182149509967 : ℚ) / (2000000000000000 : ℚ)⟩ : Iv).mem _ :=
    ⟨(BAOCert.P2.T_R503_1600.chi_z2330).1.trans (chi_anti_Om hO0 hOb hb1 hz12),
     (chi_anti_Om ha0.le hOa hO1 hz12).trans (BAOCert.P2.T_R121_400.chi_z2330).2⟩
  have henv := env_ok envs (Data.xsOf Om) (List.Forall₂.cons h0 (List.Forall₂.cons h1 (List.Forall₂.cons h2 (List.Forall₂.cons h3 (List.Forall₂.cons h4 (List.Forall₂.cons h5 (List.Forall₂.cons h6 (List.Forall₂.cons h7 (List.Forall₂.cons h8 (List.Forall₂.cons h9 (List.Forall₂.cons h10 (List.Forall₂.cons h11 (List.Forall₂.cons h12 List.Forall₂.nil)))))))))))))
  have hcb : omegaCb (73 / 100) (((503 : ℕ) : ℝ) / ((1600 : ℕ) : ℝ)) = (((534043 / 3200000 : ℚ)) : ℝ) := by unfold omegaCb omegaNu; push_cast; norm_num
  have hrd := (rdIv_mem (534043 / 3200000 : ℚ) (1109 / 50000 : ℚ) 2 5 60 25 (by decide +kernel)).1
  rw [← hcb] at hrd
  have hrlo : (0 : ℝ) < (((rdIv (534043 / 3200000 : ℚ) (1109 / 50000 : ℚ) 2 5 60 25).lo : ℚ) : ℝ) := by
    have : (0 : ℚ) < (rdIv (534043 / 3200000 : ℚ) (1109 / 50000 : ℚ) 2 5 60 25).lo := by decide +kernel
    exact_mod_cast this
  have hc : (299792.458 : ℝ) = ((299792458 / 1000 : ℚ) : ℝ) := by norm_num
  have hKq : (299792.458 : ℝ) / (100 * ((73 / 100) * (((rdIv (534043 / 3200000 : ℚ) (1109 / 50000 : ℚ) 2 5 60 25).lo : ℚ) : ℝ))) ≤ (((5808230363 / 200000000 : ℚ)) : ℝ) := by
    have hq0 : (299792458 / 1000 : ℚ) / (100 * ((73 / 100) * (rdIv (534043 / 3200000 : ℚ) (1109 / 50000 : ℚ) 2 5 60 25).lo)) ≤ (5808230363 / 200000000 : ℚ) := by decide +kernel
    have := (Rat.cast_le (K := ℝ)).2 hq0
    rw [hc]; push_cast at this ⊢; exact this
  have hdom : omegaNu ≤ (1 - 2 * 0.25351) * ((((121 : ℕ) : ℝ) / ((400 : ℕ) : ℝ)) * (73 / 100) ^ 2) := by unfold omegaNu; norm_num
  have hK := K_le (rdIv (534043 / 3200000 : ℚ) (1109 / 50000 : ℚ) 2 5 60 25).lo (5808230363 / 200000000 : ℚ) ha0 (by norm_num) hOa hOb hwc hwd hh hdom hrd hrlo hKq
  have hchi := chi2_lower_Kle Data.Pent Data.dR (5808230363 / 200000000 : ℚ) _ _ henv (6251 / 100 : ℚ) (by decide +kernel) (by decide +kernel) (by decide +kernel) _ hK
  have hpr := prior_ge (c := (8487 / 400000 : ℚ)) (d := (1109 / 50000 : ℚ)) hwc hwd
  unfold chi2tot
  exact add_le_add hchi hpr

end BAOCert.P3.Box_079
