import BAOCert.P2.Ref_O000_R1_40
import BAOCert.P2.Ref_O005_O010
import BAOCert.P2.Ref_O010_R1_8
import BAOCert.P2.Ref_O015_R7_40
import BAOCert.P2.Ref_O020_O022
import BAOCert.P2.Ref_O022_R23_100
import BAOCert.P2.Ref_O024_R49_200
import BAOCert.P2.Ref_O025_R101_400
import BAOCert.P2.Ref_O035_R141_400
import BAOCert.P2.Ref_O036_R37_100
import BAOCert.P2.Ref_O038_O040
import BAOCert.P2.Ref_O040_R17_40
import BAOCert.P2.Ref_O045_O050
import BAOCert.P2.Ref_O050_R11_20
import BAOCert.P2.Ref_O060_O070
import BAOCert.P2.Ref_O070_O080
import BAOCert.P2.Ref_O080_O090
import BAOCert.P2.Ref_O090_O100
import BAOCert.P2.Ref_R101_400_R51_200
import BAOCert.P2.Ref_R11_20_O060
import BAOCert.P2.Ref_R141_400_R71_200
import BAOCert.P2.Ref_R17_40_O045
import BAOCert.P2.Ref_R1_40_O005
import BAOCert.P2.Ref_R1_8_O015
import BAOCert.P2.Ref_R23_100_O024
import BAOCert.P2.Ref_R37_100_O038
import BAOCert.P2.Ref_R49_200_O025
import BAOCert.P2.Ref_R71_200_O036
import BAOCert.P2.Ref_R7_40_O020
import BAOCert.P3.Box_000
import BAOCert.P3.Box_001
import BAOCert.P3.Box_002
import BAOCert.P3.Box_003
import BAOCert.P3.Box_004
import BAOCert.P3.Box_005
import BAOCert.P3.Box_006
import BAOCert.P3.Box_007
import BAOCert.P3.Box_008
import BAOCert.P3.Box_009
import BAOCert.P3.Box_010
import BAOCert.P3.Box_011
import BAOCert.P3.Box_012
import BAOCert.P3.Box_013
import BAOCert.P3.Box_014
import BAOCert.P3.Box_015
import BAOCert.P3.Box_016
import BAOCert.P3.Box_017
import BAOCert.P3.Box_018
import BAOCert.P3.Box_019
import BAOCert.P3.Box_020
import BAOCert.P3.Box_021
import BAOCert.P3.Box_022
import BAOCert.P3.Box_023
import BAOCert.P3.Box_024
import BAOCert.P3.Box_025
import BAOCert.P3.Box_026
import BAOCert.P3.Box_027
import BAOCert.P3.Box_028
import BAOCert.P3.Box_029
import BAOCert.P3.Box_030
import BAOCert.P3.Box_031
import BAOCert.P3.Box_032
import BAOCert.P3.Box_033
import BAOCert.P3.Box_034
import BAOCert.P3.Box_035
import BAOCert.P3.Box_036
import BAOCert.P3.Box_037
import BAOCert.P3.Box_038
import BAOCert.P3.Box_039
import BAOCert.P3.Box_040
import BAOCert.P3.Box_041
import BAOCert.P3.Box_042
import BAOCert.P3.Box_043
import BAOCert.P3.Box_044
import BAOCert.P3.Box_045
import BAOCert.P3.Box_046
import BAOCert.P3.Box_047
import BAOCert.P3.Box_048
import BAOCert.P3.Box_049
import BAOCert.P3.Box_050
import BAOCert.P3.Box_051
import BAOCert.P3.Box_052
import BAOCert.P3.Box_053
import BAOCert.P3.Box_054
import BAOCert.P3.Box_055
import BAOCert.P3.Box_056
import BAOCert.P3.Box_057
import BAOCert.P3.Box_058
import BAOCert.P3.Box_059
import BAOCert.P3.Box_060
import BAOCert.P3.Box_061
import BAOCert.P3.Box_062
import BAOCert.P3.Box_063
import BAOCert.P3.Box_064
import BAOCert.P3.Box_065
import BAOCert.P3.Box_066
import BAOCert.P3.Box_067
import BAOCert.P3.Box_068
import BAOCert.P3.Box_069
import BAOCert.P3.Box_070
import BAOCert.P3.Box_071
import BAOCert.P3.Box_072
import BAOCert.P3.Box_073
import BAOCert.P3.Box_074
import BAOCert.P3.Box_075
import BAOCert.P3.Box_076
import BAOCert.P3.Box_077
import BAOCert.P3.Box_078
import BAOCert.P3.Box_079
import BAOCert.P3.Box_080
import BAOCert.P3.Box_081
import BAOCert.P3.Box_082
import BAOCert.P3.Box_083
import BAOCert.P3.Box_084
import BAOCert.P3.Box_085
import BAOCert.P3.Box_086
import BAOCert.P3.Box_087
import BAOCert.P3.Box_088
import BAOCert.P3.Glue
import BAOCert.P3.Point

/-! Generated by scripts/certified_numerics/emit_p3.py (untrusted): assembly of the certified H0 ≥ 73 exclusion. -/

namespace BAOCert.P3
open BAOCert BAOCert.H0

/-- **Certified Hubble tension (DESI DR2 BAO + BBN, flat ΛCDM, radiation off, Aubourg r_d).**
For every `Om ∈ [0, 1]`, every `ω_b` and every `h ≥ 0.73`, `χ²_total > 10.2897 + 25`. -/
theorem H0_ge_73_excluded : ∀ Om h wb : ℝ, 0 ≤ Om → Om ≤ 1 → 73 / 100 ≤ h → ((((352897 / 10000 : ℚ)) : ℚ) : ℝ) < chi2tot Om h wb := by
  intro Om h wb hO0 hO1 hh
  rcases lt_or_ge wb (1833 / 100000) with hw1 | hw1
  · exact gt_of_prior (Or.inl hw1) (by norm_num)
  rcases lt_or_ge (2603 / 100000) wb with hw2 | hw2
  · exact gt_of_prior (Or.inr hw2) (by norm_num)
  have hwc : (((1833 / 100000 : ℚ)) : ℝ) ≤ wb := by push_cast; linarith
  have hwd : wb ≤ (((2603 / 100000 : ℚ)) : ℝ) := by push_cast; linarith
  have hOa0 : (((0 : ℕ) : ℝ) / ((1 : ℕ) : ℝ)) ≤ Om := by norm_num; exact hO0
  have hOb1 : Om ≤ (((1 : ℕ) : ℝ) / ((1 : ℕ) : ℝ)) := by norm_num; exact hO1
  rcases le_or_gt Om (((51 : ℕ) : ℝ) / ((200 : ℕ) : ℝ)) with hL | hL
  ·
    rcases le_or_gt Om (((1 : ℕ) : ℝ) / ((40 : ℕ) : ℝ)) with hS0 | hS0
    · exact gt_of_slab (BAOCert.P2.Ref_O000_R1_40.chi2_slab Om hOa0 hS0 _) (by decide +kernel)
    rcases le_or_gt Om (((5 : ℕ) : ℝ) / ((100 : ℕ) : ℝ)) with hS1 | hS1
    · exact gt_of_slab (BAOCert.P2.Ref_R1_40_O005.chi2_slab Om hS0.le hS1 _) (by decide +kernel)
    rcases le_or_gt Om (((10 : ℕ) : ℝ) / ((100 : ℕ) : ℝ)) with hS2 | hS2
    · exact gt_of_slab (BAOCert.P2.Ref_O005_O010.chi2_slab Om hS1.le hS2 _) (by decide +kernel)
    rcases le_or_gt Om (((1 : ℕ) : ℝ) / ((8 : ℕ) : ℝ)) with hS3 | hS3
    · exact gt_of_slab (BAOCert.P2.Ref_O010_R1_8.chi2_slab Om hS2.le hS3 _) (by decide +kernel)
    rcases le_or_gt Om (((15 : ℕ) : ℝ) / ((100 : ℕ) : ℝ)) with hS4 | hS4
    · exact gt_of_slab (BAOCert.P2.Ref_R1_8_O015.chi2_slab Om hS3.le hS4 _) (by decide +kernel)
    rcases le_or_gt Om (((7 : ℕ) : ℝ) / ((40 : ℕ) : ℝ)) with hS5 | hS5
    · exact gt_of_slab (BAOCert.P2.Ref_O015_R7_40.chi2_slab Om hS4.le hS5 _) (by decide +kernel)
    rcases le_or_gt Om (((20 : ℕ) : ℝ) / ((100 : ℕ) : ℝ)) with hS6 | hS6
    · exact gt_of_slab (BAOCert.P2.Ref_R7_40_O020.chi2_slab Om hS5.le hS6 _) (by decide +kernel)
    rcases le_or_gt Om (((22 : ℕ) : ℝ) / ((100 : ℕ) : ℝ)) with hS7 | hS7
    · exact gt_of_slab (BAOCert.P2.Ref_O020_O022.chi2_slab Om hS6.le hS7 _) (by decide +kernel)
    rcases le_or_gt Om (((23 : ℕ) : ℝ) / ((100 : ℕ) : ℝ)) with hS8 | hS8
    · exact gt_of_slab (BAOCert.P2.Ref_O022_R23_100.chi2_slab Om hS7.le hS8 _) (by decide +kernel)
    rcases le_or_gt Om (((24 : ℕ) : ℝ) / ((100 : ℕ) : ℝ)) with hS9 | hS9
    · exact gt_of_slab (BAOCert.P2.Ref_R23_100_O024.chi2_slab Om hS8.le hS9 _) (by decide +kernel)
    rcases le_or_gt Om (((49 : ℕ) : ℝ) / ((200 : ℕ) : ℝ)) with hS10 | hS10
    · exact gt_of_slab (BAOCert.P2.Ref_O024_R49_200.chi2_slab Om hS9.le hS10 _) (by decide +kernel)
    rcases le_or_gt Om (((25 : ℕ) : ℝ) / ((100 : ℕ) : ℝ)) with hS11 | hS11
    · exact gt_of_slab (BAOCert.P2.Ref_R49_200_O025.chi2_slab Om hS10.le hS11 _) (by decide +kernel)
    rcases le_or_gt Om (((101 : ℕ) : ℝ) / ((400 : ℕ) : ℝ)) with hS12 | hS12
    · exact gt_of_slab (BAOCert.P2.Ref_O025_R101_400.chi2_slab Om hS11.le hS12 _) (by decide +kernel)
    exact gt_of_slab (BAOCert.P2.Ref_R101_400_R51_200.chi2_slab Om hS12.le hL _) (by decide +kernel)
  ·
    rcases le_or_gt Om (((35 : ℕ) : ℝ) / ((100 : ℕ) : ℝ)) with hU | hU
    ·
      rcases le_or_gt wb (((1109 / 50000 : ℚ)) : ℝ) with hW3 | hW3
      ·
        rcases le_or_gt Om (((121 : ℕ) : ℝ) / ((400 : ℕ) : ℝ)) with hO4 | hO4
        ·
          rcases le_or_gt wb (((4051 / 200000 : ℚ)) : ℝ) with hW5 | hW5
          ·
            rcases le_or_gt Om (((223 : ℕ) : ℝ) / ((800 : ℕ) : ℝ)) with hO6 | hO6
            ·
              exact gt_of_box (BAOCert.P3.Box_088.box Om hL.le hO6 wb hwc hW5 h hh) (by decide +kernel)
            ·
              exact gt_of_box (BAOCert.P3.Box_087.box Om hO6.le hO4 wb hwc hW5 h hh) (by decide +kernel)
          ·
            rcases le_or_gt Om (((223 : ℕ) : ℝ) / ((800 : ℕ) : ℝ)) with hO6 | hO6
            ·
              exact gt_of_box (BAOCert.P3.Box_086.box Om hL.le hO6 wb hW5.le hW3 h hh) (by decide +kernel)
            ·
              rcases le_or_gt wb (((8487 / 400000 : ℚ)) : ℝ) with hW7 | hW7
              ·
                exact gt_of_box (BAOCert.P3.Box_085.box Om hO6.le hO4 wb hW5.le hW7 h hh) (by decide +kernel)
              ·
                rcases le_or_gt Om (((93 : ℕ) : ℝ) / ((320 : ℕ) : ℝ)) with hO8 | hO8
                ·
                  exact gt_of_box (BAOCert.P3.Box_084.box Om hO6.le hO8 wb hW7.le hW3 h hh) (by decide +kernel)
                ·
                  exact gt_of_box (BAOCert.P3.Box_083.box Om hO8.le hO4 wb hW7.le hW3 h hh) (by decide +kernel)
        ·
          rcases le_or_gt wb (((4051 / 200000 : ℚ)) : ℝ) with hW5 | hW5
          ·
            rcases le_or_gt Om (((261 : ℕ) : ℝ) / ((800 : ℕ) : ℝ)) with hO6 | hO6
            ·
              exact gt_of_box (BAOCert.P3.Box_082.box Om hO4.le hO6 wb hwc hW5 h hh) (by decide +kernel)
            ·
              exact gt_of_box (BAOCert.P3.Box_081.box Om hO6.le hU wb hwc hW5 h hh) (by decide +kernel)
          ·
            rcases le_or_gt Om (((261 : ℕ) : ℝ) / ((800 : ℕ) : ℝ)) with hO6 | hO6
            ·
              rcases le_or_gt wb (((8487 / 400000 : ℚ)) : ℝ) with hW7 | hW7
              ·
                exact gt_of_box (BAOCert.P3.Box_080.box Om hO4.le hO6 wb hW5.le hW7 h hh) (by decide +kernel)
              ·
                rcases le_or_gt Om (((503 : ℕ) : ℝ) / ((1600 : ℕ) : ℝ)) with hO8 | hO8
                ·
                  exact gt_of_box (BAOCert.P3.Box_079.box Om hO4.le hO8 wb hW7.le hW3 h hh) (by decide +kernel)
                ·
                  exact gt_of_box (BAOCert.P3.Box_078.box Om hO8.le hO6 wb hW7.le hW3 h hh) (by decide +kernel)
            ·
              rcases le_or_gt wb (((8487 / 400000 : ℚ)) : ℝ) with hW7 | hW7
              ·
                exact gt_of_box (BAOCert.P3.Box_077.box Om hO6.le hU wb hW5.le hW7 h hh) (by decide +kernel)
              ·
                rcases le_or_gt Om (((541 : ℕ) : ℝ) / ((1600 : ℕ) : ℝ)) with hO8 | hO8
                ·
                  exact gt_of_box (BAOCert.P3.Box_076.box Om hO6.le hO8 wb hW7.le hW3 h hh) (by decide +kernel)
                ·
                  exact gt_of_box (BAOCert.P3.Box_075.box Om hO8.le hU wb hW7.le hW3 h hh) (by decide +kernel)
      ·
        rcases le_or_gt Om (((121 : ℕ) : ℝ) / ((400 : ℕ) : ℝ)) with hO4 | hO4
        ·
          rcases le_or_gt wb (((4821 / 200000 : ℚ)) : ℝ) with hW5 | hW5
          ·
            rcases le_or_gt Om (((223 : ℕ) : ℝ) / ((800 : ℕ) : ℝ)) with hO6 | hO6
            ·
              rcases le_or_gt wb (((9257 / 400000 : ℚ)) : ℝ) with hW7 | hW7
              ·
                rcases le_or_gt Om (((427 : ℕ) : ℝ) / ((1600 : ℕ) : ℝ)) with hO8 | hO8
                ·
                  exact gt_of_box (BAOCert.P3.Box_074.box Om hL.le hO8 wb hW3.le hW7 h hh) (by decide +kernel)
                ·
                  exact gt_of_box (BAOCert.P3.Box_073.box Om hO8.le hO6 wb hW3.le hW7 h hh) (by decide +kernel)
              ·
                rcases le_or_gt Om (((427 : ℕ) : ℝ) / ((1600 : ℕ) : ℝ)) with hO8 | hO8
                ·
                  exact gt_of_box (BAOCert.P3.Box_072.box Om hL.le hO8 wb hW7.le hW5 h hh) (by decide +kernel)
                ·
                  exact gt_of_box (BAOCert.P3.Box_071.box Om hO8.le hO6 wb hW7.le hW5 h hh) (by decide +kernel)
            ·
              rcases le_or_gt wb (((9257 / 400000 : ℚ)) : ℝ) with hW7 | hW7
              ·
                rcases le_or_gt Om (((93 : ℕ) : ℝ) / ((320 : ℕ) : ℝ)) with hO8 | hO8
                ·
                  exact gt_of_box (BAOCert.P3.Box_070.box Om hO6.le hO8 wb hW3.le hW7 h hh) (by decide +kernel)
                ·
                  exact gt_of_box (BAOCert.P3.Box_069.box Om hO8.le hO4 wb hW3.le hW7 h hh) (by decide +kernel)
              ·
                rcases le_or_gt Om (((93 : ℕ) : ℝ) / ((320 : ℕ) : ℝ)) with hO8 | hO8
                ·
                  rcases le_or_gt wb (((18899 / 800000 : ℚ)) : ℝ) with hW9 | hW9
                  ·
                    exact gt_of_box (BAOCert.P3.Box_068.box Om hO6.le hO8 wb hW7.le hW9 h hh) (by decide +kernel)
                  ·
                    rcases le_or_gt Om (((911 : ℕ) : ℝ) / ((3200 : ℕ) : ℝ)) with hO10 | hO10
                    ·
                      exact gt_of_box (BAOCert.P3.Box_067.box Om hO6.le hO10 wb hW9.le hW5 h hh) (by decide +kernel)
                    ·
                      exact gt_of_box (BAOCert.P3.Box_066.box Om hO10.le hO8 wb hW9.le hW5 h hh) (by decide +kernel)
                ·
                  rcases le_or_gt wb (((18899 / 800000 : ℚ)) : ℝ) with hW9 | hW9
                  ·
                    rcases le_or_gt Om (((949 : ℕ) : ℝ) / ((3200 : ℕ) : ℝ)) with hO10 | hO10
                    ·
                      exact gt_of_box (BAOCert.P3.Box_065.box Om hO8.le hO10 wb hW7.le hW9 h hh) (by decide +kernel)
                    ·
                      exact gt_of_box (BAOCert.P3.Box_064.box Om hO10.le hO4 wb hW7.le hW9 h hh) (by decide +kernel)
                  ·
                    rcases le_or_gt Om (((949 : ℕ) : ℝ) / ((3200 : ℕ) : ℝ)) with hO10 | hO10
                    ·
                      exact gt_of_box (BAOCert.P3.Box_063.box Om hO8.le hO10 wb hW9.le hW5 h hh) (by decide +kernel)
                    ·
                      exact gt_of_box (BAOCert.P3.Box_062.box Om hO10.le hO4 wb hW9.le hW5 h hh) (by decide +kernel)
          ·
            rcases le_or_gt Om (((223 : ℕ) : ℝ) / ((800 : ℕ) : ℝ)) with hO6 | hO6
            ·
              rcases le_or_gt wb (((10027 / 400000 : ℚ)) : ℝ) with hW7 | hW7
              ·
                rcases le_or_gt Om (((427 : ℕ) : ℝ) / ((1600 : ℕ) : ℝ)) with hO8 | hO8
                ·
                  exact gt_of_box (BAOCert.P3.Box_061.box Om hL.le hO8 wb hW5.le hW7 h hh) (by decide +kernel)
                ·
                  rcases le_or_gt wb (((19669 / 800000 : ℚ)) : ℝ) with hW9 | hW9
                  ·
                    exact gt_of_box (BAOCert.P3.Box_060.box Om hO8.le hO6 wb hW5.le hW9 h hh) (by decide +kernel)
                  ·
                    exact gt_of_box (BAOCert.P3.Box_059.box Om hO8.le hO6 wb hW9.le hW7 h hh) (by decide +kernel)
              ·
                rcases le_or_gt Om (((427 : ℕ) : ℝ) / ((1600 : ℕ) : ℝ)) with hO8 | hO8
                ·
                  exact gt_of_box (BAOCert.P3.Box_058.box Om hL.le hO8 wb hW7.le hwd h hh) (by decide +kernel)
                ·
                  exact gt_of_box (BAOCert.P3.Box_057.box Om hO8.le hO6 wb hW7.le hwd h hh) (by decide +kernel)
            ·
              rcases le_or_gt wb (((10027 / 400000 : ℚ)) : ℝ) with hW7 | hW7
              ·
                rcases le_or_gt Om (((93 : ℕ) : ℝ) / ((320 : ℕ) : ℝ)) with hO8 | hO8
                ·
                  rcases le_or_gt wb (((19669 / 800000 : ℚ)) : ℝ) with hW9 | hW9
                  ·
                    rcases le_or_gt Om (((911 : ℕ) : ℝ) / ((3200 : ℕ) : ℝ)) with hO10 | hO10
                    ·
                      exact gt_of_box (BAOCert.P3.Box_056.box Om hO6.le hO10 wb hW5.le hW9 h hh) (by decide +kernel)
                    ·
                      exact gt_of_box (BAOCert.P3.Box_055.box Om hO10.le hO8 wb hW5.le hW9 h hh) (by decide +kernel)
                  ·
                    rcases le_or_gt Om (((911 : ℕ) : ℝ) / ((3200 : ℕ) : ℝ)) with hO10 | hO10
                    ·
                      exact gt_of_box (BAOCert.P3.Box_054.box Om hO6.le hO10 wb hW9.le hW7 h hh) (by decide +kernel)
                    ·
                      exact gt_of_box (BAOCert.P3.Box_053.box Om hO10.le hO8 wb hW9.le hW7 h hh) (by decide +kernel)
                ·
                  rcases le_or_gt wb (((19669 / 800000 : ℚ)) : ℝ) with hW9 | hW9
                  ·
                    rcases le_or_gt Om (((949 : ℕ) : ℝ) / ((3200 : ℕ) : ℝ)) with hO10 | hO10
                    ·
                      exact gt_of_box (BAOCert.P3.Box_052.box Om hO8.le hO10 wb hW5.le hW9 h hh) (by decide +kernel)
                    ·
                      exact gt_of_box (BAOCert.P3.Box_051.box Om hO10.le hO4 wb hW5.le hW9 h hh) (by decide +kernel)
                  ·
                    rcases le_or_gt Om (((949 : ℕ) : ℝ) / ((3200 : ℕ) : ℝ)) with hO10 | hO10
                    ·
                      exact gt_of_box (BAOCert.P3.Box_050.box Om hO8.le hO10 wb hW9.le hW7 h hh) (by decide +kernel)
                    ·
                      exact gt_of_box (BAOCert.P3.Box_049.box Om hO10.le hO4 wb hW9.le hW7 h hh) (by decide +kernel)
              ·
                rcases le_or_gt Om (((93 : ℕ) : ℝ) / ((320 : ℕ) : ℝ)) with hO8 | hO8
                ·
                  rcases le_or_gt wb (((20439 / 800000 : ℚ)) : ℝ) with hW9 | hW9
                  ·
                    exact gt_of_box (BAOCert.P3.Box_048.box Om hO6.le hO8 wb hW7.le hW9 h hh) (by decide +kernel)
                  ·
                    exact gt_of_box (BAOCert.P3.Box_047.box Om hO6.le hO8 wb hW9.le hwd h hh) (by decide +kernel)
                ·
                  rcases le_or_gt wb (((20439 / 800000 : ℚ)) : ℝ) with hW9 | hW9
                  ·
                    rcases le_or_gt Om (((949 : ℕ) : ℝ) / ((3200 : ℕ) : ℝ)) with hO10 | hO10
                    ·
                      exact gt_of_box (BAOCert.P3.Box_046.box Om hO8.le hO10 wb hW7.le hW9 h hh) (by decide +kernel)
                    ·
                      exact gt_of_box (BAOCert.P3.Box_045.box Om hO10.le hO4 wb hW7.le hW9 h hh) (by decide +kernel)
                  ·
                    exact gt_of_box (BAOCert.P3.Box_044.box Om hO8.le hO4 wb hW9.le hwd h hh) (by decide +kernel)
        ·
          rcases le_or_gt wb (((4821 / 200000 : ℚ)) : ℝ) with hW5 | hW5
          ·
            rcases le_or_gt Om (((261 : ℕ) : ℝ) / ((800 : ℕ) : ℝ)) with hO6 | hO6
            ·
              rcases le_or_gt wb (((9257 / 400000 : ℚ)) : ℝ) with hW7 | hW7
              ·
                rcases le_or_gt Om (((503 : ℕ) : ℝ) / ((1600 : ℕ) : ℝ)) with hO8 | hO8
                ·
                  exact gt_of_box (BAOCert.P3.Box_043.box Om hO4.le hO8 wb hW3.le hW7 h hh) (by decide +kernel)
                ·
                  exact gt_of_box (BAOCert.P3.Box_042.box Om hO8.le hO6 wb hW3.le hW7 h hh) (by decide +kernel)
              ·
                rcases le_or_gt Om (((503 : ℕ) : ℝ) / ((1600 : ℕ) : ℝ)) with hO8 | hO8
                ·
                  rcases le_or_gt wb (((18899 / 800000 : ℚ)) : ℝ) with hW9 | hW9
                  ·
                    rcases le_or_gt Om (((987 : ℕ) : ℝ) / ((3200 : ℕ) : ℝ)) with hO10 | hO10
                    ·
                      exact gt_of_box (BAOCert.P3.Box_041.box Om hO4.le hO10 wb hW7.le hW9 h hh) (by decide +kernel)
                    ·
                      exact gt_of_box (BAOCert.P3.Box_040.box Om hO10.le hO8 wb hW7.le hW9 h hh) (by decide +kernel)
                  ·
                    rcases le_or_gt Om (((987 : ℕ) : ℝ) / ((3200 : ℕ) : ℝ)) with hO10 | hO10
                    ·
                      exact gt_of_box (BAOCert.P3.Box_039.box Om hO4.le hO10 wb hW9.le hW5 h hh) (by decide +kernel)
                    ·
                      exact gt_of_box (BAOCert.P3.Box_038.box Om hO10.le hO8 wb hW9.le hW5 h hh) (by decide +kernel)
                ·
                  rcases le_or_gt wb (((18899 / 800000 : ℚ)) : ℝ) with hW9 | hW9
                  ·
                    rcases le_or_gt Om (((41 : ℕ) : ℝ) / ((128 : ℕ) : ℝ)) with hO10 | hO10
                    ·
                      exact gt_of_box (BAOCert.P3.Box_037.box Om hO8.le hO10 wb hW7.le hW9 h hh) (by decide +kernel)
                    ·
                      exact gt_of_box (BAOCert.P3.Box_036.box Om hO10.le hO6 wb hW7.le hW9 h hh) (by decide +kernel)
                  ·
                    rcases le_or_gt Om (((41 : ℕ) : ℝ) / ((128 : ℕ) : ℝ)) with hO10 | hO10
                    ·
                      exact gt_of_box (BAOCert.P3.Box_035.box Om hO8.le hO10 wb hW9.le hW5 h hh) (by decide +kernel)
                    ·
                      exact gt_of_box (BAOCert.P3.Box_034.box Om hO10.le hO6 wb hW9.le hW5 h hh) (by decide +kernel)
            ·
              rcases le_or_gt wb (((9257 / 400000 : ℚ)) : ℝ) with hW7 | hW7
              ·
                rcases le_or_gt Om (((541 : ℕ) : ℝ) / ((1600 : ℕ) : ℝ)) with hO8 | hO8
                ·
                  exact gt_of_box (BAOCert.P3.Box_033.box Om hO6.le hO8 wb hW3.le hW7 h hh) (by decide +kernel)
                ·
                  exact gt_of_box (BAOCert.P3.Box_032.box Om hO8.le hU wb hW3.le hW7 h hh) (by decide +kernel)
              ·
                rcases le_or_gt Om (((541 : ℕ) : ℝ) / ((1600 : ℕ) : ℝ)) with hO8 | hO8
                ·
                  rcases le_or_gt wb (((18899 / 800000 : ℚ)) : ℝ) with hW9 | hW9
                  ·
                    exact gt_of_box (BAOCert.P3.Box_031.box Om hO6.le hO8 wb hW7.le hW9 h hh) (by decide +kernel)
                  ·
                    rcases le_or_gt Om (((1063 : ℕ) : ℝ) / ((3200 : ℕ) : ℝ)) with hO10 | hO10
                    ·
                      exact gt_of_box (BAOCert.P3.Box_030.box Om hO6.le hO10 wb hW9.le hW5 h hh) (by decide +kernel)
                    ·
                      exact gt_of_box (BAOCert.P3.Box_029.box Om hO10.le hO8 wb hW9.le hW5 h hh) (by decide +kernel)
                ·
                  exact gt_of_box (BAOCert.P3.Box_028.box Om hO8.le hU wb hW7.le hW5 h hh) (by decide +kernel)
          ·
            rcases le_or_gt Om (((261 : ℕ) : ℝ) / ((800 : ℕ) : ℝ)) with hO6 | hO6
            ·
              rcases le_or_gt wb (((10027 / 400000 : ℚ)) : ℝ) with hW7 | hW7
              ·
                rcases le_or_gt Om (((503 : ℕ) : ℝ) / ((1600 : ℕ) : ℝ)) with hO8 | hO8
                ·
                  rcases le_or_gt wb (((19669 / 800000 : ℚ)) : ℝ) with hW9 | hW9
                  ·
                    rcases le_or_gt Om (((987 : ℕ) : ℝ) / ((3200 : ℕ) : ℝ)) with hO10 | hO10
                    ·
                      exact gt_of_box (BAOCert.P3.Box_027.box Om hO4.le hO10 wb hW5.le hW9 h hh) (by decide +kernel)
                    ·
                      exact gt_of_box (BAOCert.P3.Box_026.box Om hO10.le hO8 wb hW5.le hW9 h hh) (by decide +kernel)
                  ·
                    rcases le_or_gt Om (((987 : ℕ) : ℝ) / ((3200 : ℕ) : ℝ)) with hO10 | hO10
                    ·
                      exact gt_of_box (BAOCert.P3.Box_025.box Om hO4.le hO10 wb hW9.le hW7 h hh) (by decide +kernel)
                    ·
                      exact gt_of_box (BAOCert.P3.Box_024.box Om hO10.le hO8 wb hW9.le hW7 h hh) (by decide +kernel)
                ·
                  rcases le_or_gt wb (((19669 / 800000 : ℚ)) : ℝ) with hW9 | hW9
                  ·
                    rcases le_or_gt Om (((41 : ℕ) : ℝ) / ((128 : ℕ) : ℝ)) with hO10 | hO10
                    ·
                      exact gt_of_box (BAOCert.P3.Box_023.box Om hO8.le hO10 wb hW5.le hW9 h hh) (by decide +kernel)
                    ·
                      exact gt_of_box (BAOCert.P3.Box_022.box Om hO10.le hO6 wb hW5.le hW9 h hh) (by decide +kernel)
                  ·
                    rcases le_or_gt Om (((41 : ℕ) : ℝ) / ((128 : ℕ) : ℝ)) with hO10 | hO10
                    ·
                      exact gt_of_box (BAOCert.P3.Box_021.box Om hO8.le hO10 wb hW9.le hW7 h hh) (by decide +kernel)
                    ·
                      exact gt_of_box (BAOCert.P3.Box_020.box Om hO10.le hO6 wb hW9.le hW7 h hh) (by decide +kernel)
              ·
                rcases le_or_gt Om (((503 : ℕ) : ℝ) / ((1600 : ℕ) : ℝ)) with hO8 | hO8
                ·
                  rcases le_or_gt wb (((20439 / 800000 : ℚ)) : ℝ) with hW9 | hW9
                  ·
                    rcases le_or_gt Om (((987 : ℕ) : ℝ) / ((3200 : ℕ) : ℝ)) with hO10 | hO10
                    ·
                      exact gt_of_box (BAOCert.P3.Box_019.box Om hO4.le hO10 wb hW7.le hW9 h hh) (by decide +kernel)
                    ·
                      exact gt_of_box (BAOCert.P3.Box_018.box Om hO10.le hO8 wb hW7.le hW9 h hh) (by decide +kernel)
                  ·
                    rcases le_or_gt Om (((987 : ℕ) : ℝ) / ((3200 : ℕ) : ℝ)) with hO10 | hO10
                    ·
                      exact gt_of_box (BAOCert.P3.Box_017.box Om hO4.le hO10 wb hW9.le hwd h hh) (by decide +kernel)
                    ·
                      exact gt_of_box (BAOCert.P3.Box_016.box Om hO10.le hO8 wb hW9.le hwd h hh) (by decide +kernel)
                ·
                  rcases le_or_gt wb (((20439 / 800000 : ℚ)) : ℝ) with hW9 | hW9
                  ·
                    rcases le_or_gt Om (((41 : ℕ) : ℝ) / ((128 : ℕ) : ℝ)) with hO10 | hO10
                    ·
                      exact gt_of_box (BAOCert.P3.Box_015.box Om hO8.le hO10 wb hW7.le hW9 h hh) (by decide +kernel)
                    ·
                      exact gt_of_box (BAOCert.P3.Box_014.box Om hO10.le hO6 wb hW7.le hW9 h hh) (by decide +kernel)
                  ·
                    rcases le_or_gt Om (((41 : ℕ) : ℝ) / ((128 : ℕ) : ℝ)) with hO10 | hO10
                    ·
                      exact gt_of_box (BAOCert.P3.Box_013.box Om hO8.le hO10 wb hW9.le hwd h hh) (by decide +kernel)
                    ·
                      exact gt_of_box (BAOCert.P3.Box_012.box Om hO10.le hO6 wb hW9.le hwd h hh) (by decide +kernel)
            ·
              rcases le_or_gt wb (((10027 / 400000 : ℚ)) : ℝ) with hW7 | hW7
              ·
                rcases le_or_gt Om (((541 : ℕ) : ℝ) / ((1600 : ℕ) : ℝ)) with hO8 | hO8
                ·
                  rcases le_or_gt wb (((19669 / 800000 : ℚ)) : ℝ) with hW9 | hW9
                  ·
                    rcases le_or_gt Om (((1063 : ℕ) : ℝ) / ((3200 : ℕ) : ℝ)) with hO10 | hO10
                    ·
                      exact gt_of_box (BAOCert.P3.Box_011.box Om hO6.le hO10 wb hW5.le hW9 h hh) (by decide +kernel)
                    ·
                      exact gt_of_box (BAOCert.P3.Box_010.box Om hO10.le hO8 wb hW5.le hW9 h hh) (by decide +kernel)
                  ·
                    rcases le_or_gt Om (((1063 : ℕ) : ℝ) / ((3200 : ℕ) : ℝ)) with hO10 | hO10
                    ·
                      exact gt_of_box (BAOCert.P3.Box_009.box Om hO6.le hO10 wb hW9.le hW7 h hh) (by decide +kernel)
                    ·
                      exact gt_of_box (BAOCert.P3.Box_008.box Om hO10.le hO8 wb hW9.le hW7 h hh) (by decide +kernel)
                ·
                  rcases le_or_gt wb (((19669 / 800000 : ℚ)) : ℝ) with hW9 | hW9
                  ·
                    exact gt_of_box (BAOCert.P3.Box_007.box Om hO8.le hU wb hW5.le hW9 h hh) (by decide +kernel)
                  ·
                    exact gt_of_box (BAOCert.P3.Box_006.box Om hO8.le hU wb hW9.le hW7 h hh) (by decide +kernel)
              ·
                rcases le_or_gt Om (((541 : ℕ) : ℝ) / ((1600 : ℕ) : ℝ)) with hO8 | hO8
                ·
                  rcases le_or_gt wb (((20439 / 800000 : ℚ)) : ℝ) with hW9 | hW9
                  ·
                    exact gt_of_box (BAOCert.P3.Box_005.box Om hO6.le hO8 wb hW7.le hW9 h hh) (by decide +kernel)
                  ·
                    rcases le_or_gt Om (((1063 : ℕ) : ℝ) / ((3200 : ℕ) : ℝ)) with hO10 | hO10
                    ·
                      exact gt_of_box (BAOCert.P3.Box_004.box Om hO6.le hO10 wb hW9.le hwd h hh) (by decide +kernel)
                    ·
                      exact gt_of_box (BAOCert.P3.Box_003.box Om hO10.le hO8 wb hW9.le hwd h hh) (by decide +kernel)
                ·
                  rcases le_or_gt wb (((20439 / 800000 : ℚ)) : ℝ) with hW9 | hW9
                  ·
                    exact gt_of_box (BAOCert.P3.Box_002.box Om hO8.le hU wb hW7.le hW9 h hh) (by decide +kernel)
                  ·
                    rcases le_or_gt Om (((1101 : ℕ) : ℝ) / ((3200 : ℕ) : ℝ)) with hO10 | hO10
                    ·
                      exact gt_of_box (BAOCert.P3.Box_001.box Om hO8.le hO10 wb hW9.le hwd h hh) (by decide +kernel)
                    ·
                      exact gt_of_box (BAOCert.P3.Box_000.box Om hO10.le hU wb hW9.le hwd h hh) (by decide +kernel)
    ·
      rcases le_or_gt Om (((141 : ℕ) : ℝ) / ((400 : ℕ) : ℝ)) with hS0 | hS0
      · exact gt_of_slab (BAOCert.P2.Ref_O035_R141_400.chi2_slab Om hU.le hS0 _) (by decide +kernel)
      rcases le_or_gt Om (((71 : ℕ) : ℝ) / ((200 : ℕ) : ℝ)) with hS1 | hS1
      · exact gt_of_slab (BAOCert.P2.Ref_R141_400_R71_200.chi2_slab Om hS0.le hS1 _) (by decide +kernel)
      rcases le_or_gt Om (((36 : ℕ) : ℝ) / ((100 : ℕ) : ℝ)) with hS2 | hS2
      · exact gt_of_slab (BAOCert.P2.Ref_R71_200_O036.chi2_slab Om hS1.le hS2 _) (by decide +kernel)
      rcases le_or_gt Om (((37 : ℕ) : ℝ) / ((100 : ℕ) : ℝ)) with hS3 | hS3
      · exact gt_of_slab (BAOCert.P2.Ref_O036_R37_100.chi2_slab Om hS2.le hS3 _) (by decide +kernel)
      rcases le_or_gt Om (((38 : ℕ) : ℝ) / ((100 : ℕ) : ℝ)) with hS4 | hS4
      · exact gt_of_slab (BAOCert.P2.Ref_R37_100_O038.chi2_slab Om hS3.le hS4 _) (by decide +kernel)
      rcases le_or_gt Om (((40 : ℕ) : ℝ) / ((100 : ℕ) : ℝ)) with hS5 | hS5
      · exact gt_of_slab (BAOCert.P2.Ref_O038_O040.chi2_slab Om hS4.le hS5 _) (by decide +kernel)
      rcases le_or_gt Om (((17 : ℕ) : ℝ) / ((40 : ℕ) : ℝ)) with hS6 | hS6
      · exact gt_of_slab (BAOCert.P2.Ref_O040_R17_40.chi2_slab Om hS5.le hS6 _) (by decide +kernel)
      rcases le_or_gt Om (((45 : ℕ) : ℝ) / ((100 : ℕ) : ℝ)) with hS7 | hS7
      · exact gt_of_slab (BAOCert.P2.Ref_R17_40_O045.chi2_slab Om hS6.le hS7 _) (by decide +kernel)
      rcases le_or_gt Om (((50 : ℕ) : ℝ) / ((100 : ℕ) : ℝ)) with hS8 | hS8
      · exact gt_of_slab (BAOCert.P2.Ref_O045_O050.chi2_slab Om hS7.le hS8 _) (by decide +kernel)
      rcases le_or_gt Om (((11 : ℕ) : ℝ) / ((20 : ℕ) : ℝ)) with hS9 | hS9
      · exact gt_of_slab (BAOCert.P2.Ref_O050_R11_20.chi2_slab Om hS8.le hS9 _) (by decide +kernel)
      rcases le_or_gt Om (((60 : ℕ) : ℝ) / ((100 : ℕ) : ℝ)) with hS10 | hS10
      · exact gt_of_slab (BAOCert.P2.Ref_R11_20_O060.chi2_slab Om hS9.le hS10 _) (by decide +kernel)
      rcases le_or_gt Om (((70 : ℕ) : ℝ) / ((100 : ℕ) : ℝ)) with hS11 | hS11
      · exact gt_of_slab (BAOCert.P2.Ref_O060_O070.chi2_slab Om hS10.le hS11 _) (by decide +kernel)
      rcases le_or_gt Om (((80 : ℕ) : ℝ) / ((100 : ℕ) : ℝ)) with hS12 | hS12
      · exact gt_of_slab (BAOCert.P2.Ref_O070_O080.chi2_slab Om hS11.le hS12 _) (by decide +kernel)
      rcases le_or_gt Om (((90 : ℕ) : ℝ) / ((100 : ℕ) : ℝ)) with hS13 | hS13
      · exact gt_of_slab (BAOCert.P2.Ref_O080_O090.chi2_slab Om hS12.le hS13 _) (by decide +kernel)
      exact gt_of_slab (BAOCert.P2.Ref_O090_O100.chi2_slab Om hS13.le hOb1 _) (by decide +kernel)

/-- Corollary: every H0 ≥ 73 point is more than Δχ² = 25 above an allowed point (h = 0.685901). -/
theorem H0_ge_73_delta_chi2 : ∀ Om h wb : ℝ, 0 ≤ Om → Om ≤ 1 → 73 / 100 ≤ h →
    chi2tot ((29743 : ℕ) / (100000 : ℕ) : ℝ) (((1371802127 / 2000000000 : ℚ)) : ℝ) (((1109 / 50000 : ℚ)) : ℝ) + 25 < chi2tot Om h wb := by
  intro Om h wb hO0 hO1 hh
  have hp := BAOCert.P3.Point.chi2tot_point
  have hx := H0_ge_73_excluded Om h wb hO0 hO1 hh
  push_cast at hp hx ⊢
  linarith

end BAOCert.P3
