import BAOCert.H0.Lemmas
import BAOCert.P2.T_FitFine
import BAOCert.P2.Data

/-! Generated by scripts/certified_numerics/emit_p3.py (untrusted). H9: kernel-checked upper bound of the
BAO+BBN chi^2 at a point, hence of its global minimum. -/

namespace BAOCert.P3.Point
open BAOCert BAOCert.H0 BAOCert.P2 ANSE.BAOBBNH0

def envs : List Iv := [⟨(267656640852960 : ℚ) / (1000000000000000 : ℚ), (267661150270096 : ℚ) / (1000000000000000 : ℚ)⟩, ⟨(8980093744124392 : ℚ) / (20000000000000000 : ℚ), (8980332711532688 : ℚ) / (20000000000000000 : ℚ)⟩, ⟨(761032601904 : ℚ) / (1000000000000 : ℚ), (761032601905 : ℚ) / (1000000000000 : ℚ)⟩, ⟨(11796466787192679 : ℚ) / (20000000000000000 : ℚ), (11796789403948199 : ℚ) / (20000000000000000 : ℚ)⟩, ⟨(677383258600 : ℚ) / (1000000000000 : ℚ), (677383258601 : ℚ) / (1000000000000 : ℚ)⟩, ⟨(14685438720179756 : ℚ) / (20000000000000000 : ℚ), (14685846800417121 : ℚ) / (20000000000000000 : ℚ)⟩, ⟨(591919781315 : ℚ) / (1000000000000 : ℚ), (591919781316 : ℚ) / (1000000000000 : ℚ)⟩, ⟨(18794681414802300 : ℚ) / (20000000000000000 : ℚ), (18795205840426801 : ℚ) / (20000000000000000 : ℚ)⟩, ⟨(475574401919 : ℚ) / (1000000000000 : ℚ), (475574401920 : ℚ) / (1000000000000 : ℚ)⟩, ⟨(20279130785876203 : ℚ) / (20000000000000000 : ℚ), (20279694817175477 : ℚ) / (20000000000000000 : ℚ)⟩, ⟨(435968730406 : ℚ) / (1000000000000 : ℚ), (435968730407 : ℚ) / (1000000000000 : ℚ)⟩, ⟨(292534235876 : ℚ) / (1000000000000 : ℚ), (292534235877 : ℚ) / (1000000000000 : ℚ)⟩, ⟨(26318935983824944 : ℚ) / (20000000000000000 : ℚ), (26319643449635668 : ℚ) / (20000000000000000 : ℚ)⟩]

/-- χ²_total(Om = 0.29743, h = 0.6859010635, ω_b = 0.02218) ≤ 10.2897. -/
theorem chi2tot_point : chi2tot (((29743 : ℕ) : ℝ) / ((100000 : ℕ) : ℝ)) (((1371802127 / 2000000000 : ℚ)) : ℝ) (((1109 / 50000 : ℚ)) : ℝ) ≤ ((102897 / 10000 : ℚ) : ℝ) := by
  have h0 := BAOCert.P2.T_FitFine.wV_z0295
  have h1 := BAOCert.P2.T_FitFine.chi_z0510
  have h2 := BAOCert.P2.T_FitFine.invE_z0510
  have h3 := BAOCert.P2.T_FitFine.chi_z0706
  have h4 := BAOCert.P2.T_FitFine.invE_z0706
  have h5 := BAOCert.P2.T_FitFine.chi_z0934
  have h6 := BAOCert.P2.T_FitFine.invE_z0934
  have h7 := BAOCert.P2.T_FitFine.chi_z1321
  have h8 := BAOCert.P2.T_FitFine.invE_z1321
  have h9 := BAOCert.P2.T_FitFine.chi_z1484
  have h10 := BAOCert.P2.T_FitFine.invE_z1484
  have h11 := BAOCert.P2.T_FitFine.invE_z2330
  have h12 := BAOCert.P2.T_FitFine.chi_z2330
  have henv := env_ok envs (Data.xsOf ((((29743 : ℕ) : ℝ) / ((100000 : ℕ) : ℝ)))) (List.Forall₂.cons h0 (List.Forall₂.cons h1 (List.Forall₂.cons h2 (List.Forall₂.cons h3 (List.Forall₂.cons h4 (List.Forall₂.cons h5 (List.Forall₂.cons h6 (List.Forall₂.cons h7 (List.Forall₂.cons h8 (List.Forall₂.cons h9 (List.Forall₂.cons h10 (List.Forall₂.cons h11 (List.Forall₂.cons h12 List.Forall₂.nil)))))))))))))
  have hcb : omegaCb (((1371802127 / 2000000000 : ℚ)) : ℝ) (((29743 : ℕ) : ℝ) / ((100000 : ℕ) : ℝ)) = (((55714799112811800768847 / 400000000000000000000000 : ℚ)) : ℝ) := by unfold omegaCb omegaNu; push_cast; norm_num
  have hrd := rdIv_mem (55714799112811800768847 / 400000000000000000000000 : ℚ) (1109 / 50000 : ℚ) 2 5 60 25 (by decide +kernel)
  rw [← hcb] at hrd
  have hc : (299792.458 : ℝ) = ((299792458 / 1000 : ℚ) : ℝ) := by norm_num
  have hlo : (((2053373 / 69550 : ℚ)) : ℝ) - (((1 / 10000000 : ℚ)) : ℝ) ≤ 299792.458 / (100 * ((((1371802127 / 2000000000 : ℚ)) : ℝ) * (((rdIv (55714799112811800768847 / 400000000000000000000000 : ℚ) (1109 / 50000 : ℚ) 2 5 60 25).hi : ℚ) : ℝ))) := by
    have hq0 : (2053373 / 69550 : ℚ) - (1 / 10000000 : ℚ) ≤ (299792458 / 1000 : ℚ) / (100 * ((1371802127 / 2000000000 : ℚ) * (rdIv (55714799112811800768847 / 400000000000000000000000 : ℚ) (1109 / 50000 : ℚ) 2 5 60 25).hi)) := by decide +kernel
    have := (Rat.cast_le (K := ℝ)).2 hq0
    rw [hc]; push_cast at this ⊢; exact this
  have hhi : 299792.458 / (100 * ((((1371802127 / 2000000000 : ℚ)) : ℝ) * (((rdIv (55714799112811800768847 / 400000000000000000000000 : ℚ) (1109 / 50000 : ℚ) 2 5 60 25).lo : ℚ) : ℝ))) ≤ (((2053373 / 69550 : ℚ)) : ℝ) + (((1 / 10000000 : ℚ)) : ℝ) := by
    have hq0 : (299792458 / 1000 : ℚ) / (100 * ((1371802127 / 2000000000 : ℚ) * (rdIv (55714799112811800768847 / 400000000000000000000000 : ℚ) (1109 / 50000 : ℚ) 2 5 60 25).lo)) ≤ (2053373 / 69550 : ℚ) + (1 / 10000000 : ℚ) := by decide +kernel
    have := (Rat.cast_le (K := ℝ)).2 hq0
    rw [hc]; push_cast at this ⊢; exact this
  have hrlo : (0 : ℝ) < (((rdIv (55714799112811800768847 / 400000000000000000000000 : ℚ) (1109 / 50000 : ℚ) 2 5 60 25).lo : ℚ) : ℝ) := by
    have : (0 : ℚ) < (rdIv (55714799112811800768847 / 400000000000000000000000 : ℚ) (1109 / 50000 : ℚ) 2 5 60 25).lo := by decide +kernel
    exact_mod_cast this
  have hK := Kof_near (rdIv (55714799112811800768847 / 400000000000000000000000 : ℚ) (1109 / 50000 : ℚ) 2 5 60 25).lo (rdIv (55714799112811800768847 / 400000000000000000000000 : ℚ) (1109 / 50000 : ℚ) 2 5 60 25).hi (2053373 / 69550 : ℚ) (1 / 10000000 : ℚ) (by norm_num) hrd hrlo hlo hhi
  have hchi := chi2_upper_Kin Data.Pent Data.dR (2053373 / 69550 : ℚ) _ _ henv (102897 / 10000 : ℚ) (1 / 10000000 : ℚ) (by norm_num) (by decide +kernel) (by decide +kernel) _ hK
  unfold chi2tot
  have hp : (((((1109 / 50000 : ℚ)) : ℝ) - 0.02218) / 0.00055) ^ 2 = 0 := by norm_num
  rw [hp, add_zero]
  exact hchi

end BAOCert.P3.Point
