#!/usr/bin/env python3
"""Generate the tables and numbers of the certified-BAO paper from the committed P1 result files.

Writes gen_numbers.tex (macros) and table_*.tex (complete tabulars) next to this script.
"""

from __future__ import annotations

import json
from fractions import Fraction
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
R = REPO / "results" / "certified_numerics" / "P1_bao"
C = Fraction(299792458, 10154300)


def frac(s: str) -> Fraction:
    n, d = s.split("/")
    return Fraction(int(n), int(d))


AUDIT_SHORT = [("CVODE $10^{-7}$", 0), ("GK quad.", 1), ("astropy", 2), ("CVODE $10^{-3}$", 3), ("CVODE $10^{-2}$", 4)]


def wrap(spec: str, header: str, rows: list[str]) -> str:
    return "\\begin{tabular}{" + spec + "}\\toprule\n" + header + " \\\\\n\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n"


def sci(x: float) -> str:
    m, e = f"{x:.2e}".split("e")
    return f"{m}\\times10^{{{int(e)}}}"


def main() -> None:
    res = json.loads((R / "result.json").read_text())
    fit = json.loads((R / "bounds_Fit.json").read_text())["redshifts"]
    labels = res["labels"]
    m: dict[str, str] = {}

    rows = []
    for k in labels:
        b = fit[k]
        lo, hi = frac(b["chi_lo"]), frac(b["chi_hi"])
        ilo, ihi = frac(b["invE_lo"]), frac(b["invE_hi"])
        rows.append(f"{float(Fraction(b['z'])):.3f} & {b['n']} & {float(lo):.7f} & {float(hi):.7f} & ${sci(b['chi_rel_width'])}$ & "
                    f"[{float(C * lo):.4f}, {float(C * hi):.4f}] & [{float(C * ilo):.5f}, {float(C * ihi):.5f}] \\\\")
    (HERE / "table_enclosures.tex").write_text(wrap("@{}rrcccll@{}", "$z$ & $n$ & $\\chi$ lower & $\\chi$ upper & rel. width & $D_M/r_d$ & $D_H/r_d$", rows))
    m["MaxWidth"] = sci(res["H1"]["max_rel_width"])
    m["MinWidth"] = sci(min(res["H1"]["rel_widths"].values()))

    def pos(v: dict[str, object]) -> str:
        if v["inside"]:
            return "in"
        return f"out (${'+' if v['above_hi_by'] else '-'}{sci(v['above_hi_by'] or v['below_lo_by'])}$)"

    groups = [("rusty-SUNDIALS CVODE, default ($r_{\\rm tol}=10^{-7}$)", res["H2"]["detail"]["rust_cvode_default"]),
              ("rusty-SUNDIALS Gauss--Kronrod, default", res["H2"]["detail"]["rust_quadrature_default"]),
              ("astropy 6.1.7, $T_{\\rm CMB}=0$", res["H2"]["detail"]["astropy_6.1.7_Tcmb0_0"]),
              ("rusty-SUNDIALS CVODE, $r_{\\rm tol}=10^{-3}$", res["H4"]["detail"]["cvode_rtol1e-3"]),
              ("rusty-SUNDIALS CVODE, $r_{\\rm tol}=10^{-2}$", res["H4"]["detail"]["cvode_rtol1e-2"])]
    rows = [f"{float(Fraction(fit[k]['z'])):.3f} & " + " & ".join(pos(d[k]) for _, d in groups) + " \\\\" for k in labels]
    head = "$z$ & " + " & ".join(short for short, _ in AUDIT_SHORT)
    (HERE / "table_audit.tex").write_text(wrap("@{}r" + "c" * len(groups) + "@{}", head, rows))
    m["LooseOut"] = str(sum(not v["inside"] for v in res["H4"]["detail"]["cvode_rtol1e-2"].values()))
    m["NZ"] = str(len(labels))

    rows = []
    for r in res["desi_dr2_comparison"]:
        q = r["quantity"].replace("_over_rs", "/r_d").replace("DM", "D_M").replace("DH", "D_H").replace("DV", "D_V")
        if "pred_lo" in r:
            rows.append(f"{r['z']:.3f} & ${q}$ & {r['measured']:.4f} & {r['sigma']:.4f} & [{r['pred_lo']:.4f}, {r['pred_hi']:.4f}] & [{r['pull_lo']:+.3f}, {r['pull_hi']:+.3f}] \\\\")
        else:
            rows.append(f"{r['z']:.3f} & ${q}$ & {r['measured']:.4f} & -- & not certified & -- \\\\")
    (HERE / "table_desi.tex").write_text(wrap("@{}rlrrll@{}", "$z$ & quantity & DESI DR2 & $\\sigma$ & prediction from certified bounds & pull", rows))

    ax = res["lean"]["axioms"]
    m["NTheorems"] = str(len([k for k in ax if not k.startswith("ctl_")]))
    m["FitSeconds"] = f"{res['lean']['compile_seconds']['Fit']:.0f}"
    m["CoreSeconds"] = f"{res['lean']['compile_seconds']['Core']:.0f}"
    m["NNodes"] = str(fit[labels[-1]]["n"] + 1)
    (HERE / "gen_numbers.tex").write_text("% generated by gen_numbers.py; do not edit\n" + "\n".join(f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in m.items()) + "\n")
    print(json.dumps(m, indent=1))


if __name__ == "__main__":
    main()
